// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mt5-term-api-health-check.proto

#include "mt5-term-api-health-check.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace mt5_term_api {
PROTOBUF_CONSTEXPR StopListeningRequest::StopListeningRequest(
    ::_pbi::ConstantInitialized) {}
struct StopListeningRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR StopListeningRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~StopListeningRequestDefaultTypeInternal() {}
  union {
    StopListeningRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StopListeningRequestDefaultTypeInternal _StopListeningRequest_default_instance_;
PROTOBUF_CONSTEXPR StopListeningReply::StopListeningReply(
    ::_pbi::ConstantInitialized) {}
struct StopListeningReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR StopListeningReplyDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~StopListeningReplyDefaultTypeInternal() {}
  union {
    StopListeningReply _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StopListeningReplyDefaultTypeInternal _StopListeningReply_default_instance_;
PROTOBUF_CONSTEXPR HealthCheckRequest::HealthCheckRequest(
    ::_pbi::ConstantInitialized) {}
struct HealthCheckRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HealthCheckRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~HealthCheckRequestDefaultTypeInternal() {}
  union {
    HealthCheckRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HealthCheckRequestDefaultTypeInternal _HealthCheckRequest_default_instance_;
PROTOBUF_CONSTEXPR HealthCheckReply::HealthCheckReply(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.server_time_seconds_)*/int64_t{0}
  , /*decltype(_impl_.is_connected_to_server_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct HealthCheckReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HealthCheckReplyDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~HealthCheckReplyDefaultTypeInternal() {}
  union {
    HealthCheckReply _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HealthCheckReplyDefaultTypeInternal _HealthCheckReply_default_instance_;
}  // namespace mt5_term_api
static ::_pb::Metadata file_level_metadata_mt5_2dterm_2dapi_2dhealth_2dcheck_2eproto[4];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_mt5_2dterm_2dapi_2dhealth_2dcheck_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_mt5_2dterm_2dapi_2dhealth_2dcheck_2eproto = nullptr;

const uint32_t TableStruct_mt5_2dterm_2dapi_2dhealth_2dcheck_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mt5_term_api::StopListeningRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mt5_term_api::StopListeningReply, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mt5_term_api::HealthCheckRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mt5_term_api::HealthCheckReply, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::mt5_term_api::HealthCheckReply, _impl_.is_connected_to_server_),
  PROTOBUF_FIELD_OFFSET(::mt5_term_api::HealthCheckReply, _impl_.server_time_seconds_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::mt5_term_api::StopListeningRequest)},
  { 6, -1, -1, sizeof(::mt5_term_api::StopListeningReply)},
  { 12, -1, -1, sizeof(::mt5_term_api::HealthCheckRequest)},
  { 18, -1, -1, sizeof(::mt5_term_api::HealthCheckReply)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::mt5_term_api::_StopListeningRequest_default_instance_._instance,
  &::mt5_term_api::_StopListeningReply_default_instance_._instance,
  &::mt5_term_api::_HealthCheckRequest_default_instance_._instance,
  &::mt5_term_api::_HealthCheckReply_default_instance_._instance,
};

const char descriptor_table_protodef_mt5_2dterm_2dapi_2dhealth_2dcheck_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\037mt5-term-api-health-check.proto\022\014mt5_t"
  "erm_api\032\035mt5-term-api-connection.proto\"\026"
  "\n\024StopListeningRequest\"\024\n\022StopListeningR"
  "eply\"\024\n\022HealthCheckRequest\"O\n\020HealthChec"
  "kReply\022\036\n\026is_connected_to_server\030\001 \001(\010\022\033"
  "\n\023server_time_seconds\030\002 \001(\0032\252\001\n\006Health\022I"
  "\n\005Check\022 .mt5_term_api.HealthCheckReques"
  "t\032\036.mt5_term_api.HealthCheckReply\022U\n\rSto"
  "pListening\022\".mt5_term_api.StopListeningR"
  "equest\032 .mt5_term_api.StopListeningReply"
  "BBZ1git.mtapi.io/root/mrpc-proto.git/mt5"
  "/libraries/go\252\002\014mt5_term_apib\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_mt5_2dterm_2dapi_2dhealth_2dcheck_2eproto_deps[1] = {
  &::descriptor_table_mt5_2dterm_2dapi_2dconnection_2eproto,
};
static ::_pbi::once_flag descriptor_table_mt5_2dterm_2dapi_2dhealth_2dcheck_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_mt5_2dterm_2dapi_2dhealth_2dcheck_2eproto = {
    false, false, 476, descriptor_table_protodef_mt5_2dterm_2dapi_2dhealth_2dcheck_2eproto,
    "mt5-term-api-health-check.proto",
    &descriptor_table_mt5_2dterm_2dapi_2dhealth_2dcheck_2eproto_once, descriptor_table_mt5_2dterm_2dapi_2dhealth_2dcheck_2eproto_deps, 1, 4,
    schemas, file_default_instances, TableStruct_mt5_2dterm_2dapi_2dhealth_2dcheck_2eproto::offsets,
    file_level_metadata_mt5_2dterm_2dapi_2dhealth_2dcheck_2eproto, file_level_enum_descriptors_mt5_2dterm_2dapi_2dhealth_2dcheck_2eproto,
    file_level_service_descriptors_mt5_2dterm_2dapi_2dhealth_2dcheck_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_mt5_2dterm_2dapi_2dhealth_2dcheck_2eproto_getter() {
  return &descriptor_table_mt5_2dterm_2dapi_2dhealth_2dcheck_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_mt5_2dterm_2dapi_2dhealth_2dcheck_2eproto(&descriptor_table_mt5_2dterm_2dapi_2dhealth_2dcheck_2eproto);
namespace mt5_term_api {

// ===================================================================

class StopListeningRequest::_Internal {
 public:
};

StopListeningRequest::StopListeningRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:mt5_term_api.StopListeningRequest)
}
StopListeningRequest::StopListeningRequest(const StopListeningRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  StopListeningRequest* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:mt5_term_api.StopListeningRequest)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData StopListeningRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*StopListeningRequest::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata StopListeningRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_mt5_2dterm_2dapi_2dhealth_2dcheck_2eproto_getter, &descriptor_table_mt5_2dterm_2dapi_2dhealth_2dcheck_2eproto_once,
      file_level_metadata_mt5_2dterm_2dapi_2dhealth_2dcheck_2eproto[0]);
}

// ===================================================================

class StopListeningReply::_Internal {
 public:
};

StopListeningReply::StopListeningReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:mt5_term_api.StopListeningReply)
}
StopListeningReply::StopListeningReply(const StopListeningReply& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  StopListeningReply* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:mt5_term_api.StopListeningReply)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData StopListeningReply::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*StopListeningReply::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata StopListeningReply::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_mt5_2dterm_2dapi_2dhealth_2dcheck_2eproto_getter, &descriptor_table_mt5_2dterm_2dapi_2dhealth_2dcheck_2eproto_once,
      file_level_metadata_mt5_2dterm_2dapi_2dhealth_2dcheck_2eproto[1]);
}

// ===================================================================

class HealthCheckRequest::_Internal {
 public:
};

HealthCheckRequest::HealthCheckRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:mt5_term_api.HealthCheckRequest)
}
HealthCheckRequest::HealthCheckRequest(const HealthCheckRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  HealthCheckRequest* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:mt5_term_api.HealthCheckRequest)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData HealthCheckRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*HealthCheckRequest::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata HealthCheckRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_mt5_2dterm_2dapi_2dhealth_2dcheck_2eproto_getter, &descriptor_table_mt5_2dterm_2dapi_2dhealth_2dcheck_2eproto_once,
      file_level_metadata_mt5_2dterm_2dapi_2dhealth_2dcheck_2eproto[2]);
}

// ===================================================================

class HealthCheckReply::_Internal {
 public:
};

HealthCheckReply::HealthCheckReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:mt5_term_api.HealthCheckReply)
}
HealthCheckReply::HealthCheckReply(const HealthCheckReply& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  HealthCheckReply* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.server_time_seconds_){}
    , decltype(_impl_.is_connected_to_server_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.server_time_seconds_, &from._impl_.server_time_seconds_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.is_connected_to_server_) -
    reinterpret_cast<char*>(&_impl_.server_time_seconds_)) + sizeof(_impl_.is_connected_to_server_));
  // @@protoc_insertion_point(copy_constructor:mt5_term_api.HealthCheckReply)
}

inline void HealthCheckReply::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.server_time_seconds_){int64_t{0}}
    , decltype(_impl_.is_connected_to_server_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

HealthCheckReply::~HealthCheckReply() {
  // @@protoc_insertion_point(destructor:mt5_term_api.HealthCheckReply)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void HealthCheckReply::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void HealthCheckReply::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void HealthCheckReply::Clear() {
// @@protoc_insertion_point(message_clear_start:mt5_term_api.HealthCheckReply)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.server_time_seconds_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.is_connected_to_server_) -
      reinterpret_cast<char*>(&_impl_.server_time_seconds_)) + sizeof(_impl_.is_connected_to_server_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* HealthCheckReply::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bool is_connected_to_server = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.is_connected_to_server_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 server_time_seconds = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.server_time_seconds_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* HealthCheckReply::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mt5_term_api.HealthCheckReply)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bool is_connected_to_server = 1;
  if (this->_internal_is_connected_to_server() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(1, this->_internal_is_connected_to_server(), target);
  }

  // int64 server_time_seconds = 2;
  if (this->_internal_server_time_seconds() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(2, this->_internal_server_time_seconds(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mt5_term_api.HealthCheckReply)
  return target;
}

size_t HealthCheckReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mt5_term_api.HealthCheckReply)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 server_time_seconds = 2;
  if (this->_internal_server_time_seconds() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_server_time_seconds());
  }

  // bool is_connected_to_server = 1;
  if (this->_internal_is_connected_to_server() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData HealthCheckReply::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    HealthCheckReply::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*HealthCheckReply::GetClassData() const { return &_class_data_; }


void HealthCheckReply::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<HealthCheckReply*>(&to_msg);
  auto& from = static_cast<const HealthCheckReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:mt5_term_api.HealthCheckReply)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_server_time_seconds() != 0) {
    _this->_internal_set_server_time_seconds(from._internal_server_time_seconds());
  }
  if (from._internal_is_connected_to_server() != 0) {
    _this->_internal_set_is_connected_to_server(from._internal_is_connected_to_server());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void HealthCheckReply::CopyFrom(const HealthCheckReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mt5_term_api.HealthCheckReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool HealthCheckReply::IsInitialized() const {
  return true;
}

void HealthCheckReply::InternalSwap(HealthCheckReply* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(HealthCheckReply, _impl_.is_connected_to_server_)
      + sizeof(HealthCheckReply::_impl_.is_connected_to_server_)
      - PROTOBUF_FIELD_OFFSET(HealthCheckReply, _impl_.server_time_seconds_)>(
          reinterpret_cast<char*>(&_impl_.server_time_seconds_),
          reinterpret_cast<char*>(&other->_impl_.server_time_seconds_));
}

::PROTOBUF_NAMESPACE_ID::Metadata HealthCheckReply::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_mt5_2dterm_2dapi_2dhealth_2dcheck_2eproto_getter, &descriptor_table_mt5_2dterm_2dapi_2dhealth_2dcheck_2eproto_once,
      file_level_metadata_mt5_2dterm_2dapi_2dhealth_2dcheck_2eproto[3]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace mt5_term_api
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::mt5_term_api::StopListeningRequest*
Arena::CreateMaybeMessage< ::mt5_term_api::StopListeningRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::mt5_term_api::StopListeningRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::mt5_term_api::StopListeningReply*
Arena::CreateMaybeMessage< ::mt5_term_api::StopListeningReply >(Arena* arena) {
  return Arena::CreateMessageInternal< ::mt5_term_api::StopListeningReply >(arena);
}
template<> PROTOBUF_NOINLINE ::mt5_term_api::HealthCheckRequest*
Arena::CreateMaybeMessage< ::mt5_term_api::HealthCheckRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::mt5_term_api::HealthCheckRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::mt5_term_api::HealthCheckReply*
Arena::CreateMaybeMessage< ::mt5_term_api::HealthCheckReply >(Arena* arena) {
  return Arena::CreateMessageInternal< ::mt5_term_api::HealthCheckReply >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
