// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: mt5-term-api-admin.proto

#include "mt5-term-api-admin.pb.h"
#include "mt5-term-api-admin.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace mrpc_admin {

static const char* AdminApi_method_names[] = {
  "/mrpc_admin.AdminApi/ActiveTerminals",
  "/mrpc_admin.AdminApi/ActiveTerminalsCluster",
  "/mrpc_admin.AdminApi/SystemUsage",
  "/mrpc_admin.AdminApi/ListLogFiles",
  "/mrpc_admin.AdminApi/GetLogFile",
  "/mrpc_admin.AdminApi/GetEventLogEntries",
  "/mrpc_admin.AdminApi/CaptureSessionScreenshot",
  "/mrpc_admin.AdminApi/CaptureSessionScreenshotOnPod",
  "/mrpc_admin.AdminApi/RefreshMrpcRest",
  "/mrpc_admin.AdminApi/GetVersion",
  "/mrpc_admin.AdminApi/GetTerminalJournal",
  "/mrpc_admin.AdminApi/GetAllLogs",
  "/mrpc_admin.AdminApi/GetSessionRestoreLogs",
  "/mrpc_admin.AdminApi/GetSessionRestoreStatus",
};

std::unique_ptr< AdminApi::Stub> AdminApi::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< AdminApi::Stub> stub(new AdminApi::Stub(channel, options));
  return stub;
}

AdminApi::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ActiveTerminals_(AdminApi_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ActiveTerminalsCluster_(AdminApi_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SystemUsage_(AdminApi_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListLogFiles_(AdminApi_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetLogFile_(AdminApi_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetEventLogEntries_(AdminApi_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CaptureSessionScreenshot_(AdminApi_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CaptureSessionScreenshotOnPod_(AdminApi_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RefreshMrpcRest_(AdminApi_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetVersion_(AdminApi_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetTerminalJournal_(AdminApi_method_names[10], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetAllLogs_(AdminApi_method_names[11], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetSessionRestoreLogs_(AdminApi_method_names[12], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetSessionRestoreStatus_(AdminApi_method_names[13], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status AdminApi::Stub::ActiveTerminals(::grpc::ClientContext* context, const ::mrpc_admin::ActiveTerminalsRequest& request, ::mrpc_admin::ActiveTerminalsReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mrpc_admin::ActiveTerminalsRequest, ::mrpc_admin::ActiveTerminalsReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ActiveTerminals_, context, request, response);
}

void AdminApi::Stub::async::ActiveTerminals(::grpc::ClientContext* context, const ::mrpc_admin::ActiveTerminalsRequest* request, ::mrpc_admin::ActiveTerminalsReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mrpc_admin::ActiveTerminalsRequest, ::mrpc_admin::ActiveTerminalsReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ActiveTerminals_, context, request, response, std::move(f));
}

void AdminApi::Stub::async::ActiveTerminals(::grpc::ClientContext* context, const ::mrpc_admin::ActiveTerminalsRequest* request, ::mrpc_admin::ActiveTerminalsReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ActiveTerminals_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mrpc_admin::ActiveTerminalsReply>* AdminApi::Stub::PrepareAsyncActiveTerminalsRaw(::grpc::ClientContext* context, const ::mrpc_admin::ActiveTerminalsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::mrpc_admin::ActiveTerminalsReply, ::mrpc_admin::ActiveTerminalsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ActiveTerminals_, context, request);
}

::grpc::ClientAsyncResponseReader< ::mrpc_admin::ActiveTerminalsReply>* AdminApi::Stub::AsyncActiveTerminalsRaw(::grpc::ClientContext* context, const ::mrpc_admin::ActiveTerminalsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncActiveTerminalsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AdminApi::Stub::ActiveTerminalsCluster(::grpc::ClientContext* context, const ::mrpc_admin::ActiveTerminalsRequest& request, ::mrpc_admin::ActiveTerminalsClusterReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mrpc_admin::ActiveTerminalsRequest, ::mrpc_admin::ActiveTerminalsClusterReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ActiveTerminalsCluster_, context, request, response);
}

void AdminApi::Stub::async::ActiveTerminalsCluster(::grpc::ClientContext* context, const ::mrpc_admin::ActiveTerminalsRequest* request, ::mrpc_admin::ActiveTerminalsClusterReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mrpc_admin::ActiveTerminalsRequest, ::mrpc_admin::ActiveTerminalsClusterReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ActiveTerminalsCluster_, context, request, response, std::move(f));
}

void AdminApi::Stub::async::ActiveTerminalsCluster(::grpc::ClientContext* context, const ::mrpc_admin::ActiveTerminalsRequest* request, ::mrpc_admin::ActiveTerminalsClusterReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ActiveTerminalsCluster_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mrpc_admin::ActiveTerminalsClusterReply>* AdminApi::Stub::PrepareAsyncActiveTerminalsClusterRaw(::grpc::ClientContext* context, const ::mrpc_admin::ActiveTerminalsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::mrpc_admin::ActiveTerminalsClusterReply, ::mrpc_admin::ActiveTerminalsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ActiveTerminalsCluster_, context, request);
}

::grpc::ClientAsyncResponseReader< ::mrpc_admin::ActiveTerminalsClusterReply>* AdminApi::Stub::AsyncActiveTerminalsClusterRaw(::grpc::ClientContext* context, const ::mrpc_admin::ActiveTerminalsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncActiveTerminalsClusterRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AdminApi::Stub::SystemUsage(::grpc::ClientContext* context, const ::mrpc_admin::ActiveTerminalsRequest& request, ::mrpc_admin::SystemUsageReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mrpc_admin::ActiveTerminalsRequest, ::mrpc_admin::SystemUsageReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SystemUsage_, context, request, response);
}

void AdminApi::Stub::async::SystemUsage(::grpc::ClientContext* context, const ::mrpc_admin::ActiveTerminalsRequest* request, ::mrpc_admin::SystemUsageReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mrpc_admin::ActiveTerminalsRequest, ::mrpc_admin::SystemUsageReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SystemUsage_, context, request, response, std::move(f));
}

void AdminApi::Stub::async::SystemUsage(::grpc::ClientContext* context, const ::mrpc_admin::ActiveTerminalsRequest* request, ::mrpc_admin::SystemUsageReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SystemUsage_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mrpc_admin::SystemUsageReply>* AdminApi::Stub::PrepareAsyncSystemUsageRaw(::grpc::ClientContext* context, const ::mrpc_admin::ActiveTerminalsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::mrpc_admin::SystemUsageReply, ::mrpc_admin::ActiveTerminalsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SystemUsage_, context, request);
}

::grpc::ClientAsyncResponseReader< ::mrpc_admin::SystemUsageReply>* AdminApi::Stub::AsyncSystemUsageRaw(::grpc::ClientContext* context, const ::mrpc_admin::ActiveTerminalsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSystemUsageRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AdminApi::Stub::ListLogFiles(::grpc::ClientContext* context, const ::mrpc_admin::ActiveTerminalsRequest& request, ::mrpc_admin::ListLogFilesReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mrpc_admin::ActiveTerminalsRequest, ::mrpc_admin::ListLogFilesReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListLogFiles_, context, request, response);
}

void AdminApi::Stub::async::ListLogFiles(::grpc::ClientContext* context, const ::mrpc_admin::ActiveTerminalsRequest* request, ::mrpc_admin::ListLogFilesReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mrpc_admin::ActiveTerminalsRequest, ::mrpc_admin::ListLogFilesReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListLogFiles_, context, request, response, std::move(f));
}

void AdminApi::Stub::async::ListLogFiles(::grpc::ClientContext* context, const ::mrpc_admin::ActiveTerminalsRequest* request, ::mrpc_admin::ListLogFilesReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListLogFiles_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mrpc_admin::ListLogFilesReply>* AdminApi::Stub::PrepareAsyncListLogFilesRaw(::grpc::ClientContext* context, const ::mrpc_admin::ActiveTerminalsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::mrpc_admin::ListLogFilesReply, ::mrpc_admin::ActiveTerminalsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListLogFiles_, context, request);
}

::grpc::ClientAsyncResponseReader< ::mrpc_admin::ListLogFilesReply>* AdminApi::Stub::AsyncListLogFilesRaw(::grpc::ClientContext* context, const ::mrpc_admin::ActiveTerminalsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListLogFilesRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AdminApi::Stub::GetLogFile(::grpc::ClientContext* context, const ::mrpc_admin::GetLogFileRequest& request, ::mrpc_admin::GetLogFileReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mrpc_admin::GetLogFileRequest, ::mrpc_admin::GetLogFileReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetLogFile_, context, request, response);
}

void AdminApi::Stub::async::GetLogFile(::grpc::ClientContext* context, const ::mrpc_admin::GetLogFileRequest* request, ::mrpc_admin::GetLogFileReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mrpc_admin::GetLogFileRequest, ::mrpc_admin::GetLogFileReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetLogFile_, context, request, response, std::move(f));
}

void AdminApi::Stub::async::GetLogFile(::grpc::ClientContext* context, const ::mrpc_admin::GetLogFileRequest* request, ::mrpc_admin::GetLogFileReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetLogFile_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mrpc_admin::GetLogFileReply>* AdminApi::Stub::PrepareAsyncGetLogFileRaw(::grpc::ClientContext* context, const ::mrpc_admin::GetLogFileRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::mrpc_admin::GetLogFileReply, ::mrpc_admin::GetLogFileRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetLogFile_, context, request);
}

::grpc::ClientAsyncResponseReader< ::mrpc_admin::GetLogFileReply>* AdminApi::Stub::AsyncGetLogFileRaw(::grpc::ClientContext* context, const ::mrpc_admin::GetLogFileRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetLogFileRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AdminApi::Stub::GetEventLogEntries(::grpc::ClientContext* context, const ::mrpc_admin::GetEventLogEntriesRequest& request, ::mrpc_admin::GetEventLogEntriesReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mrpc_admin::GetEventLogEntriesRequest, ::mrpc_admin::GetEventLogEntriesReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetEventLogEntries_, context, request, response);
}

void AdminApi::Stub::async::GetEventLogEntries(::grpc::ClientContext* context, const ::mrpc_admin::GetEventLogEntriesRequest* request, ::mrpc_admin::GetEventLogEntriesReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mrpc_admin::GetEventLogEntriesRequest, ::mrpc_admin::GetEventLogEntriesReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetEventLogEntries_, context, request, response, std::move(f));
}

void AdminApi::Stub::async::GetEventLogEntries(::grpc::ClientContext* context, const ::mrpc_admin::GetEventLogEntriesRequest* request, ::mrpc_admin::GetEventLogEntriesReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetEventLogEntries_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mrpc_admin::GetEventLogEntriesReply>* AdminApi::Stub::PrepareAsyncGetEventLogEntriesRaw(::grpc::ClientContext* context, const ::mrpc_admin::GetEventLogEntriesRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::mrpc_admin::GetEventLogEntriesReply, ::mrpc_admin::GetEventLogEntriesRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetEventLogEntries_, context, request);
}

::grpc::ClientAsyncResponseReader< ::mrpc_admin::GetEventLogEntriesReply>* AdminApi::Stub::AsyncGetEventLogEntriesRaw(::grpc::ClientContext* context, const ::mrpc_admin::GetEventLogEntriesRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetEventLogEntriesRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AdminApi::Stub::CaptureSessionScreenshot(::grpc::ClientContext* context, const ::mrpc_admin::CaptureSessionScreenshotRequest& request, ::mrpc_admin::CaptureSessionScreenshotReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mrpc_admin::CaptureSessionScreenshotRequest, ::mrpc_admin::CaptureSessionScreenshotReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CaptureSessionScreenshot_, context, request, response);
}

void AdminApi::Stub::async::CaptureSessionScreenshot(::grpc::ClientContext* context, const ::mrpc_admin::CaptureSessionScreenshotRequest* request, ::mrpc_admin::CaptureSessionScreenshotReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mrpc_admin::CaptureSessionScreenshotRequest, ::mrpc_admin::CaptureSessionScreenshotReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CaptureSessionScreenshot_, context, request, response, std::move(f));
}

void AdminApi::Stub::async::CaptureSessionScreenshot(::grpc::ClientContext* context, const ::mrpc_admin::CaptureSessionScreenshotRequest* request, ::mrpc_admin::CaptureSessionScreenshotReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CaptureSessionScreenshot_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mrpc_admin::CaptureSessionScreenshotReply>* AdminApi::Stub::PrepareAsyncCaptureSessionScreenshotRaw(::grpc::ClientContext* context, const ::mrpc_admin::CaptureSessionScreenshotRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::mrpc_admin::CaptureSessionScreenshotReply, ::mrpc_admin::CaptureSessionScreenshotRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CaptureSessionScreenshot_, context, request);
}

::grpc::ClientAsyncResponseReader< ::mrpc_admin::CaptureSessionScreenshotReply>* AdminApi::Stub::AsyncCaptureSessionScreenshotRaw(::grpc::ClientContext* context, const ::mrpc_admin::CaptureSessionScreenshotRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCaptureSessionScreenshotRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AdminApi::Stub::CaptureSessionScreenshotOnPod(::grpc::ClientContext* context, const ::mrpc_admin::CaptureSessionScreenshotOnPodRequest& request, ::mrpc_admin::CaptureSessionScreenshotReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mrpc_admin::CaptureSessionScreenshotOnPodRequest, ::mrpc_admin::CaptureSessionScreenshotReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CaptureSessionScreenshotOnPod_, context, request, response);
}

void AdminApi::Stub::async::CaptureSessionScreenshotOnPod(::grpc::ClientContext* context, const ::mrpc_admin::CaptureSessionScreenshotOnPodRequest* request, ::mrpc_admin::CaptureSessionScreenshotReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mrpc_admin::CaptureSessionScreenshotOnPodRequest, ::mrpc_admin::CaptureSessionScreenshotReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CaptureSessionScreenshotOnPod_, context, request, response, std::move(f));
}

void AdminApi::Stub::async::CaptureSessionScreenshotOnPod(::grpc::ClientContext* context, const ::mrpc_admin::CaptureSessionScreenshotOnPodRequest* request, ::mrpc_admin::CaptureSessionScreenshotReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CaptureSessionScreenshotOnPod_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mrpc_admin::CaptureSessionScreenshotReply>* AdminApi::Stub::PrepareAsyncCaptureSessionScreenshotOnPodRaw(::grpc::ClientContext* context, const ::mrpc_admin::CaptureSessionScreenshotOnPodRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::mrpc_admin::CaptureSessionScreenshotReply, ::mrpc_admin::CaptureSessionScreenshotOnPodRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CaptureSessionScreenshotOnPod_, context, request);
}

::grpc::ClientAsyncResponseReader< ::mrpc_admin::CaptureSessionScreenshotReply>* AdminApi::Stub::AsyncCaptureSessionScreenshotOnPodRaw(::grpc::ClientContext* context, const ::mrpc_admin::CaptureSessionScreenshotOnPodRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCaptureSessionScreenshotOnPodRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AdminApi::Stub::RefreshMrpcRest(::grpc::ClientContext* context, const ::mrpc_admin::ActiveTerminalsRequest& request, ::mrpc_admin::RefreshMrpcRestReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mrpc_admin::ActiveTerminalsRequest, ::mrpc_admin::RefreshMrpcRestReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RefreshMrpcRest_, context, request, response);
}

void AdminApi::Stub::async::RefreshMrpcRest(::grpc::ClientContext* context, const ::mrpc_admin::ActiveTerminalsRequest* request, ::mrpc_admin::RefreshMrpcRestReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mrpc_admin::ActiveTerminalsRequest, ::mrpc_admin::RefreshMrpcRestReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RefreshMrpcRest_, context, request, response, std::move(f));
}

void AdminApi::Stub::async::RefreshMrpcRest(::grpc::ClientContext* context, const ::mrpc_admin::ActiveTerminalsRequest* request, ::mrpc_admin::RefreshMrpcRestReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RefreshMrpcRest_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mrpc_admin::RefreshMrpcRestReply>* AdminApi::Stub::PrepareAsyncRefreshMrpcRestRaw(::grpc::ClientContext* context, const ::mrpc_admin::ActiveTerminalsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::mrpc_admin::RefreshMrpcRestReply, ::mrpc_admin::ActiveTerminalsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RefreshMrpcRest_, context, request);
}

::grpc::ClientAsyncResponseReader< ::mrpc_admin::RefreshMrpcRestReply>* AdminApi::Stub::AsyncRefreshMrpcRestRaw(::grpc::ClientContext* context, const ::mrpc_admin::ActiveTerminalsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRefreshMrpcRestRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AdminApi::Stub::GetVersion(::grpc::ClientContext* context, const ::mrpc_admin::VersionRequest& request, ::mrpc_admin::VersionReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mrpc_admin::VersionRequest, ::mrpc_admin::VersionReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetVersion_, context, request, response);
}

void AdminApi::Stub::async::GetVersion(::grpc::ClientContext* context, const ::mrpc_admin::VersionRequest* request, ::mrpc_admin::VersionReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mrpc_admin::VersionRequest, ::mrpc_admin::VersionReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetVersion_, context, request, response, std::move(f));
}

void AdminApi::Stub::async::GetVersion(::grpc::ClientContext* context, const ::mrpc_admin::VersionRequest* request, ::mrpc_admin::VersionReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetVersion_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mrpc_admin::VersionReply>* AdminApi::Stub::PrepareAsyncGetVersionRaw(::grpc::ClientContext* context, const ::mrpc_admin::VersionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::mrpc_admin::VersionReply, ::mrpc_admin::VersionRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetVersion_, context, request);
}

::grpc::ClientAsyncResponseReader< ::mrpc_admin::VersionReply>* AdminApi::Stub::AsyncGetVersionRaw(::grpc::ClientContext* context, const ::mrpc_admin::VersionRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetVersionRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AdminApi::Stub::GetTerminalJournal(::grpc::ClientContext* context, const ::mrpc_admin::GetTerminalJournalRequest& request, ::mrpc_admin::GetTerminalJournalReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mrpc_admin::GetTerminalJournalRequest, ::mrpc_admin::GetTerminalJournalReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetTerminalJournal_, context, request, response);
}

void AdminApi::Stub::async::GetTerminalJournal(::grpc::ClientContext* context, const ::mrpc_admin::GetTerminalJournalRequest* request, ::mrpc_admin::GetTerminalJournalReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mrpc_admin::GetTerminalJournalRequest, ::mrpc_admin::GetTerminalJournalReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetTerminalJournal_, context, request, response, std::move(f));
}

void AdminApi::Stub::async::GetTerminalJournal(::grpc::ClientContext* context, const ::mrpc_admin::GetTerminalJournalRequest* request, ::mrpc_admin::GetTerminalJournalReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetTerminalJournal_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mrpc_admin::GetTerminalJournalReply>* AdminApi::Stub::PrepareAsyncGetTerminalJournalRaw(::grpc::ClientContext* context, const ::mrpc_admin::GetTerminalJournalRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::mrpc_admin::GetTerminalJournalReply, ::mrpc_admin::GetTerminalJournalRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetTerminalJournal_, context, request);
}

::grpc::ClientAsyncResponseReader< ::mrpc_admin::GetTerminalJournalReply>* AdminApi::Stub::AsyncGetTerminalJournalRaw(::grpc::ClientContext* context, const ::mrpc_admin::GetTerminalJournalRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetTerminalJournalRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AdminApi::Stub::GetAllLogs(::grpc::ClientContext* context, const ::mrpc_admin::GetAllLogsRequest& request, ::mrpc_admin::GetAllLogsReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mrpc_admin::GetAllLogsRequest, ::mrpc_admin::GetAllLogsReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetAllLogs_, context, request, response);
}

void AdminApi::Stub::async::GetAllLogs(::grpc::ClientContext* context, const ::mrpc_admin::GetAllLogsRequest* request, ::mrpc_admin::GetAllLogsReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mrpc_admin::GetAllLogsRequest, ::mrpc_admin::GetAllLogsReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetAllLogs_, context, request, response, std::move(f));
}

void AdminApi::Stub::async::GetAllLogs(::grpc::ClientContext* context, const ::mrpc_admin::GetAllLogsRequest* request, ::mrpc_admin::GetAllLogsReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetAllLogs_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mrpc_admin::GetAllLogsReply>* AdminApi::Stub::PrepareAsyncGetAllLogsRaw(::grpc::ClientContext* context, const ::mrpc_admin::GetAllLogsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::mrpc_admin::GetAllLogsReply, ::mrpc_admin::GetAllLogsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetAllLogs_, context, request);
}

::grpc::ClientAsyncResponseReader< ::mrpc_admin::GetAllLogsReply>* AdminApi::Stub::AsyncGetAllLogsRaw(::grpc::ClientContext* context, const ::mrpc_admin::GetAllLogsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetAllLogsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AdminApi::Stub::GetSessionRestoreLogs(::grpc::ClientContext* context, const ::mrpc_admin::GetSessionRestoreLogsRequest& request, ::mrpc_admin::GetSessionRestoreLogsReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mrpc_admin::GetSessionRestoreLogsRequest, ::mrpc_admin::GetSessionRestoreLogsReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetSessionRestoreLogs_, context, request, response);
}

void AdminApi::Stub::async::GetSessionRestoreLogs(::grpc::ClientContext* context, const ::mrpc_admin::GetSessionRestoreLogsRequest* request, ::mrpc_admin::GetSessionRestoreLogsReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mrpc_admin::GetSessionRestoreLogsRequest, ::mrpc_admin::GetSessionRestoreLogsReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetSessionRestoreLogs_, context, request, response, std::move(f));
}

void AdminApi::Stub::async::GetSessionRestoreLogs(::grpc::ClientContext* context, const ::mrpc_admin::GetSessionRestoreLogsRequest* request, ::mrpc_admin::GetSessionRestoreLogsReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetSessionRestoreLogs_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mrpc_admin::GetSessionRestoreLogsReply>* AdminApi::Stub::PrepareAsyncGetSessionRestoreLogsRaw(::grpc::ClientContext* context, const ::mrpc_admin::GetSessionRestoreLogsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::mrpc_admin::GetSessionRestoreLogsReply, ::mrpc_admin::GetSessionRestoreLogsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetSessionRestoreLogs_, context, request);
}

::grpc::ClientAsyncResponseReader< ::mrpc_admin::GetSessionRestoreLogsReply>* AdminApi::Stub::AsyncGetSessionRestoreLogsRaw(::grpc::ClientContext* context, const ::mrpc_admin::GetSessionRestoreLogsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetSessionRestoreLogsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AdminApi::Stub::GetSessionRestoreStatus(::grpc::ClientContext* context, const ::mrpc_admin::ActiveTerminalsRequest& request, ::mrpc_admin::GetSessionRestoreStatusReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mrpc_admin::ActiveTerminalsRequest, ::mrpc_admin::GetSessionRestoreStatusReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetSessionRestoreStatus_, context, request, response);
}

void AdminApi::Stub::async::GetSessionRestoreStatus(::grpc::ClientContext* context, const ::mrpc_admin::ActiveTerminalsRequest* request, ::mrpc_admin::GetSessionRestoreStatusReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mrpc_admin::ActiveTerminalsRequest, ::mrpc_admin::GetSessionRestoreStatusReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetSessionRestoreStatus_, context, request, response, std::move(f));
}

void AdminApi::Stub::async::GetSessionRestoreStatus(::grpc::ClientContext* context, const ::mrpc_admin::ActiveTerminalsRequest* request, ::mrpc_admin::GetSessionRestoreStatusReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetSessionRestoreStatus_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mrpc_admin::GetSessionRestoreStatusReply>* AdminApi::Stub::PrepareAsyncGetSessionRestoreStatusRaw(::grpc::ClientContext* context, const ::mrpc_admin::ActiveTerminalsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::mrpc_admin::GetSessionRestoreStatusReply, ::mrpc_admin::ActiveTerminalsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetSessionRestoreStatus_, context, request);
}

::grpc::ClientAsyncResponseReader< ::mrpc_admin::GetSessionRestoreStatusReply>* AdminApi::Stub::AsyncGetSessionRestoreStatusRaw(::grpc::ClientContext* context, const ::mrpc_admin::ActiveTerminalsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetSessionRestoreStatusRaw(context, request, cq);
  result->StartCall();
  return result;
}

AdminApi::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AdminApi_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AdminApi::Service, ::mrpc_admin::ActiveTerminalsRequest, ::mrpc_admin::ActiveTerminalsReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AdminApi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mrpc_admin::ActiveTerminalsRequest* req,
             ::mrpc_admin::ActiveTerminalsReply* resp) {
               return service->ActiveTerminals(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AdminApi_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AdminApi::Service, ::mrpc_admin::ActiveTerminalsRequest, ::mrpc_admin::ActiveTerminalsClusterReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AdminApi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mrpc_admin::ActiveTerminalsRequest* req,
             ::mrpc_admin::ActiveTerminalsClusterReply* resp) {
               return service->ActiveTerminalsCluster(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AdminApi_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AdminApi::Service, ::mrpc_admin::ActiveTerminalsRequest, ::mrpc_admin::SystemUsageReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AdminApi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mrpc_admin::ActiveTerminalsRequest* req,
             ::mrpc_admin::SystemUsageReply* resp) {
               return service->SystemUsage(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AdminApi_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AdminApi::Service, ::mrpc_admin::ActiveTerminalsRequest, ::mrpc_admin::ListLogFilesReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AdminApi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mrpc_admin::ActiveTerminalsRequest* req,
             ::mrpc_admin::ListLogFilesReply* resp) {
               return service->ListLogFiles(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AdminApi_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AdminApi::Service, ::mrpc_admin::GetLogFileRequest, ::mrpc_admin::GetLogFileReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AdminApi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mrpc_admin::GetLogFileRequest* req,
             ::mrpc_admin::GetLogFileReply* resp) {
               return service->GetLogFile(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AdminApi_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AdminApi::Service, ::mrpc_admin::GetEventLogEntriesRequest, ::mrpc_admin::GetEventLogEntriesReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AdminApi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mrpc_admin::GetEventLogEntriesRequest* req,
             ::mrpc_admin::GetEventLogEntriesReply* resp) {
               return service->GetEventLogEntries(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AdminApi_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AdminApi::Service, ::mrpc_admin::CaptureSessionScreenshotRequest, ::mrpc_admin::CaptureSessionScreenshotReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AdminApi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mrpc_admin::CaptureSessionScreenshotRequest* req,
             ::mrpc_admin::CaptureSessionScreenshotReply* resp) {
               return service->CaptureSessionScreenshot(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AdminApi_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AdminApi::Service, ::mrpc_admin::CaptureSessionScreenshotOnPodRequest, ::mrpc_admin::CaptureSessionScreenshotReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AdminApi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mrpc_admin::CaptureSessionScreenshotOnPodRequest* req,
             ::mrpc_admin::CaptureSessionScreenshotReply* resp) {
               return service->CaptureSessionScreenshotOnPod(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AdminApi_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AdminApi::Service, ::mrpc_admin::ActiveTerminalsRequest, ::mrpc_admin::RefreshMrpcRestReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AdminApi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mrpc_admin::ActiveTerminalsRequest* req,
             ::mrpc_admin::RefreshMrpcRestReply* resp) {
               return service->RefreshMrpcRest(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AdminApi_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AdminApi::Service, ::mrpc_admin::VersionRequest, ::mrpc_admin::VersionReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AdminApi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mrpc_admin::VersionRequest* req,
             ::mrpc_admin::VersionReply* resp) {
               return service->GetVersion(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AdminApi_method_names[10],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AdminApi::Service, ::mrpc_admin::GetTerminalJournalRequest, ::mrpc_admin::GetTerminalJournalReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AdminApi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mrpc_admin::GetTerminalJournalRequest* req,
             ::mrpc_admin::GetTerminalJournalReply* resp) {
               return service->GetTerminalJournal(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AdminApi_method_names[11],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AdminApi::Service, ::mrpc_admin::GetAllLogsRequest, ::mrpc_admin::GetAllLogsReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AdminApi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mrpc_admin::GetAllLogsRequest* req,
             ::mrpc_admin::GetAllLogsReply* resp) {
               return service->GetAllLogs(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AdminApi_method_names[12],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AdminApi::Service, ::mrpc_admin::GetSessionRestoreLogsRequest, ::mrpc_admin::GetSessionRestoreLogsReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AdminApi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mrpc_admin::GetSessionRestoreLogsRequest* req,
             ::mrpc_admin::GetSessionRestoreLogsReply* resp) {
               return service->GetSessionRestoreLogs(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AdminApi_method_names[13],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AdminApi::Service, ::mrpc_admin::ActiveTerminalsRequest, ::mrpc_admin::GetSessionRestoreStatusReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AdminApi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mrpc_admin::ActiveTerminalsRequest* req,
             ::mrpc_admin::GetSessionRestoreStatusReply* resp) {
               return service->GetSessionRestoreStatus(ctx, req, resp);
             }, this)));
}

AdminApi::Service::~Service() {
}

::grpc::Status AdminApi::Service::ActiveTerminals(::grpc::ServerContext* context, const ::mrpc_admin::ActiveTerminalsRequest* request, ::mrpc_admin::ActiveTerminalsReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AdminApi::Service::ActiveTerminalsCluster(::grpc::ServerContext* context, const ::mrpc_admin::ActiveTerminalsRequest* request, ::mrpc_admin::ActiveTerminalsClusterReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AdminApi::Service::SystemUsage(::grpc::ServerContext* context, const ::mrpc_admin::ActiveTerminalsRequest* request, ::mrpc_admin::SystemUsageReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AdminApi::Service::ListLogFiles(::grpc::ServerContext* context, const ::mrpc_admin::ActiveTerminalsRequest* request, ::mrpc_admin::ListLogFilesReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AdminApi::Service::GetLogFile(::grpc::ServerContext* context, const ::mrpc_admin::GetLogFileRequest* request, ::mrpc_admin::GetLogFileReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AdminApi::Service::GetEventLogEntries(::grpc::ServerContext* context, const ::mrpc_admin::GetEventLogEntriesRequest* request, ::mrpc_admin::GetEventLogEntriesReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AdminApi::Service::CaptureSessionScreenshot(::grpc::ServerContext* context, const ::mrpc_admin::CaptureSessionScreenshotRequest* request, ::mrpc_admin::CaptureSessionScreenshotReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AdminApi::Service::CaptureSessionScreenshotOnPod(::grpc::ServerContext* context, const ::mrpc_admin::CaptureSessionScreenshotOnPodRequest* request, ::mrpc_admin::CaptureSessionScreenshotReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AdminApi::Service::RefreshMrpcRest(::grpc::ServerContext* context, const ::mrpc_admin::ActiveTerminalsRequest* request, ::mrpc_admin::RefreshMrpcRestReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AdminApi::Service::GetVersion(::grpc::ServerContext* context, const ::mrpc_admin::VersionRequest* request, ::mrpc_admin::VersionReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AdminApi::Service::GetTerminalJournal(::grpc::ServerContext* context, const ::mrpc_admin::GetTerminalJournalRequest* request, ::mrpc_admin::GetTerminalJournalReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AdminApi::Service::GetAllLogs(::grpc::ServerContext* context, const ::mrpc_admin::GetAllLogsRequest* request, ::mrpc_admin::GetAllLogsReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AdminApi::Service::GetSessionRestoreLogs(::grpc::ServerContext* context, const ::mrpc_admin::GetSessionRestoreLogsRequest* request, ::mrpc_admin::GetSessionRestoreLogsReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AdminApi::Service::GetSessionRestoreStatus(::grpc::ServerContext* context, const ::mrpc_admin::ActiveTerminalsRequest* request, ::mrpc_admin::GetSessionRestoreStatusReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace mrpc_admin

