// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mt5-term-api-health-check.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_mt5_2dterm_2dapi_2dhealth_2dcheck_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_mt5_2dterm_2dapi_2dhealth_2dcheck_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021006 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_bases.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "mt5-term-api-connection.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_mt5_2dterm_2dapi_2dhealth_2dcheck_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_mt5_2dterm_2dapi_2dhealth_2dcheck_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_mt5_2dterm_2dapi_2dhealth_2dcheck_2eproto;
namespace mt5_term_api {
class HealthCheckReply;
struct HealthCheckReplyDefaultTypeInternal;
extern HealthCheckReplyDefaultTypeInternal _HealthCheckReply_default_instance_;
class HealthCheckRequest;
struct HealthCheckRequestDefaultTypeInternal;
extern HealthCheckRequestDefaultTypeInternal _HealthCheckRequest_default_instance_;
class StopListeningReply;
struct StopListeningReplyDefaultTypeInternal;
extern StopListeningReplyDefaultTypeInternal _StopListeningReply_default_instance_;
class StopListeningRequest;
struct StopListeningRequestDefaultTypeInternal;
extern StopListeningRequestDefaultTypeInternal _StopListeningRequest_default_instance_;
}  // namespace mt5_term_api
PROTOBUF_NAMESPACE_OPEN
template<> ::mt5_term_api::HealthCheckReply* Arena::CreateMaybeMessage<::mt5_term_api::HealthCheckReply>(Arena*);
template<> ::mt5_term_api::HealthCheckRequest* Arena::CreateMaybeMessage<::mt5_term_api::HealthCheckRequest>(Arena*);
template<> ::mt5_term_api::StopListeningReply* Arena::CreateMaybeMessage<::mt5_term_api::StopListeningReply>(Arena*);
template<> ::mt5_term_api::StopListeningRequest* Arena::CreateMaybeMessage<::mt5_term_api::StopListeningRequest>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace mt5_term_api {

// ===================================================================

class StopListeningRequest final :
    public ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:mt5_term_api.StopListeningRequest) */ {
 public:
  inline StopListeningRequest() : StopListeningRequest(nullptr) {}
  explicit PROTOBUF_CONSTEXPR StopListeningRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  StopListeningRequest(const StopListeningRequest& from);
  StopListeningRequest(StopListeningRequest&& from) noexcept
    : StopListeningRequest() {
    *this = ::std::move(from);
  }

  inline StopListeningRequest& operator=(const StopListeningRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline StopListeningRequest& operator=(StopListeningRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const StopListeningRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const StopListeningRequest* internal_default_instance() {
    return reinterpret_cast<const StopListeningRequest*>(
               &_StopListeningRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(StopListeningRequest& a, StopListeningRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(StopListeningRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StopListeningRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  StopListeningRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<StopListeningRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const StopListeningRequest& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const StopListeningRequest& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }
  public:

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mt5_term_api.StopListeningRequest";
  }
  protected:
  explicit StopListeningRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:mt5_term_api.StopListeningRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
  };
  friend struct ::TableStruct_mt5_2dterm_2dapi_2dhealth_2dcheck_2eproto;
};
// -------------------------------------------------------------------

class StopListeningReply final :
    public ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:mt5_term_api.StopListeningReply) */ {
 public:
  inline StopListeningReply() : StopListeningReply(nullptr) {}
  explicit PROTOBUF_CONSTEXPR StopListeningReply(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  StopListeningReply(const StopListeningReply& from);
  StopListeningReply(StopListeningReply&& from) noexcept
    : StopListeningReply() {
    *this = ::std::move(from);
  }

  inline StopListeningReply& operator=(const StopListeningReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline StopListeningReply& operator=(StopListeningReply&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const StopListeningReply& default_instance() {
    return *internal_default_instance();
  }
  static inline const StopListeningReply* internal_default_instance() {
    return reinterpret_cast<const StopListeningReply*>(
               &_StopListeningReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(StopListeningReply& a, StopListeningReply& b) {
    a.Swap(&b);
  }
  inline void Swap(StopListeningReply* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StopListeningReply* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  StopListeningReply* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<StopListeningReply>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const StopListeningReply& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const StopListeningReply& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }
  public:

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mt5_term_api.StopListeningReply";
  }
  protected:
  explicit StopListeningReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:mt5_term_api.StopListeningReply)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
  };
  friend struct ::TableStruct_mt5_2dterm_2dapi_2dhealth_2dcheck_2eproto;
};
// -------------------------------------------------------------------

class HealthCheckRequest final :
    public ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:mt5_term_api.HealthCheckRequest) */ {
 public:
  inline HealthCheckRequest() : HealthCheckRequest(nullptr) {}
  explicit PROTOBUF_CONSTEXPR HealthCheckRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  HealthCheckRequest(const HealthCheckRequest& from);
  HealthCheckRequest(HealthCheckRequest&& from) noexcept
    : HealthCheckRequest() {
    *this = ::std::move(from);
  }

  inline HealthCheckRequest& operator=(const HealthCheckRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline HealthCheckRequest& operator=(HealthCheckRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HealthCheckRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const HealthCheckRequest* internal_default_instance() {
    return reinterpret_cast<const HealthCheckRequest*>(
               &_HealthCheckRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(HealthCheckRequest& a, HealthCheckRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(HealthCheckRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HealthCheckRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HealthCheckRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<HealthCheckRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const HealthCheckRequest& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const HealthCheckRequest& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }
  public:

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mt5_term_api.HealthCheckRequest";
  }
  protected:
  explicit HealthCheckRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:mt5_term_api.HealthCheckRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
  };
  friend struct ::TableStruct_mt5_2dterm_2dapi_2dhealth_2dcheck_2eproto;
};
// -------------------------------------------------------------------

class HealthCheckReply final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mt5_term_api.HealthCheckReply) */ {
 public:
  inline HealthCheckReply() : HealthCheckReply(nullptr) {}
  ~HealthCheckReply() override;
  explicit PROTOBUF_CONSTEXPR HealthCheckReply(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  HealthCheckReply(const HealthCheckReply& from);
  HealthCheckReply(HealthCheckReply&& from) noexcept
    : HealthCheckReply() {
    *this = ::std::move(from);
  }

  inline HealthCheckReply& operator=(const HealthCheckReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline HealthCheckReply& operator=(HealthCheckReply&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HealthCheckReply& default_instance() {
    return *internal_default_instance();
  }
  static inline const HealthCheckReply* internal_default_instance() {
    return reinterpret_cast<const HealthCheckReply*>(
               &_HealthCheckReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(HealthCheckReply& a, HealthCheckReply& b) {
    a.Swap(&b);
  }
  inline void Swap(HealthCheckReply* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HealthCheckReply* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HealthCheckReply* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<HealthCheckReply>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const HealthCheckReply& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const HealthCheckReply& from) {
    HealthCheckReply::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(HealthCheckReply* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mt5_term_api.HealthCheckReply";
  }
  protected:
  explicit HealthCheckReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kServerTimeSecondsFieldNumber = 2,
    kIsConnectedToServerFieldNumber = 1,
  };
  // int64 server_time_seconds = 2;
  void clear_server_time_seconds();
  int64_t server_time_seconds() const;
  void set_server_time_seconds(int64_t value);
  private:
  int64_t _internal_server_time_seconds() const;
  void _internal_set_server_time_seconds(int64_t value);
  public:

  // bool is_connected_to_server = 1;
  void clear_is_connected_to_server();
  bool is_connected_to_server() const;
  void set_is_connected_to_server(bool value);
  private:
  bool _internal_is_connected_to_server() const;
  void _internal_set_is_connected_to_server(bool value);
  public:

  // @@protoc_insertion_point(class_scope:mt5_term_api.HealthCheckReply)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int64_t server_time_seconds_;
    bool is_connected_to_server_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_mt5_2dterm_2dapi_2dhealth_2dcheck_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// StopListeningRequest

// -------------------------------------------------------------------

// StopListeningReply

// -------------------------------------------------------------------

// HealthCheckRequest

// -------------------------------------------------------------------

// HealthCheckReply

// bool is_connected_to_server = 1;
inline void HealthCheckReply::clear_is_connected_to_server() {
  _impl_.is_connected_to_server_ = false;
}
inline bool HealthCheckReply::_internal_is_connected_to_server() const {
  return _impl_.is_connected_to_server_;
}
inline bool HealthCheckReply::is_connected_to_server() const {
  // @@protoc_insertion_point(field_get:mt5_term_api.HealthCheckReply.is_connected_to_server)
  return _internal_is_connected_to_server();
}
inline void HealthCheckReply::_internal_set_is_connected_to_server(bool value) {
  
  _impl_.is_connected_to_server_ = value;
}
inline void HealthCheckReply::set_is_connected_to_server(bool value) {
  _internal_set_is_connected_to_server(value);
  // @@protoc_insertion_point(field_set:mt5_term_api.HealthCheckReply.is_connected_to_server)
}

// int64 server_time_seconds = 2;
inline void HealthCheckReply::clear_server_time_seconds() {
  _impl_.server_time_seconds_ = int64_t{0};
}
inline int64_t HealthCheckReply::_internal_server_time_seconds() const {
  return _impl_.server_time_seconds_;
}
inline int64_t HealthCheckReply::server_time_seconds() const {
  // @@protoc_insertion_point(field_get:mt5_term_api.HealthCheckReply.server_time_seconds)
  return _internal_server_time_seconds();
}
inline void HealthCheckReply::_internal_set_server_time_seconds(int64_t value) {
  
  _impl_.server_time_seconds_ = value;
}
inline void HealthCheckReply::set_server_time_seconds(int64_t value) {
  _internal_set_server_time_seconds(value);
  // @@protoc_insertion_point(field_set:mt5_term_api.HealthCheckReply.server_time_seconds)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace mt5_term_api

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_mt5_2dterm_2dapi_2dhealth_2dcheck_2eproto
