// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: mt5-term-api-demo-account.proto
#ifndef GRPC_mt5_2dterm_2dapi_2ddemo_2daccount_2eproto__INCLUDED
#define GRPC_mt5_2dterm_2dapi_2ddemo_2daccount_2eproto__INCLUDED

#include "mt5-term-api-demo-account.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace mt5_term_api {

// Demo account creation service.
// Automates the MT5 "Open an Account" wizard via Win32 GUI automation.
// Does NOT require 'id' header — auto-picks any available terminal.
class DemoAccount final {
 public:
  static constexpr char const* service_full_name() {
    return "mt5_term_api.DemoAccount";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Open a demo account. Full wizard flow: search → select → fill form → register.
    // Returns login, password, and investor password for the new demo account.
    // [DefaultValues]
    // {
    //   "company": "MetaQuotes Ltd.",
    //   "firstName": "Test",
    //   "lastName": "User",
    //   "email": "test@test.com",
    //   "phone": "+1234567890",
    //   "timeoutSeconds": "60"
    // }
    virtual ::grpc::Status OpenDemoAccount(::grpc::ClientContext* context, const ::mt5_term_api::GuiDemoOpenAccountRequest& request, ::mt5_term_api::GuiDemoOpenAccountReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mt5_term_api::GuiDemoOpenAccountReply>> AsyncOpenDemoAccount(::grpc::ClientContext* context, const ::mt5_term_api::GuiDemoOpenAccountRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mt5_term_api::GuiDemoOpenAccountReply>>(AsyncOpenDemoAccountRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mt5_term_api::GuiDemoOpenAccountReply>> PrepareAsyncOpenDemoAccount(::grpc::ClientContext* context, const ::mt5_term_api::GuiDemoOpenAccountRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mt5_term_api::GuiDemoOpenAccountReply>>(PrepareAsyncOpenDemoAccountRaw(context, request, cq));
    }
    // Interactive step-by-step demo account opening wizard.
    // Bidirectional streaming session: search company -> select -> form schema -> submit -> 2FA (if any) -> completed.
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::mt5_term_api::GuiDemoInteractiveClientMessage, ::mt5_term_api::GuiDemoInteractiveServerMessage>> DemoOpenAccountInteractive(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::mt5_term_api::GuiDemoInteractiveClientMessage, ::mt5_term_api::GuiDemoInteractiveServerMessage>>(DemoOpenAccountInteractiveRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::mt5_term_api::GuiDemoInteractiveClientMessage, ::mt5_term_api::GuiDemoInteractiveServerMessage>> AsyncDemoOpenAccountInteractive(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::mt5_term_api::GuiDemoInteractiveClientMessage, ::mt5_term_api::GuiDemoInteractiveServerMessage>>(AsyncDemoOpenAccountInteractiveRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::mt5_term_api::GuiDemoInteractiveClientMessage, ::mt5_term_api::GuiDemoInteractiveServerMessage>> PrepareAsyncDemoOpenAccountInteractive(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::mt5_term_api::GuiDemoInteractiveClientMessage, ::mt5_term_api::GuiDemoInteractiveServerMessage>>(PrepareAsyncDemoOpenAccountInteractiveRaw(context, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Open a demo account. Full wizard flow: search → select → fill form → register.
      // Returns login, password, and investor password for the new demo account.
      // [DefaultValues]
      // {
      //   "company": "MetaQuotes Ltd.",
      //   "firstName": "Test",
      //   "lastName": "User",
      //   "email": "test@test.com",
      //   "phone": "+1234567890",
      //   "timeoutSeconds": "60"
      // }
      virtual void OpenDemoAccount(::grpc::ClientContext* context, const ::mt5_term_api::GuiDemoOpenAccountRequest* request, ::mt5_term_api::GuiDemoOpenAccountReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void OpenDemoAccount(::grpc::ClientContext* context, const ::mt5_term_api::GuiDemoOpenAccountRequest* request, ::mt5_term_api::GuiDemoOpenAccountReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Interactive step-by-step demo account opening wizard.
      // Bidirectional streaming session: search company -> select -> form schema -> submit -> 2FA (if any) -> completed.
      virtual void DemoOpenAccountInteractive(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::mt5_term_api::GuiDemoInteractiveClientMessage,::mt5_term_api::GuiDemoInteractiveServerMessage>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mt5_term_api::GuiDemoOpenAccountReply>* AsyncOpenDemoAccountRaw(::grpc::ClientContext* context, const ::mt5_term_api::GuiDemoOpenAccountRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mt5_term_api::GuiDemoOpenAccountReply>* PrepareAsyncOpenDemoAccountRaw(::grpc::ClientContext* context, const ::mt5_term_api::GuiDemoOpenAccountRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderWriterInterface< ::mt5_term_api::GuiDemoInteractiveClientMessage, ::mt5_term_api::GuiDemoInteractiveServerMessage>* DemoOpenAccountInteractiveRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::mt5_term_api::GuiDemoInteractiveClientMessage, ::mt5_term_api::GuiDemoInteractiveServerMessage>* AsyncDemoOpenAccountInteractiveRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::mt5_term_api::GuiDemoInteractiveClientMessage, ::mt5_term_api::GuiDemoInteractiveServerMessage>* PrepareAsyncDemoOpenAccountInteractiveRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status OpenDemoAccount(::grpc::ClientContext* context, const ::mt5_term_api::GuiDemoOpenAccountRequest& request, ::mt5_term_api::GuiDemoOpenAccountReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mt5_term_api::GuiDemoOpenAccountReply>> AsyncOpenDemoAccount(::grpc::ClientContext* context, const ::mt5_term_api::GuiDemoOpenAccountRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mt5_term_api::GuiDemoOpenAccountReply>>(AsyncOpenDemoAccountRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mt5_term_api::GuiDemoOpenAccountReply>> PrepareAsyncOpenDemoAccount(::grpc::ClientContext* context, const ::mt5_term_api::GuiDemoOpenAccountRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mt5_term_api::GuiDemoOpenAccountReply>>(PrepareAsyncOpenDemoAccountRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriter< ::mt5_term_api::GuiDemoInteractiveClientMessage, ::mt5_term_api::GuiDemoInteractiveServerMessage>> DemoOpenAccountInteractive(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::mt5_term_api::GuiDemoInteractiveClientMessage, ::mt5_term_api::GuiDemoInteractiveServerMessage>>(DemoOpenAccountInteractiveRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::mt5_term_api::GuiDemoInteractiveClientMessage, ::mt5_term_api::GuiDemoInteractiveServerMessage>> AsyncDemoOpenAccountInteractive(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::mt5_term_api::GuiDemoInteractiveClientMessage, ::mt5_term_api::GuiDemoInteractiveServerMessage>>(AsyncDemoOpenAccountInteractiveRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::mt5_term_api::GuiDemoInteractiveClientMessage, ::mt5_term_api::GuiDemoInteractiveServerMessage>> PrepareAsyncDemoOpenAccountInteractive(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::mt5_term_api::GuiDemoInteractiveClientMessage, ::mt5_term_api::GuiDemoInteractiveServerMessage>>(PrepareAsyncDemoOpenAccountInteractiveRaw(context, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void OpenDemoAccount(::grpc::ClientContext* context, const ::mt5_term_api::GuiDemoOpenAccountRequest* request, ::mt5_term_api::GuiDemoOpenAccountReply* response, std::function<void(::grpc::Status)>) override;
      void OpenDemoAccount(::grpc::ClientContext* context, const ::mt5_term_api::GuiDemoOpenAccountRequest* request, ::mt5_term_api::GuiDemoOpenAccountReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void DemoOpenAccountInteractive(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::mt5_term_api::GuiDemoInteractiveClientMessage,::mt5_term_api::GuiDemoInteractiveServerMessage>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::mt5_term_api::GuiDemoOpenAccountReply>* AsyncOpenDemoAccountRaw(::grpc::ClientContext* context, const ::mt5_term_api::GuiDemoOpenAccountRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::mt5_term_api::GuiDemoOpenAccountReply>* PrepareAsyncOpenDemoAccountRaw(::grpc::ClientContext* context, const ::mt5_term_api::GuiDemoOpenAccountRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReaderWriter< ::mt5_term_api::GuiDemoInteractiveClientMessage, ::mt5_term_api::GuiDemoInteractiveServerMessage>* DemoOpenAccountInteractiveRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::mt5_term_api::GuiDemoInteractiveClientMessage, ::mt5_term_api::GuiDemoInteractiveServerMessage>* AsyncDemoOpenAccountInteractiveRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::mt5_term_api::GuiDemoInteractiveClientMessage, ::mt5_term_api::GuiDemoInteractiveServerMessage>* PrepareAsyncDemoOpenAccountInteractiveRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_OpenDemoAccount_;
    const ::grpc::internal::RpcMethod rpcmethod_DemoOpenAccountInteractive_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Open a demo account. Full wizard flow: search → select → fill form → register.
    // Returns login, password, and investor password for the new demo account.
    // [DefaultValues]
    // {
    //   "company": "MetaQuotes Ltd.",
    //   "firstName": "Test",
    //   "lastName": "User",
    //   "email": "test@test.com",
    //   "phone": "+1234567890",
    //   "timeoutSeconds": "60"
    // }
    virtual ::grpc::Status OpenDemoAccount(::grpc::ServerContext* context, const ::mt5_term_api::GuiDemoOpenAccountRequest* request, ::mt5_term_api::GuiDemoOpenAccountReply* response);
    // Interactive step-by-step demo account opening wizard.
    // Bidirectional streaming session: search company -> select -> form schema -> submit -> 2FA (if any) -> completed.
    virtual ::grpc::Status DemoOpenAccountInteractive(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::mt5_term_api::GuiDemoInteractiveServerMessage, ::mt5_term_api::GuiDemoInteractiveClientMessage>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_OpenDemoAccount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_OpenDemoAccount() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_OpenDemoAccount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OpenDemoAccount(::grpc::ServerContext* /*context*/, const ::mt5_term_api::GuiDemoOpenAccountRequest* /*request*/, ::mt5_term_api::GuiDemoOpenAccountReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestOpenDemoAccount(::grpc::ServerContext* context, ::mt5_term_api::GuiDemoOpenAccountRequest* request, ::grpc::ServerAsyncResponseWriter< ::mt5_term_api::GuiDemoOpenAccountReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_DemoOpenAccountInteractive : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_DemoOpenAccountInteractive() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_DemoOpenAccountInteractive() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DemoOpenAccountInteractive(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::mt5_term_api::GuiDemoInteractiveServerMessage, ::mt5_term_api::GuiDemoInteractiveClientMessage>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDemoOpenAccountInteractive(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::mt5_term_api::GuiDemoInteractiveServerMessage, ::mt5_term_api::GuiDemoInteractiveClientMessage>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(1, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_OpenDemoAccount<WithAsyncMethod_DemoOpenAccountInteractive<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_OpenDemoAccount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_OpenDemoAccount() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::mt5_term_api::GuiDemoOpenAccountRequest, ::mt5_term_api::GuiDemoOpenAccountReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::mt5_term_api::GuiDemoOpenAccountRequest* request, ::mt5_term_api::GuiDemoOpenAccountReply* response) { return this->OpenDemoAccount(context, request, response); }));}
    void SetMessageAllocatorFor_OpenDemoAccount(
        ::grpc::MessageAllocator< ::mt5_term_api::GuiDemoOpenAccountRequest, ::mt5_term_api::GuiDemoOpenAccountReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::mt5_term_api::GuiDemoOpenAccountRequest, ::mt5_term_api::GuiDemoOpenAccountReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_OpenDemoAccount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OpenDemoAccount(::grpc::ServerContext* /*context*/, const ::mt5_term_api::GuiDemoOpenAccountRequest* /*request*/, ::mt5_term_api::GuiDemoOpenAccountReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* OpenDemoAccount(
      ::grpc::CallbackServerContext* /*context*/, const ::mt5_term_api::GuiDemoOpenAccountRequest* /*request*/, ::mt5_term_api::GuiDemoOpenAccountReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_DemoOpenAccountInteractive : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_DemoOpenAccountInteractive() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackBidiHandler< ::mt5_term_api::GuiDemoInteractiveClientMessage, ::mt5_term_api::GuiDemoInteractiveServerMessage>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->DemoOpenAccountInteractive(context); }));
    }
    ~WithCallbackMethod_DemoOpenAccountInteractive() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DemoOpenAccountInteractive(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::mt5_term_api::GuiDemoInteractiveServerMessage, ::mt5_term_api::GuiDemoInteractiveClientMessage>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::mt5_term_api::GuiDemoInteractiveClientMessage, ::mt5_term_api::GuiDemoInteractiveServerMessage>* DemoOpenAccountInteractive(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef WithCallbackMethod_OpenDemoAccount<WithCallbackMethod_DemoOpenAccountInteractive<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_OpenDemoAccount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_OpenDemoAccount() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_OpenDemoAccount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OpenDemoAccount(::grpc::ServerContext* /*context*/, const ::mt5_term_api::GuiDemoOpenAccountRequest* /*request*/, ::mt5_term_api::GuiDemoOpenAccountReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_DemoOpenAccountInteractive : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_DemoOpenAccountInteractive() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_DemoOpenAccountInteractive() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DemoOpenAccountInteractive(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::mt5_term_api::GuiDemoInteractiveServerMessage, ::mt5_term_api::GuiDemoInteractiveClientMessage>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_OpenDemoAccount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_OpenDemoAccount() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_OpenDemoAccount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OpenDemoAccount(::grpc::ServerContext* /*context*/, const ::mt5_term_api::GuiDemoOpenAccountRequest* /*request*/, ::mt5_term_api::GuiDemoOpenAccountReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestOpenDemoAccount(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_DemoOpenAccountInteractive : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_DemoOpenAccountInteractive() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_DemoOpenAccountInteractive() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DemoOpenAccountInteractive(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::mt5_term_api::GuiDemoInteractiveServerMessage, ::mt5_term_api::GuiDemoInteractiveClientMessage>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDemoOpenAccountInteractive(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(1, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_OpenDemoAccount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_OpenDemoAccount() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->OpenDemoAccount(context, request, response); }));
    }
    ~WithRawCallbackMethod_OpenDemoAccount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OpenDemoAccount(::grpc::ServerContext* /*context*/, const ::mt5_term_api::GuiDemoOpenAccountRequest* /*request*/, ::mt5_term_api::GuiDemoOpenAccountReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* OpenDemoAccount(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_DemoOpenAccountInteractive : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_DemoOpenAccountInteractive() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->DemoOpenAccountInteractive(context); }));
    }
    ~WithRawCallbackMethod_DemoOpenAccountInteractive() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DemoOpenAccountInteractive(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::mt5_term_api::GuiDemoInteractiveServerMessage, ::mt5_term_api::GuiDemoInteractiveClientMessage>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* DemoOpenAccountInteractive(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_OpenDemoAccount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_OpenDemoAccount() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::mt5_term_api::GuiDemoOpenAccountRequest, ::mt5_term_api::GuiDemoOpenAccountReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::mt5_term_api::GuiDemoOpenAccountRequest, ::mt5_term_api::GuiDemoOpenAccountReply>* streamer) {
                       return this->StreamedOpenDemoAccount(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_OpenDemoAccount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status OpenDemoAccount(::grpc::ServerContext* /*context*/, const ::mt5_term_api::GuiDemoOpenAccountRequest* /*request*/, ::mt5_term_api::GuiDemoOpenAccountReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedOpenDemoAccount(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::mt5_term_api::GuiDemoOpenAccountRequest,::mt5_term_api::GuiDemoOpenAccountReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_OpenDemoAccount<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_OpenDemoAccount<Service > StreamedService;
};

}  // namespace mt5_term_api


#endif  // GRPC_mt5_2dterm_2dapi_2ddemo_2daccount_2eproto__INCLUDED
