// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: mt5-term-api-vnc.proto

#include "mt5-term-api-vnc.pb.h"
#include "mt5-term-api-vnc.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace mt5_term_api {

static const char* VncService_method_names[] = {
  "/mt5_term_api.VncService/VncStream",
};

std::unique_ptr< VncService::Stub> VncService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< VncService::Stub> stub(new VncService::Stub(channel, options));
  return stub;
}

VncService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_VncStream_(VncService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::ClientReaderWriter< ::mt5_term_api::VncData, ::mt5_term_api::VncData>* VncService::Stub::VncStreamRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::mt5_term_api::VncData, ::mt5_term_api::VncData>::Create(channel_.get(), rpcmethod_VncStream_, context);
}

void VncService::Stub::async::VncStream(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::mt5_term_api::VncData,::mt5_term_api::VncData>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::mt5_term_api::VncData,::mt5_term_api::VncData>::Create(stub_->channel_.get(), stub_->rpcmethod_VncStream_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::mt5_term_api::VncData, ::mt5_term_api::VncData>* VncService::Stub::AsyncVncStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::mt5_term_api::VncData, ::mt5_term_api::VncData>::Create(channel_.get(), cq, rpcmethod_VncStream_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::mt5_term_api::VncData, ::mt5_term_api::VncData>* VncService::Stub::PrepareAsyncVncStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::mt5_term_api::VncData, ::mt5_term_api::VncData>::Create(channel_.get(), cq, rpcmethod_VncStream_, context, false, nullptr);
}

VncService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VncService_method_names[0],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< VncService::Service, ::mt5_term_api::VncData, ::mt5_term_api::VncData>(
          [](VncService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::mt5_term_api::VncData,
             ::mt5_term_api::VncData>* stream) {
               return service->VncStream(ctx, stream);
             }, this)));
}

VncService::Service::~Service() {
}

::grpc::Status VncService::Service::VncStream(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::mt5_term_api::VncData, ::mt5_term_api::VncData>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace mt5_term_api

