// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: mt5-term-api-charts.proto
#ifndef GRPC_mt5_2dterm_2dapi_2dcharts_2eproto__INCLUDED
#define GRPC_mt5_2dterm_2dapi_2dcharts_2eproto__INCLUDED

#include "mt5-term-api-charts.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace mt5_term_api {

class Charts final {
 public:
  static constexpr char const* service_full_name() {
    return "mt5_term_api.Charts";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status OpenTerminalChartWithEa(::grpc::ClientContext* context, const ::mt5_term_api::OpenTerminalChartWithEaRequest& request, ::mt5_term_api::OpenTerminalChartWithEaReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mt5_term_api::OpenTerminalChartWithEaReply>> AsyncOpenTerminalChartWithEa(::grpc::ClientContext* context, const ::mt5_term_api::OpenTerminalChartWithEaRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mt5_term_api::OpenTerminalChartWithEaReply>>(AsyncOpenTerminalChartWithEaRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mt5_term_api::OpenTerminalChartWithEaReply>> PrepareAsyncOpenTerminalChartWithEa(::grpc::ClientContext* context, const ::mt5_term_api::OpenTerminalChartWithEaRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mt5_term_api::OpenTerminalChartWithEaReply>>(PrepareAsyncOpenTerminalChartWithEaRaw(context, request, cq));
    }
    virtual ::grpc::Status GetEaParams(::grpc::ClientContext* context, const ::mt5_term_api::GetEaParamsRequest& request, ::mt5_term_api::GetEaParamsReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mt5_term_api::GetEaParamsReply>> AsyncGetEaParams(::grpc::ClientContext* context, const ::mt5_term_api::GetEaParamsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mt5_term_api::GetEaParamsReply>>(AsyncGetEaParamsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mt5_term_api::GetEaParamsReply>> PrepareAsyncGetEaParams(::grpc::ClientContext* context, const ::mt5_term_api::GetEaParamsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mt5_term_api::GetEaParamsReply>>(PrepareAsyncGetEaParamsRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void OpenTerminalChartWithEa(::grpc::ClientContext* context, const ::mt5_term_api::OpenTerminalChartWithEaRequest* request, ::mt5_term_api::OpenTerminalChartWithEaReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void OpenTerminalChartWithEa(::grpc::ClientContext* context, const ::mt5_term_api::OpenTerminalChartWithEaRequest* request, ::mt5_term_api::OpenTerminalChartWithEaReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void GetEaParams(::grpc::ClientContext* context, const ::mt5_term_api::GetEaParamsRequest* request, ::mt5_term_api::GetEaParamsReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetEaParams(::grpc::ClientContext* context, const ::mt5_term_api::GetEaParamsRequest* request, ::mt5_term_api::GetEaParamsReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mt5_term_api::OpenTerminalChartWithEaReply>* AsyncOpenTerminalChartWithEaRaw(::grpc::ClientContext* context, const ::mt5_term_api::OpenTerminalChartWithEaRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mt5_term_api::OpenTerminalChartWithEaReply>* PrepareAsyncOpenTerminalChartWithEaRaw(::grpc::ClientContext* context, const ::mt5_term_api::OpenTerminalChartWithEaRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mt5_term_api::GetEaParamsReply>* AsyncGetEaParamsRaw(::grpc::ClientContext* context, const ::mt5_term_api::GetEaParamsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mt5_term_api::GetEaParamsReply>* PrepareAsyncGetEaParamsRaw(::grpc::ClientContext* context, const ::mt5_term_api::GetEaParamsRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status OpenTerminalChartWithEa(::grpc::ClientContext* context, const ::mt5_term_api::OpenTerminalChartWithEaRequest& request, ::mt5_term_api::OpenTerminalChartWithEaReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mt5_term_api::OpenTerminalChartWithEaReply>> AsyncOpenTerminalChartWithEa(::grpc::ClientContext* context, const ::mt5_term_api::OpenTerminalChartWithEaRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mt5_term_api::OpenTerminalChartWithEaReply>>(AsyncOpenTerminalChartWithEaRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mt5_term_api::OpenTerminalChartWithEaReply>> PrepareAsyncOpenTerminalChartWithEa(::grpc::ClientContext* context, const ::mt5_term_api::OpenTerminalChartWithEaRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mt5_term_api::OpenTerminalChartWithEaReply>>(PrepareAsyncOpenTerminalChartWithEaRaw(context, request, cq));
    }
    ::grpc::Status GetEaParams(::grpc::ClientContext* context, const ::mt5_term_api::GetEaParamsRequest& request, ::mt5_term_api::GetEaParamsReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mt5_term_api::GetEaParamsReply>> AsyncGetEaParams(::grpc::ClientContext* context, const ::mt5_term_api::GetEaParamsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mt5_term_api::GetEaParamsReply>>(AsyncGetEaParamsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mt5_term_api::GetEaParamsReply>> PrepareAsyncGetEaParams(::grpc::ClientContext* context, const ::mt5_term_api::GetEaParamsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mt5_term_api::GetEaParamsReply>>(PrepareAsyncGetEaParamsRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void OpenTerminalChartWithEa(::grpc::ClientContext* context, const ::mt5_term_api::OpenTerminalChartWithEaRequest* request, ::mt5_term_api::OpenTerminalChartWithEaReply* response, std::function<void(::grpc::Status)>) override;
      void OpenTerminalChartWithEa(::grpc::ClientContext* context, const ::mt5_term_api::OpenTerminalChartWithEaRequest* request, ::mt5_term_api::OpenTerminalChartWithEaReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetEaParams(::grpc::ClientContext* context, const ::mt5_term_api::GetEaParamsRequest* request, ::mt5_term_api::GetEaParamsReply* response, std::function<void(::grpc::Status)>) override;
      void GetEaParams(::grpc::ClientContext* context, const ::mt5_term_api::GetEaParamsRequest* request, ::mt5_term_api::GetEaParamsReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::mt5_term_api::OpenTerminalChartWithEaReply>* AsyncOpenTerminalChartWithEaRaw(::grpc::ClientContext* context, const ::mt5_term_api::OpenTerminalChartWithEaRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::mt5_term_api::OpenTerminalChartWithEaReply>* PrepareAsyncOpenTerminalChartWithEaRaw(::grpc::ClientContext* context, const ::mt5_term_api::OpenTerminalChartWithEaRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::mt5_term_api::GetEaParamsReply>* AsyncGetEaParamsRaw(::grpc::ClientContext* context, const ::mt5_term_api::GetEaParamsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::mt5_term_api::GetEaParamsReply>* PrepareAsyncGetEaParamsRaw(::grpc::ClientContext* context, const ::mt5_term_api::GetEaParamsRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_OpenTerminalChartWithEa_;
    const ::grpc::internal::RpcMethod rpcmethod_GetEaParams_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status OpenTerminalChartWithEa(::grpc::ServerContext* context, const ::mt5_term_api::OpenTerminalChartWithEaRequest* request, ::mt5_term_api::OpenTerminalChartWithEaReply* response);
    virtual ::grpc::Status GetEaParams(::grpc::ServerContext* context, const ::mt5_term_api::GetEaParamsRequest* request, ::mt5_term_api::GetEaParamsReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_OpenTerminalChartWithEa : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_OpenTerminalChartWithEa() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_OpenTerminalChartWithEa() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OpenTerminalChartWithEa(::grpc::ServerContext* /*context*/, const ::mt5_term_api::OpenTerminalChartWithEaRequest* /*request*/, ::mt5_term_api::OpenTerminalChartWithEaReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestOpenTerminalChartWithEa(::grpc::ServerContext* context, ::mt5_term_api::OpenTerminalChartWithEaRequest* request, ::grpc::ServerAsyncResponseWriter< ::mt5_term_api::OpenTerminalChartWithEaReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetEaParams : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetEaParams() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GetEaParams() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetEaParams(::grpc::ServerContext* /*context*/, const ::mt5_term_api::GetEaParamsRequest* /*request*/, ::mt5_term_api::GetEaParamsReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetEaParams(::grpc::ServerContext* context, ::mt5_term_api::GetEaParamsRequest* request, ::grpc::ServerAsyncResponseWriter< ::mt5_term_api::GetEaParamsReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_OpenTerminalChartWithEa<WithAsyncMethod_GetEaParams<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_OpenTerminalChartWithEa : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_OpenTerminalChartWithEa() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::mt5_term_api::OpenTerminalChartWithEaRequest, ::mt5_term_api::OpenTerminalChartWithEaReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::mt5_term_api::OpenTerminalChartWithEaRequest* request, ::mt5_term_api::OpenTerminalChartWithEaReply* response) { return this->OpenTerminalChartWithEa(context, request, response); }));}
    void SetMessageAllocatorFor_OpenTerminalChartWithEa(
        ::grpc::MessageAllocator< ::mt5_term_api::OpenTerminalChartWithEaRequest, ::mt5_term_api::OpenTerminalChartWithEaReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::mt5_term_api::OpenTerminalChartWithEaRequest, ::mt5_term_api::OpenTerminalChartWithEaReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_OpenTerminalChartWithEa() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OpenTerminalChartWithEa(::grpc::ServerContext* /*context*/, const ::mt5_term_api::OpenTerminalChartWithEaRequest* /*request*/, ::mt5_term_api::OpenTerminalChartWithEaReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* OpenTerminalChartWithEa(
      ::grpc::CallbackServerContext* /*context*/, const ::mt5_term_api::OpenTerminalChartWithEaRequest* /*request*/, ::mt5_term_api::OpenTerminalChartWithEaReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetEaParams : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetEaParams() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::mt5_term_api::GetEaParamsRequest, ::mt5_term_api::GetEaParamsReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::mt5_term_api::GetEaParamsRequest* request, ::mt5_term_api::GetEaParamsReply* response) { return this->GetEaParams(context, request, response); }));}
    void SetMessageAllocatorFor_GetEaParams(
        ::grpc::MessageAllocator< ::mt5_term_api::GetEaParamsRequest, ::mt5_term_api::GetEaParamsReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::mt5_term_api::GetEaParamsRequest, ::mt5_term_api::GetEaParamsReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetEaParams() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetEaParams(::grpc::ServerContext* /*context*/, const ::mt5_term_api::GetEaParamsRequest* /*request*/, ::mt5_term_api::GetEaParamsReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetEaParams(
      ::grpc::CallbackServerContext* /*context*/, const ::mt5_term_api::GetEaParamsRequest* /*request*/, ::mt5_term_api::GetEaParamsReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_OpenTerminalChartWithEa<WithCallbackMethod_GetEaParams<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_OpenTerminalChartWithEa : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_OpenTerminalChartWithEa() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_OpenTerminalChartWithEa() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OpenTerminalChartWithEa(::grpc::ServerContext* /*context*/, const ::mt5_term_api::OpenTerminalChartWithEaRequest* /*request*/, ::mt5_term_api::OpenTerminalChartWithEaReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetEaParams : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetEaParams() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GetEaParams() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetEaParams(::grpc::ServerContext* /*context*/, const ::mt5_term_api::GetEaParamsRequest* /*request*/, ::mt5_term_api::GetEaParamsReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_OpenTerminalChartWithEa : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_OpenTerminalChartWithEa() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_OpenTerminalChartWithEa() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OpenTerminalChartWithEa(::grpc::ServerContext* /*context*/, const ::mt5_term_api::OpenTerminalChartWithEaRequest* /*request*/, ::mt5_term_api::OpenTerminalChartWithEaReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestOpenTerminalChartWithEa(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetEaParams : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetEaParams() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_GetEaParams() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetEaParams(::grpc::ServerContext* /*context*/, const ::mt5_term_api::GetEaParamsRequest* /*request*/, ::mt5_term_api::GetEaParamsReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetEaParams(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_OpenTerminalChartWithEa : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_OpenTerminalChartWithEa() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->OpenTerminalChartWithEa(context, request, response); }));
    }
    ~WithRawCallbackMethod_OpenTerminalChartWithEa() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OpenTerminalChartWithEa(::grpc::ServerContext* /*context*/, const ::mt5_term_api::OpenTerminalChartWithEaRequest* /*request*/, ::mt5_term_api::OpenTerminalChartWithEaReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* OpenTerminalChartWithEa(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetEaParams : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetEaParams() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetEaParams(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetEaParams() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetEaParams(::grpc::ServerContext* /*context*/, const ::mt5_term_api::GetEaParamsRequest* /*request*/, ::mt5_term_api::GetEaParamsReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetEaParams(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_OpenTerminalChartWithEa : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_OpenTerminalChartWithEa() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::mt5_term_api::OpenTerminalChartWithEaRequest, ::mt5_term_api::OpenTerminalChartWithEaReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::mt5_term_api::OpenTerminalChartWithEaRequest, ::mt5_term_api::OpenTerminalChartWithEaReply>* streamer) {
                       return this->StreamedOpenTerminalChartWithEa(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_OpenTerminalChartWithEa() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status OpenTerminalChartWithEa(::grpc::ServerContext* /*context*/, const ::mt5_term_api::OpenTerminalChartWithEaRequest* /*request*/, ::mt5_term_api::OpenTerminalChartWithEaReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedOpenTerminalChartWithEa(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::mt5_term_api::OpenTerminalChartWithEaRequest,::mt5_term_api::OpenTerminalChartWithEaReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetEaParams : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetEaParams() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::mt5_term_api::GetEaParamsRequest, ::mt5_term_api::GetEaParamsReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::mt5_term_api::GetEaParamsRequest, ::mt5_term_api::GetEaParamsReply>* streamer) {
                       return this->StreamedGetEaParams(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetEaParams() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetEaParams(::grpc::ServerContext* /*context*/, const ::mt5_term_api::GetEaParamsRequest* /*request*/, ::mt5_term_api::GetEaParamsReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetEaParams(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::mt5_term_api::GetEaParamsRequest,::mt5_term_api::GetEaParamsReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_OpenTerminalChartWithEa<WithStreamedUnaryMethod_GetEaParams<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_OpenTerminalChartWithEa<WithStreamedUnaryMethod_GetEaParams<Service > > StreamedService;
};

}  // namespace mt5_term_api


#endif  // GRPC_mt5_2dterm_2dapi_2dcharts_2eproto__INCLUDED
