// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mt5-term-api-demo-account.proto

#include "mt5-term-api-demo-account.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace mt5_term_api {
PROTOBUF_CONSTEXPR DemoAccountStreamEvent::DemoAccountStreamEvent(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.step_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.message_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.level_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.timestamp_)*/nullptr
  , /*decltype(_impl_.account_data_)*/nullptr
  , /*decltype(_impl_.elapsed_ms_)*/int64_t{0}
  , /*decltype(_impl_.is_final_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct DemoAccountStreamEventDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DemoAccountStreamEventDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~DemoAccountStreamEventDefaultTypeInternal() {}
  union {
    DemoAccountStreamEvent _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DemoAccountStreamEventDefaultTypeInternal _DemoAccountStreamEvent_default_instance_;
}  // namespace mt5_term_api
static ::_pb::Metadata file_level_metadata_mt5_2dterm_2dapi_2ddemo_2daccount_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_mt5_2dterm_2dapi_2ddemo_2daccount_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_mt5_2dterm_2dapi_2ddemo_2daccount_2eproto = nullptr;

const uint32_t TableStruct_mt5_2dterm_2dapi_2ddemo_2daccount_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mt5_term_api::DemoAccountStreamEvent, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::mt5_term_api::DemoAccountStreamEvent, _impl_.step_),
  PROTOBUF_FIELD_OFFSET(::mt5_term_api::DemoAccountStreamEvent, _impl_.message_),
  PROTOBUF_FIELD_OFFSET(::mt5_term_api::DemoAccountStreamEvent, _impl_.level_),
  PROTOBUF_FIELD_OFFSET(::mt5_term_api::DemoAccountStreamEvent, _impl_.elapsed_ms_),
  PROTOBUF_FIELD_OFFSET(::mt5_term_api::DemoAccountStreamEvent, _impl_.timestamp_),
  PROTOBUF_FIELD_OFFSET(::mt5_term_api::DemoAccountStreamEvent, _impl_.is_final_),
  PROTOBUF_FIELD_OFFSET(::mt5_term_api::DemoAccountStreamEvent, _impl_.account_data_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::mt5_term_api::DemoAccountStreamEvent)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::mt5_term_api::_DemoAccountStreamEvent_default_instance_._instance,
};

const char descriptor_table_protodef_mt5_2dterm_2dapi_2ddemo_2daccount_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\037mt5-term-api-demo-account.proto\022\014mt5_t"
  "erm_api\032\034google/api/annotations.proto\032\026m"
  "t5-term-api-gui.proto\032\037google/protobuf/t"
  "imestamp.proto\"\330\001\n\026DemoAccountStreamEven"
  "t\022\014\n\004step\030\001 \001(\t\022\017\n\007message\030\002 \001(\t\022\r\n\005leve"
  "l\030\003 \001(\t\022\022\n\nelapsed_ms\030\004 \001(\003\022-\n\ttimestamp"
  "\030\005 \001(\0132\032.google.protobuf.Timestamp\022\020\n\010is"
  "_final\030\006 \001(\010\022;\n\014account_data\030\007 \001(\0132%.mt5"
  "_term_api.GuiDemoOpenAccountReply2\301\004\n\013De"
  "moAccount\022\207\001\n\rFindCompanies\022).mt5_term_a"
  "pi.GuiDemoFindCompaniesRequest\032\'.mt5_ter"
  "m_api.GuiDemoFindCompaniesReply\"\"\202\323\344\223\002\034\022"
  "\032/DemoAccount/FindCompanies\022\235\001\n\026ServersA"
  "ndAccountTypes\022+.mt5_term_api.GuiDemoSer"
  "versAndTypesRequest\032).mt5_term_api.GuiDe"
  "moServersAndTypesReply\"+\202\323\344\223\002%\022#/DemoAcc"
  "ount/ServersAndAccountTypes\022|\n\017OpenDemoA"
  "ccount\022\'.mt5_term_api.GuiDemoOpenAccount"
  "Request\032%.mt5_term_api.GuiDemoOpenAccoun"
  "tReply\"\031\202\323\344\223\002\023\022\021/DemoAccount/Open\022\211\001\n\025Op"
  "enDemoAccountStream\022\'.mt5_term_api.GuiDe"
  "moOpenAccountRequest\032$.mt5_term_api.Demo"
  "AccountStreamEvent\"\037\202\323\344\223\002\031\022\027/DemoAccount"
  "/OpenStream0\001BBZ1git.mtapi.io/root/mrpc-"
  "proto.git/mt5/libraries/go\252\002\014mt5_term_ap"
  "ib\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_mt5_2dterm_2dapi_2ddemo_2daccount_2eproto_deps[3] = {
  &::descriptor_table_google_2fapi_2fannotations_2eproto,
  &::descriptor_table_google_2fprotobuf_2ftimestamp_2eproto,
  &::descriptor_table_mt5_2dterm_2dapi_2dgui_2eproto,
};
static ::_pbi::once_flag descriptor_table_mt5_2dterm_2dapi_2ddemo_2daccount_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_mt5_2dterm_2dapi_2ddemo_2daccount_2eproto = {
    false, false, 1009, descriptor_table_protodef_mt5_2dterm_2dapi_2ddemo_2daccount_2eproto,
    "mt5-term-api-demo-account.proto",
    &descriptor_table_mt5_2dterm_2dapi_2ddemo_2daccount_2eproto_once, descriptor_table_mt5_2dterm_2dapi_2ddemo_2daccount_2eproto_deps, 3, 1,
    schemas, file_default_instances, TableStruct_mt5_2dterm_2dapi_2ddemo_2daccount_2eproto::offsets,
    file_level_metadata_mt5_2dterm_2dapi_2ddemo_2daccount_2eproto, file_level_enum_descriptors_mt5_2dterm_2dapi_2ddemo_2daccount_2eproto,
    file_level_service_descriptors_mt5_2dterm_2dapi_2ddemo_2daccount_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_mt5_2dterm_2dapi_2ddemo_2daccount_2eproto_getter() {
  return &descriptor_table_mt5_2dterm_2dapi_2ddemo_2daccount_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_mt5_2dterm_2dapi_2ddemo_2daccount_2eproto(&descriptor_table_mt5_2dterm_2dapi_2ddemo_2daccount_2eproto);
namespace mt5_term_api {

// ===================================================================

class DemoAccountStreamEvent::_Internal {
 public:
  static const ::PROTOBUF_NAMESPACE_ID::Timestamp& timestamp(const DemoAccountStreamEvent* msg);
  static const ::mt5_term_api::GuiDemoOpenAccountReply& account_data(const DemoAccountStreamEvent* msg);
};

const ::PROTOBUF_NAMESPACE_ID::Timestamp&
DemoAccountStreamEvent::_Internal::timestamp(const DemoAccountStreamEvent* msg) {
  return *msg->_impl_.timestamp_;
}
const ::mt5_term_api::GuiDemoOpenAccountReply&
DemoAccountStreamEvent::_Internal::account_data(const DemoAccountStreamEvent* msg) {
  return *msg->_impl_.account_data_;
}
void DemoAccountStreamEvent::clear_timestamp() {
  if (GetArenaForAllocation() == nullptr && _impl_.timestamp_ != nullptr) {
    delete _impl_.timestamp_;
  }
  _impl_.timestamp_ = nullptr;
}
void DemoAccountStreamEvent::clear_account_data() {
  if (GetArenaForAllocation() == nullptr && _impl_.account_data_ != nullptr) {
    delete _impl_.account_data_;
  }
  _impl_.account_data_ = nullptr;
}
DemoAccountStreamEvent::DemoAccountStreamEvent(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:mt5_term_api.DemoAccountStreamEvent)
}
DemoAccountStreamEvent::DemoAccountStreamEvent(const DemoAccountStreamEvent& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  DemoAccountStreamEvent* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.step_){}
    , decltype(_impl_.message_){}
    , decltype(_impl_.level_){}
    , decltype(_impl_.timestamp_){nullptr}
    , decltype(_impl_.account_data_){nullptr}
    , decltype(_impl_.elapsed_ms_){}
    , decltype(_impl_.is_final_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.step_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.step_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_step().empty()) {
    _this->_impl_.step_.Set(from._internal_step(), 
      _this->GetArenaForAllocation());
  }
  _impl_.message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_message().empty()) {
    _this->_impl_.message_.Set(from._internal_message(), 
      _this->GetArenaForAllocation());
  }
  _impl_.level_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.level_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_level().empty()) {
    _this->_impl_.level_.Set(from._internal_level(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_timestamp()) {
    _this->_impl_.timestamp_ = new ::PROTOBUF_NAMESPACE_ID::Timestamp(*from._impl_.timestamp_);
  }
  if (from._internal_has_account_data()) {
    _this->_impl_.account_data_ = new ::mt5_term_api::GuiDemoOpenAccountReply(*from._impl_.account_data_);
  }
  ::memcpy(&_impl_.elapsed_ms_, &from._impl_.elapsed_ms_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.is_final_) -
    reinterpret_cast<char*>(&_impl_.elapsed_ms_)) + sizeof(_impl_.is_final_));
  // @@protoc_insertion_point(copy_constructor:mt5_term_api.DemoAccountStreamEvent)
}

inline void DemoAccountStreamEvent::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.step_){}
    , decltype(_impl_.message_){}
    , decltype(_impl_.level_){}
    , decltype(_impl_.timestamp_){nullptr}
    , decltype(_impl_.account_data_){nullptr}
    , decltype(_impl_.elapsed_ms_){int64_t{0}}
    , decltype(_impl_.is_final_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.step_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.step_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.level_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.level_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

DemoAccountStreamEvent::~DemoAccountStreamEvent() {
  // @@protoc_insertion_point(destructor:mt5_term_api.DemoAccountStreamEvent)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void DemoAccountStreamEvent::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.step_.Destroy();
  _impl_.message_.Destroy();
  _impl_.level_.Destroy();
  if (this != internal_default_instance()) delete _impl_.timestamp_;
  if (this != internal_default_instance()) delete _impl_.account_data_;
}

void DemoAccountStreamEvent::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void DemoAccountStreamEvent::Clear() {
// @@protoc_insertion_point(message_clear_start:mt5_term_api.DemoAccountStreamEvent)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.step_.ClearToEmpty();
  _impl_.message_.ClearToEmpty();
  _impl_.level_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.timestamp_ != nullptr) {
    delete _impl_.timestamp_;
  }
  _impl_.timestamp_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.account_data_ != nullptr) {
    delete _impl_.account_data_;
  }
  _impl_.account_data_ = nullptr;
  ::memset(&_impl_.elapsed_ms_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.is_final_) -
      reinterpret_cast<char*>(&_impl_.elapsed_ms_)) + sizeof(_impl_.is_final_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* DemoAccountStreamEvent::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string step = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_step();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "mt5_term_api.DemoAccountStreamEvent.step"));
        } else
          goto handle_unusual;
        continue;
      // string message = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_message();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "mt5_term_api.DemoAccountStreamEvent.message"));
        } else
          goto handle_unusual;
        continue;
      // string level = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_level();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "mt5_term_api.DemoAccountStreamEvent.level"));
        } else
          goto handle_unusual;
        continue;
      // int64 elapsed_ms = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.elapsed_ms_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .google.protobuf.Timestamp timestamp = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_timestamp(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool is_final = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.is_final_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .mt5_term_api.GuiDemoOpenAccountReply account_data = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          ptr = ctx->ParseMessage(_internal_mutable_account_data(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* DemoAccountStreamEvent::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mt5_term_api.DemoAccountStreamEvent)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string step = 1;
  if (!this->_internal_step().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_step().data(), static_cast<int>(this->_internal_step().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "mt5_term_api.DemoAccountStreamEvent.step");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_step(), target);
  }

  // string message = 2;
  if (!this->_internal_message().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_message().data(), static_cast<int>(this->_internal_message().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "mt5_term_api.DemoAccountStreamEvent.message");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_message(), target);
  }

  // string level = 3;
  if (!this->_internal_level().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_level().data(), static_cast<int>(this->_internal_level().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "mt5_term_api.DemoAccountStreamEvent.level");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_level(), target);
  }

  // int64 elapsed_ms = 4;
  if (this->_internal_elapsed_ms() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(4, this->_internal_elapsed_ms(), target);
  }

  // .google.protobuf.Timestamp timestamp = 5;
  if (this->_internal_has_timestamp()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(5, _Internal::timestamp(this),
        _Internal::timestamp(this).GetCachedSize(), target, stream);
  }

  // bool is_final = 6;
  if (this->_internal_is_final() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(6, this->_internal_is_final(), target);
  }

  // .mt5_term_api.GuiDemoOpenAccountReply account_data = 7;
  if (this->_internal_has_account_data()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(7, _Internal::account_data(this),
        _Internal::account_data(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mt5_term_api.DemoAccountStreamEvent)
  return target;
}

size_t DemoAccountStreamEvent::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mt5_term_api.DemoAccountStreamEvent)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string step = 1;
  if (!this->_internal_step().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_step());
  }

  // string message = 2;
  if (!this->_internal_message().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_message());
  }

  // string level = 3;
  if (!this->_internal_level().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_level());
  }

  // .google.protobuf.Timestamp timestamp = 5;
  if (this->_internal_has_timestamp()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.timestamp_);
  }

  // .mt5_term_api.GuiDemoOpenAccountReply account_data = 7;
  if (this->_internal_has_account_data()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.account_data_);
  }

  // int64 elapsed_ms = 4;
  if (this->_internal_elapsed_ms() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_elapsed_ms());
  }

  // bool is_final = 6;
  if (this->_internal_is_final() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData DemoAccountStreamEvent::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    DemoAccountStreamEvent::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*DemoAccountStreamEvent::GetClassData() const { return &_class_data_; }


void DemoAccountStreamEvent::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<DemoAccountStreamEvent*>(&to_msg);
  auto& from = static_cast<const DemoAccountStreamEvent&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:mt5_term_api.DemoAccountStreamEvent)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_step().empty()) {
    _this->_internal_set_step(from._internal_step());
  }
  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  if (!from._internal_level().empty()) {
    _this->_internal_set_level(from._internal_level());
  }
  if (from._internal_has_timestamp()) {
    _this->_internal_mutable_timestamp()->::PROTOBUF_NAMESPACE_ID::Timestamp::MergeFrom(
        from._internal_timestamp());
  }
  if (from._internal_has_account_data()) {
    _this->_internal_mutable_account_data()->::mt5_term_api::GuiDemoOpenAccountReply::MergeFrom(
        from._internal_account_data());
  }
  if (from._internal_elapsed_ms() != 0) {
    _this->_internal_set_elapsed_ms(from._internal_elapsed_ms());
  }
  if (from._internal_is_final() != 0) {
    _this->_internal_set_is_final(from._internal_is_final());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void DemoAccountStreamEvent::CopyFrom(const DemoAccountStreamEvent& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mt5_term_api.DemoAccountStreamEvent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DemoAccountStreamEvent::IsInitialized() const {
  return true;
}

void DemoAccountStreamEvent::InternalSwap(DemoAccountStreamEvent* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.step_, lhs_arena,
      &other->_impl_.step_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.message_, lhs_arena,
      &other->_impl_.message_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.level_, lhs_arena,
      &other->_impl_.level_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(DemoAccountStreamEvent, _impl_.is_final_)
      + sizeof(DemoAccountStreamEvent::_impl_.is_final_)
      - PROTOBUF_FIELD_OFFSET(DemoAccountStreamEvent, _impl_.timestamp_)>(
          reinterpret_cast<char*>(&_impl_.timestamp_),
          reinterpret_cast<char*>(&other->_impl_.timestamp_));
}

::PROTOBUF_NAMESPACE_ID::Metadata DemoAccountStreamEvent::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_mt5_2dterm_2dapi_2ddemo_2daccount_2eproto_getter, &descriptor_table_mt5_2dterm_2dapi_2ddemo_2daccount_2eproto_once,
      file_level_metadata_mt5_2dterm_2dapi_2ddemo_2daccount_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace mt5_term_api
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::mt5_term_api::DemoAccountStreamEvent*
Arena::CreateMaybeMessage< ::mt5_term_api::DemoAccountStreamEvent >(Arena* arena) {
  return Arena::CreateMessageInternal< ::mt5_term_api::DemoAccountStreamEvent >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
