// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mt5-term-api-account-information.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_mt5_2dterm_2dapi_2daccount_2dinformation_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_mt5_2dterm_2dapi_2daccount_2dinformation_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021006 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "google/api/annotations.pb.h"
#include "mrpc-mt5-error.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_mt5_2dterm_2dapi_2daccount_2dinformation_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_mt5_2dterm_2dapi_2daccount_2dinformation_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_mt5_2dterm_2dapi_2daccount_2dinformation_2eproto;
namespace mt5_term_api {
class AccountInfoDoubleData;
struct AccountInfoDoubleDataDefaultTypeInternal;
extern AccountInfoDoubleDataDefaultTypeInternal _AccountInfoDoubleData_default_instance_;
class AccountInfoDoubleReply;
struct AccountInfoDoubleReplyDefaultTypeInternal;
extern AccountInfoDoubleReplyDefaultTypeInternal _AccountInfoDoubleReply_default_instance_;
class AccountInfoDoubleRequest;
struct AccountInfoDoubleRequestDefaultTypeInternal;
extern AccountInfoDoubleRequestDefaultTypeInternal _AccountInfoDoubleRequest_default_instance_;
class AccountInfoIntegerData;
struct AccountInfoIntegerDataDefaultTypeInternal;
extern AccountInfoIntegerDataDefaultTypeInternal _AccountInfoIntegerData_default_instance_;
class AccountInfoIntegerReply;
struct AccountInfoIntegerReplyDefaultTypeInternal;
extern AccountInfoIntegerReplyDefaultTypeInternal _AccountInfoIntegerReply_default_instance_;
class AccountInfoIntegerRequest;
struct AccountInfoIntegerRequestDefaultTypeInternal;
extern AccountInfoIntegerRequestDefaultTypeInternal _AccountInfoIntegerRequest_default_instance_;
class AccountInfoStringData;
struct AccountInfoStringDataDefaultTypeInternal;
extern AccountInfoStringDataDefaultTypeInternal _AccountInfoStringData_default_instance_;
class AccountInfoStringReply;
struct AccountInfoStringReplyDefaultTypeInternal;
extern AccountInfoStringReplyDefaultTypeInternal _AccountInfoStringReply_default_instance_;
class AccountInfoStringRequest;
struct AccountInfoStringRequestDefaultTypeInternal;
extern AccountInfoStringRequestDefaultTypeInternal _AccountInfoStringRequest_default_instance_;
}  // namespace mt5_term_api
PROTOBUF_NAMESPACE_OPEN
template<> ::mt5_term_api::AccountInfoDoubleData* Arena::CreateMaybeMessage<::mt5_term_api::AccountInfoDoubleData>(Arena*);
template<> ::mt5_term_api::AccountInfoDoubleReply* Arena::CreateMaybeMessage<::mt5_term_api::AccountInfoDoubleReply>(Arena*);
template<> ::mt5_term_api::AccountInfoDoubleRequest* Arena::CreateMaybeMessage<::mt5_term_api::AccountInfoDoubleRequest>(Arena*);
template<> ::mt5_term_api::AccountInfoIntegerData* Arena::CreateMaybeMessage<::mt5_term_api::AccountInfoIntegerData>(Arena*);
template<> ::mt5_term_api::AccountInfoIntegerReply* Arena::CreateMaybeMessage<::mt5_term_api::AccountInfoIntegerReply>(Arena*);
template<> ::mt5_term_api::AccountInfoIntegerRequest* Arena::CreateMaybeMessage<::mt5_term_api::AccountInfoIntegerRequest>(Arena*);
template<> ::mt5_term_api::AccountInfoStringData* Arena::CreateMaybeMessage<::mt5_term_api::AccountInfoStringData>(Arena*);
template<> ::mt5_term_api::AccountInfoStringReply* Arena::CreateMaybeMessage<::mt5_term_api::AccountInfoStringReply>(Arena*);
template<> ::mt5_term_api::AccountInfoStringRequest* Arena::CreateMaybeMessage<::mt5_term_api::AccountInfoStringRequest>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace mt5_term_api {

enum AccountInfoDoublePropertyType : int {
  ACCOUNT_BALANCE = 0,
  ACCOUNT_CREDIT = 1,
  ACCOUNT_PROFIT = 2,
  ACCOUNT_EQUITY = 3,
  ACCOUNT_MARGIN = 4,
  ACCOUNT_MARGIN_FREE = 5,
  ACCOUNT_MARGIN_LEVEL = 6,
  ACCOUNT_MARGIN_SO_CALL = 7,
  ACCOUNT_MARGIN_SO_SO = 8,
  ACCOUNT_MARGIN_INITIAL = 9,
  ACCOUNT_MARGIN_MAINTENANCE = 10,
  ACCOUNT_ASSETS = 11,
  ACCOUNT_LIABILITIES = 12,
  ACCOUNT_COMMISSION_BLOCKED = 13,
  AccountInfoDoublePropertyType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  AccountInfoDoublePropertyType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool AccountInfoDoublePropertyType_IsValid(int value);
constexpr AccountInfoDoublePropertyType AccountInfoDoublePropertyType_MIN = ACCOUNT_BALANCE;
constexpr AccountInfoDoublePropertyType AccountInfoDoublePropertyType_MAX = ACCOUNT_COMMISSION_BLOCKED;
constexpr int AccountInfoDoublePropertyType_ARRAYSIZE = AccountInfoDoublePropertyType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* AccountInfoDoublePropertyType_descriptor();
template<typename T>
inline const std::string& AccountInfoDoublePropertyType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, AccountInfoDoublePropertyType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function AccountInfoDoublePropertyType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    AccountInfoDoublePropertyType_descriptor(), enum_t_value);
}
inline bool AccountInfoDoublePropertyType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, AccountInfoDoublePropertyType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<AccountInfoDoublePropertyType>(
    AccountInfoDoublePropertyType_descriptor(), name, value);
}
enum AccountInfoIntegerPropertyType : int {
  ACCOUNT_LOGIN = 0,
  ACCOUNT_TRADE_MODE = 1,
  ACCOUNT_LEVERAGE = 2,
  ACCOUNT_LIMIT_ORDERS = 3,
  ACCOUNT_MARGIN_SO_MODE = 4,
  ACCOUNT_TRADE_ALLOWED = 5,
  ACCOUNT_TRADE_EXPERT = 6,
  ACCOUNT_MARGIN_MODE = 7,
  ACCOUNT_CURRENCY_DIGITS = 8,
  ACCOUNT_FIFO_CLOSE = 9,
  ACCOUNT_HEDGE_ALLOWED = 10,
  AccountInfoIntegerPropertyType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  AccountInfoIntegerPropertyType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool AccountInfoIntegerPropertyType_IsValid(int value);
constexpr AccountInfoIntegerPropertyType AccountInfoIntegerPropertyType_MIN = ACCOUNT_LOGIN;
constexpr AccountInfoIntegerPropertyType AccountInfoIntegerPropertyType_MAX = ACCOUNT_HEDGE_ALLOWED;
constexpr int AccountInfoIntegerPropertyType_ARRAYSIZE = AccountInfoIntegerPropertyType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* AccountInfoIntegerPropertyType_descriptor();
template<typename T>
inline const std::string& AccountInfoIntegerPropertyType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, AccountInfoIntegerPropertyType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function AccountInfoIntegerPropertyType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    AccountInfoIntegerPropertyType_descriptor(), enum_t_value);
}
inline bool AccountInfoIntegerPropertyType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, AccountInfoIntegerPropertyType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<AccountInfoIntegerPropertyType>(
    AccountInfoIntegerPropertyType_descriptor(), name, value);
}
enum AccountInfoStringPropertyType : int {
  ACCOUNT_NAME = 0,
  ACCOUNT_SERVER = 1,
  ACCOUNT_CURRENCY = 2,
  ACCOUNT_COMPANY = 3,
  AccountInfoStringPropertyType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  AccountInfoStringPropertyType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool AccountInfoStringPropertyType_IsValid(int value);
constexpr AccountInfoStringPropertyType AccountInfoStringPropertyType_MIN = ACCOUNT_NAME;
constexpr AccountInfoStringPropertyType AccountInfoStringPropertyType_MAX = ACCOUNT_COMPANY;
constexpr int AccountInfoStringPropertyType_ARRAYSIZE = AccountInfoStringPropertyType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* AccountInfoStringPropertyType_descriptor();
template<typename T>
inline const std::string& AccountInfoStringPropertyType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, AccountInfoStringPropertyType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function AccountInfoStringPropertyType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    AccountInfoStringPropertyType_descriptor(), enum_t_value);
}
inline bool AccountInfoStringPropertyType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, AccountInfoStringPropertyType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<AccountInfoStringPropertyType>(
    AccountInfoStringPropertyType_descriptor(), name, value);
}
// ===================================================================

class AccountInfoDoubleRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mt5_term_api.AccountInfoDoubleRequest) */ {
 public:
  inline AccountInfoDoubleRequest() : AccountInfoDoubleRequest(nullptr) {}
  ~AccountInfoDoubleRequest() override;
  explicit PROTOBUF_CONSTEXPR AccountInfoDoubleRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AccountInfoDoubleRequest(const AccountInfoDoubleRequest& from);
  AccountInfoDoubleRequest(AccountInfoDoubleRequest&& from) noexcept
    : AccountInfoDoubleRequest() {
    *this = ::std::move(from);
  }

  inline AccountInfoDoubleRequest& operator=(const AccountInfoDoubleRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline AccountInfoDoubleRequest& operator=(AccountInfoDoubleRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AccountInfoDoubleRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const AccountInfoDoubleRequest* internal_default_instance() {
    return reinterpret_cast<const AccountInfoDoubleRequest*>(
               &_AccountInfoDoubleRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(AccountInfoDoubleRequest& a, AccountInfoDoubleRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(AccountInfoDoubleRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AccountInfoDoubleRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AccountInfoDoubleRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AccountInfoDoubleRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AccountInfoDoubleRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AccountInfoDoubleRequest& from) {
    AccountInfoDoubleRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AccountInfoDoubleRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mt5_term_api.AccountInfoDoubleRequest";
  }
  protected:
  explicit AccountInfoDoubleRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPropertyIdFieldNumber = 1,
  };
  // .mt5_term_api.AccountInfoDoublePropertyType property_id = 1;
  void clear_property_id();
  ::mt5_term_api::AccountInfoDoublePropertyType property_id() const;
  void set_property_id(::mt5_term_api::AccountInfoDoublePropertyType value);
  private:
  ::mt5_term_api::AccountInfoDoublePropertyType _internal_property_id() const;
  void _internal_set_property_id(::mt5_term_api::AccountInfoDoublePropertyType value);
  public:

  // @@protoc_insertion_point(class_scope:mt5_term_api.AccountInfoDoubleRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int property_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_mt5_2dterm_2dapi_2daccount_2dinformation_2eproto;
};
// -------------------------------------------------------------------

class AccountInfoDoubleReply final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mt5_term_api.AccountInfoDoubleReply) */ {
 public:
  inline AccountInfoDoubleReply() : AccountInfoDoubleReply(nullptr) {}
  ~AccountInfoDoubleReply() override;
  explicit PROTOBUF_CONSTEXPR AccountInfoDoubleReply(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AccountInfoDoubleReply(const AccountInfoDoubleReply& from);
  AccountInfoDoubleReply(AccountInfoDoubleReply&& from) noexcept
    : AccountInfoDoubleReply() {
    *this = ::std::move(from);
  }

  inline AccountInfoDoubleReply& operator=(const AccountInfoDoubleReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline AccountInfoDoubleReply& operator=(AccountInfoDoubleReply&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AccountInfoDoubleReply& default_instance() {
    return *internal_default_instance();
  }
  enum ResponseCase {
    kData = 1,
    kError = 2,
    RESPONSE_NOT_SET = 0,
  };

  static inline const AccountInfoDoubleReply* internal_default_instance() {
    return reinterpret_cast<const AccountInfoDoubleReply*>(
               &_AccountInfoDoubleReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(AccountInfoDoubleReply& a, AccountInfoDoubleReply& b) {
    a.Swap(&b);
  }
  inline void Swap(AccountInfoDoubleReply* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AccountInfoDoubleReply* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AccountInfoDoubleReply* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AccountInfoDoubleReply>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AccountInfoDoubleReply& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AccountInfoDoubleReply& from) {
    AccountInfoDoubleReply::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AccountInfoDoubleReply* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mt5_term_api.AccountInfoDoubleReply";
  }
  protected:
  explicit AccountInfoDoubleReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 1,
    kErrorFieldNumber = 2,
  };
  // .mt5_term_api.AccountInfoDoubleData data = 1;
  bool has_data() const;
  private:
  bool _internal_has_data() const;
  public:
  void clear_data();
  const ::mt5_term_api::AccountInfoDoubleData& data() const;
  PROTOBUF_NODISCARD ::mt5_term_api::AccountInfoDoubleData* release_data();
  ::mt5_term_api::AccountInfoDoubleData* mutable_data();
  void set_allocated_data(::mt5_term_api::AccountInfoDoubleData* data);
  private:
  const ::mt5_term_api::AccountInfoDoubleData& _internal_data() const;
  ::mt5_term_api::AccountInfoDoubleData* _internal_mutable_data();
  public:
  void unsafe_arena_set_allocated_data(
      ::mt5_term_api::AccountInfoDoubleData* data);
  ::mt5_term_api::AccountInfoDoubleData* unsafe_arena_release_data();

  // .mt5_term_api.Error error = 2;
  bool has_error() const;
  private:
  bool _internal_has_error() const;
  public:
  void clear_error();
  const ::mt5_term_api::Error& error() const;
  PROTOBUF_NODISCARD ::mt5_term_api::Error* release_error();
  ::mt5_term_api::Error* mutable_error();
  void set_allocated_error(::mt5_term_api::Error* error);
  private:
  const ::mt5_term_api::Error& _internal_error() const;
  ::mt5_term_api::Error* _internal_mutable_error();
  public:
  void unsafe_arena_set_allocated_error(
      ::mt5_term_api::Error* error);
  ::mt5_term_api::Error* unsafe_arena_release_error();

  void clear_response();
  ResponseCase response_case() const;
  // @@protoc_insertion_point(class_scope:mt5_term_api.AccountInfoDoubleReply)
 private:
  class _Internal;
  void set_has_data();
  void set_has_error();

  inline bool has_response() const;
  inline void clear_has_response();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    union ResponseUnion {
      constexpr ResponseUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::mt5_term_api::AccountInfoDoubleData* data_;
      ::mt5_term_api::Error* error_;
    } response_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_mt5_2dterm_2dapi_2daccount_2dinformation_2eproto;
};
// -------------------------------------------------------------------

class AccountInfoDoubleData final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mt5_term_api.AccountInfoDoubleData) */ {
 public:
  inline AccountInfoDoubleData() : AccountInfoDoubleData(nullptr) {}
  ~AccountInfoDoubleData() override;
  explicit PROTOBUF_CONSTEXPR AccountInfoDoubleData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AccountInfoDoubleData(const AccountInfoDoubleData& from);
  AccountInfoDoubleData(AccountInfoDoubleData&& from) noexcept
    : AccountInfoDoubleData() {
    *this = ::std::move(from);
  }

  inline AccountInfoDoubleData& operator=(const AccountInfoDoubleData& from) {
    CopyFrom(from);
    return *this;
  }
  inline AccountInfoDoubleData& operator=(AccountInfoDoubleData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AccountInfoDoubleData& default_instance() {
    return *internal_default_instance();
  }
  static inline const AccountInfoDoubleData* internal_default_instance() {
    return reinterpret_cast<const AccountInfoDoubleData*>(
               &_AccountInfoDoubleData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(AccountInfoDoubleData& a, AccountInfoDoubleData& b) {
    a.Swap(&b);
  }
  inline void Swap(AccountInfoDoubleData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AccountInfoDoubleData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AccountInfoDoubleData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AccountInfoDoubleData>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AccountInfoDoubleData& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AccountInfoDoubleData& from) {
    AccountInfoDoubleData::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AccountInfoDoubleData* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mt5_term_api.AccountInfoDoubleData";
  }
  protected:
  explicit AccountInfoDoubleData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRequestedValueFieldNumber = 1,
  };
  // double requested_value = 1;
  void clear_requested_value();
  double requested_value() const;
  void set_requested_value(double value);
  private:
  double _internal_requested_value() const;
  void _internal_set_requested_value(double value);
  public:

  // @@protoc_insertion_point(class_scope:mt5_term_api.AccountInfoDoubleData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    double requested_value_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_mt5_2dterm_2dapi_2daccount_2dinformation_2eproto;
};
// -------------------------------------------------------------------

class AccountInfoIntegerRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mt5_term_api.AccountInfoIntegerRequest) */ {
 public:
  inline AccountInfoIntegerRequest() : AccountInfoIntegerRequest(nullptr) {}
  ~AccountInfoIntegerRequest() override;
  explicit PROTOBUF_CONSTEXPR AccountInfoIntegerRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AccountInfoIntegerRequest(const AccountInfoIntegerRequest& from);
  AccountInfoIntegerRequest(AccountInfoIntegerRequest&& from) noexcept
    : AccountInfoIntegerRequest() {
    *this = ::std::move(from);
  }

  inline AccountInfoIntegerRequest& operator=(const AccountInfoIntegerRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline AccountInfoIntegerRequest& operator=(AccountInfoIntegerRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AccountInfoIntegerRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const AccountInfoIntegerRequest* internal_default_instance() {
    return reinterpret_cast<const AccountInfoIntegerRequest*>(
               &_AccountInfoIntegerRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(AccountInfoIntegerRequest& a, AccountInfoIntegerRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(AccountInfoIntegerRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AccountInfoIntegerRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AccountInfoIntegerRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AccountInfoIntegerRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AccountInfoIntegerRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AccountInfoIntegerRequest& from) {
    AccountInfoIntegerRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AccountInfoIntegerRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mt5_term_api.AccountInfoIntegerRequest";
  }
  protected:
  explicit AccountInfoIntegerRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPropertyIdFieldNumber = 1,
  };
  // .mt5_term_api.AccountInfoIntegerPropertyType property_id = 1;
  void clear_property_id();
  ::mt5_term_api::AccountInfoIntegerPropertyType property_id() const;
  void set_property_id(::mt5_term_api::AccountInfoIntegerPropertyType value);
  private:
  ::mt5_term_api::AccountInfoIntegerPropertyType _internal_property_id() const;
  void _internal_set_property_id(::mt5_term_api::AccountInfoIntegerPropertyType value);
  public:

  // @@protoc_insertion_point(class_scope:mt5_term_api.AccountInfoIntegerRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int property_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_mt5_2dterm_2dapi_2daccount_2dinformation_2eproto;
};
// -------------------------------------------------------------------

class AccountInfoIntegerReply final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mt5_term_api.AccountInfoIntegerReply) */ {
 public:
  inline AccountInfoIntegerReply() : AccountInfoIntegerReply(nullptr) {}
  ~AccountInfoIntegerReply() override;
  explicit PROTOBUF_CONSTEXPR AccountInfoIntegerReply(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AccountInfoIntegerReply(const AccountInfoIntegerReply& from);
  AccountInfoIntegerReply(AccountInfoIntegerReply&& from) noexcept
    : AccountInfoIntegerReply() {
    *this = ::std::move(from);
  }

  inline AccountInfoIntegerReply& operator=(const AccountInfoIntegerReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline AccountInfoIntegerReply& operator=(AccountInfoIntegerReply&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AccountInfoIntegerReply& default_instance() {
    return *internal_default_instance();
  }
  enum ResponseCase {
    kData = 1,
    kError = 2,
    RESPONSE_NOT_SET = 0,
  };

  static inline const AccountInfoIntegerReply* internal_default_instance() {
    return reinterpret_cast<const AccountInfoIntegerReply*>(
               &_AccountInfoIntegerReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(AccountInfoIntegerReply& a, AccountInfoIntegerReply& b) {
    a.Swap(&b);
  }
  inline void Swap(AccountInfoIntegerReply* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AccountInfoIntegerReply* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AccountInfoIntegerReply* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AccountInfoIntegerReply>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AccountInfoIntegerReply& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AccountInfoIntegerReply& from) {
    AccountInfoIntegerReply::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AccountInfoIntegerReply* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mt5_term_api.AccountInfoIntegerReply";
  }
  protected:
  explicit AccountInfoIntegerReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 1,
    kErrorFieldNumber = 2,
  };
  // .mt5_term_api.AccountInfoIntegerData data = 1;
  bool has_data() const;
  private:
  bool _internal_has_data() const;
  public:
  void clear_data();
  const ::mt5_term_api::AccountInfoIntegerData& data() const;
  PROTOBUF_NODISCARD ::mt5_term_api::AccountInfoIntegerData* release_data();
  ::mt5_term_api::AccountInfoIntegerData* mutable_data();
  void set_allocated_data(::mt5_term_api::AccountInfoIntegerData* data);
  private:
  const ::mt5_term_api::AccountInfoIntegerData& _internal_data() const;
  ::mt5_term_api::AccountInfoIntegerData* _internal_mutable_data();
  public:
  void unsafe_arena_set_allocated_data(
      ::mt5_term_api::AccountInfoIntegerData* data);
  ::mt5_term_api::AccountInfoIntegerData* unsafe_arena_release_data();

  // .mt5_term_api.Error error = 2;
  bool has_error() const;
  private:
  bool _internal_has_error() const;
  public:
  void clear_error();
  const ::mt5_term_api::Error& error() const;
  PROTOBUF_NODISCARD ::mt5_term_api::Error* release_error();
  ::mt5_term_api::Error* mutable_error();
  void set_allocated_error(::mt5_term_api::Error* error);
  private:
  const ::mt5_term_api::Error& _internal_error() const;
  ::mt5_term_api::Error* _internal_mutable_error();
  public:
  void unsafe_arena_set_allocated_error(
      ::mt5_term_api::Error* error);
  ::mt5_term_api::Error* unsafe_arena_release_error();

  void clear_response();
  ResponseCase response_case() const;
  // @@protoc_insertion_point(class_scope:mt5_term_api.AccountInfoIntegerReply)
 private:
  class _Internal;
  void set_has_data();
  void set_has_error();

  inline bool has_response() const;
  inline void clear_has_response();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    union ResponseUnion {
      constexpr ResponseUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::mt5_term_api::AccountInfoIntegerData* data_;
      ::mt5_term_api::Error* error_;
    } response_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_mt5_2dterm_2dapi_2daccount_2dinformation_2eproto;
};
// -------------------------------------------------------------------

class AccountInfoIntegerData final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mt5_term_api.AccountInfoIntegerData) */ {
 public:
  inline AccountInfoIntegerData() : AccountInfoIntegerData(nullptr) {}
  ~AccountInfoIntegerData() override;
  explicit PROTOBUF_CONSTEXPR AccountInfoIntegerData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AccountInfoIntegerData(const AccountInfoIntegerData& from);
  AccountInfoIntegerData(AccountInfoIntegerData&& from) noexcept
    : AccountInfoIntegerData() {
    *this = ::std::move(from);
  }

  inline AccountInfoIntegerData& operator=(const AccountInfoIntegerData& from) {
    CopyFrom(from);
    return *this;
  }
  inline AccountInfoIntegerData& operator=(AccountInfoIntegerData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AccountInfoIntegerData& default_instance() {
    return *internal_default_instance();
  }
  static inline const AccountInfoIntegerData* internal_default_instance() {
    return reinterpret_cast<const AccountInfoIntegerData*>(
               &_AccountInfoIntegerData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(AccountInfoIntegerData& a, AccountInfoIntegerData& b) {
    a.Swap(&b);
  }
  inline void Swap(AccountInfoIntegerData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AccountInfoIntegerData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AccountInfoIntegerData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AccountInfoIntegerData>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AccountInfoIntegerData& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AccountInfoIntegerData& from) {
    AccountInfoIntegerData::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AccountInfoIntegerData* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mt5_term_api.AccountInfoIntegerData";
  }
  protected:
  explicit AccountInfoIntegerData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRequestedValueFieldNumber = 1,
  };
  // int64 requested_value = 1;
  void clear_requested_value();
  int64_t requested_value() const;
  void set_requested_value(int64_t value);
  private:
  int64_t _internal_requested_value() const;
  void _internal_set_requested_value(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:mt5_term_api.AccountInfoIntegerData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int64_t requested_value_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_mt5_2dterm_2dapi_2daccount_2dinformation_2eproto;
};
// -------------------------------------------------------------------

class AccountInfoStringRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mt5_term_api.AccountInfoStringRequest) */ {
 public:
  inline AccountInfoStringRequest() : AccountInfoStringRequest(nullptr) {}
  ~AccountInfoStringRequest() override;
  explicit PROTOBUF_CONSTEXPR AccountInfoStringRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AccountInfoStringRequest(const AccountInfoStringRequest& from);
  AccountInfoStringRequest(AccountInfoStringRequest&& from) noexcept
    : AccountInfoStringRequest() {
    *this = ::std::move(from);
  }

  inline AccountInfoStringRequest& operator=(const AccountInfoStringRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline AccountInfoStringRequest& operator=(AccountInfoStringRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AccountInfoStringRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const AccountInfoStringRequest* internal_default_instance() {
    return reinterpret_cast<const AccountInfoStringRequest*>(
               &_AccountInfoStringRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(AccountInfoStringRequest& a, AccountInfoStringRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(AccountInfoStringRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AccountInfoStringRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AccountInfoStringRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AccountInfoStringRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AccountInfoStringRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AccountInfoStringRequest& from) {
    AccountInfoStringRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AccountInfoStringRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mt5_term_api.AccountInfoStringRequest";
  }
  protected:
  explicit AccountInfoStringRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPropertyIdFieldNumber = 1,
  };
  // .mt5_term_api.AccountInfoStringPropertyType property_id = 1;
  void clear_property_id();
  ::mt5_term_api::AccountInfoStringPropertyType property_id() const;
  void set_property_id(::mt5_term_api::AccountInfoStringPropertyType value);
  private:
  ::mt5_term_api::AccountInfoStringPropertyType _internal_property_id() const;
  void _internal_set_property_id(::mt5_term_api::AccountInfoStringPropertyType value);
  public:

  // @@protoc_insertion_point(class_scope:mt5_term_api.AccountInfoStringRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int property_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_mt5_2dterm_2dapi_2daccount_2dinformation_2eproto;
};
// -------------------------------------------------------------------

class AccountInfoStringReply final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mt5_term_api.AccountInfoStringReply) */ {
 public:
  inline AccountInfoStringReply() : AccountInfoStringReply(nullptr) {}
  ~AccountInfoStringReply() override;
  explicit PROTOBUF_CONSTEXPR AccountInfoStringReply(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AccountInfoStringReply(const AccountInfoStringReply& from);
  AccountInfoStringReply(AccountInfoStringReply&& from) noexcept
    : AccountInfoStringReply() {
    *this = ::std::move(from);
  }

  inline AccountInfoStringReply& operator=(const AccountInfoStringReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline AccountInfoStringReply& operator=(AccountInfoStringReply&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AccountInfoStringReply& default_instance() {
    return *internal_default_instance();
  }
  enum ResponseCase {
    kData = 1,
    kError = 2,
    RESPONSE_NOT_SET = 0,
  };

  static inline const AccountInfoStringReply* internal_default_instance() {
    return reinterpret_cast<const AccountInfoStringReply*>(
               &_AccountInfoStringReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(AccountInfoStringReply& a, AccountInfoStringReply& b) {
    a.Swap(&b);
  }
  inline void Swap(AccountInfoStringReply* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AccountInfoStringReply* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AccountInfoStringReply* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AccountInfoStringReply>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AccountInfoStringReply& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AccountInfoStringReply& from) {
    AccountInfoStringReply::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AccountInfoStringReply* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mt5_term_api.AccountInfoStringReply";
  }
  protected:
  explicit AccountInfoStringReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 1,
    kErrorFieldNumber = 2,
  };
  // .mt5_term_api.AccountInfoStringData data = 1;
  bool has_data() const;
  private:
  bool _internal_has_data() const;
  public:
  void clear_data();
  const ::mt5_term_api::AccountInfoStringData& data() const;
  PROTOBUF_NODISCARD ::mt5_term_api::AccountInfoStringData* release_data();
  ::mt5_term_api::AccountInfoStringData* mutable_data();
  void set_allocated_data(::mt5_term_api::AccountInfoStringData* data);
  private:
  const ::mt5_term_api::AccountInfoStringData& _internal_data() const;
  ::mt5_term_api::AccountInfoStringData* _internal_mutable_data();
  public:
  void unsafe_arena_set_allocated_data(
      ::mt5_term_api::AccountInfoStringData* data);
  ::mt5_term_api::AccountInfoStringData* unsafe_arena_release_data();

  // .mt5_term_api.Error error = 2;
  bool has_error() const;
  private:
  bool _internal_has_error() const;
  public:
  void clear_error();
  const ::mt5_term_api::Error& error() const;
  PROTOBUF_NODISCARD ::mt5_term_api::Error* release_error();
  ::mt5_term_api::Error* mutable_error();
  void set_allocated_error(::mt5_term_api::Error* error);
  private:
  const ::mt5_term_api::Error& _internal_error() const;
  ::mt5_term_api::Error* _internal_mutable_error();
  public:
  void unsafe_arena_set_allocated_error(
      ::mt5_term_api::Error* error);
  ::mt5_term_api::Error* unsafe_arena_release_error();

  void clear_response();
  ResponseCase response_case() const;
  // @@protoc_insertion_point(class_scope:mt5_term_api.AccountInfoStringReply)
 private:
  class _Internal;
  void set_has_data();
  void set_has_error();

  inline bool has_response() const;
  inline void clear_has_response();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    union ResponseUnion {
      constexpr ResponseUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::mt5_term_api::AccountInfoStringData* data_;
      ::mt5_term_api::Error* error_;
    } response_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_mt5_2dterm_2dapi_2daccount_2dinformation_2eproto;
};
// -------------------------------------------------------------------

class AccountInfoStringData final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mt5_term_api.AccountInfoStringData) */ {
 public:
  inline AccountInfoStringData() : AccountInfoStringData(nullptr) {}
  ~AccountInfoStringData() override;
  explicit PROTOBUF_CONSTEXPR AccountInfoStringData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AccountInfoStringData(const AccountInfoStringData& from);
  AccountInfoStringData(AccountInfoStringData&& from) noexcept
    : AccountInfoStringData() {
    *this = ::std::move(from);
  }

  inline AccountInfoStringData& operator=(const AccountInfoStringData& from) {
    CopyFrom(from);
    return *this;
  }
  inline AccountInfoStringData& operator=(AccountInfoStringData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AccountInfoStringData& default_instance() {
    return *internal_default_instance();
  }
  static inline const AccountInfoStringData* internal_default_instance() {
    return reinterpret_cast<const AccountInfoStringData*>(
               &_AccountInfoStringData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    8;

  friend void swap(AccountInfoStringData& a, AccountInfoStringData& b) {
    a.Swap(&b);
  }
  inline void Swap(AccountInfoStringData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AccountInfoStringData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AccountInfoStringData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AccountInfoStringData>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AccountInfoStringData& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AccountInfoStringData& from) {
    AccountInfoStringData::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AccountInfoStringData* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mt5_term_api.AccountInfoStringData";
  }
  protected:
  explicit AccountInfoStringData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRequestedValueFieldNumber = 1,
  };
  // string requested_value = 1;
  void clear_requested_value();
  const std::string& requested_value() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_requested_value(ArgT0&& arg0, ArgT... args);
  std::string* mutable_requested_value();
  PROTOBUF_NODISCARD std::string* release_requested_value();
  void set_allocated_requested_value(std::string* requested_value);
  private:
  const std::string& _internal_requested_value() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_requested_value(const std::string& value);
  std::string* _internal_mutable_requested_value();
  public:

  // @@protoc_insertion_point(class_scope:mt5_term_api.AccountInfoStringData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr requested_value_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_mt5_2dterm_2dapi_2daccount_2dinformation_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// AccountInfoDoubleRequest

// .mt5_term_api.AccountInfoDoublePropertyType property_id = 1;
inline void AccountInfoDoubleRequest::clear_property_id() {
  _impl_.property_id_ = 0;
}
inline ::mt5_term_api::AccountInfoDoublePropertyType AccountInfoDoubleRequest::_internal_property_id() const {
  return static_cast< ::mt5_term_api::AccountInfoDoublePropertyType >(_impl_.property_id_);
}
inline ::mt5_term_api::AccountInfoDoublePropertyType AccountInfoDoubleRequest::property_id() const {
  // @@protoc_insertion_point(field_get:mt5_term_api.AccountInfoDoubleRequest.property_id)
  return _internal_property_id();
}
inline void AccountInfoDoubleRequest::_internal_set_property_id(::mt5_term_api::AccountInfoDoublePropertyType value) {
  
  _impl_.property_id_ = value;
}
inline void AccountInfoDoubleRequest::set_property_id(::mt5_term_api::AccountInfoDoublePropertyType value) {
  _internal_set_property_id(value);
  // @@protoc_insertion_point(field_set:mt5_term_api.AccountInfoDoubleRequest.property_id)
}

// -------------------------------------------------------------------

// AccountInfoDoubleReply

// .mt5_term_api.AccountInfoDoubleData data = 1;
inline bool AccountInfoDoubleReply::_internal_has_data() const {
  return response_case() == kData;
}
inline bool AccountInfoDoubleReply::has_data() const {
  return _internal_has_data();
}
inline void AccountInfoDoubleReply::set_has_data() {
  _impl_._oneof_case_[0] = kData;
}
inline void AccountInfoDoubleReply::clear_data() {
  if (_internal_has_data()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.response_.data_;
    }
    clear_has_response();
  }
}
inline ::mt5_term_api::AccountInfoDoubleData* AccountInfoDoubleReply::release_data() {
  // @@protoc_insertion_point(field_release:mt5_term_api.AccountInfoDoubleReply.data)
  if (_internal_has_data()) {
    clear_has_response();
    ::mt5_term_api::AccountInfoDoubleData* temp = _impl_.response_.data_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.response_.data_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::mt5_term_api::AccountInfoDoubleData& AccountInfoDoubleReply::_internal_data() const {
  return _internal_has_data()
      ? *_impl_.response_.data_
      : reinterpret_cast< ::mt5_term_api::AccountInfoDoubleData&>(::mt5_term_api::_AccountInfoDoubleData_default_instance_);
}
inline const ::mt5_term_api::AccountInfoDoubleData& AccountInfoDoubleReply::data() const {
  // @@protoc_insertion_point(field_get:mt5_term_api.AccountInfoDoubleReply.data)
  return _internal_data();
}
inline ::mt5_term_api::AccountInfoDoubleData* AccountInfoDoubleReply::unsafe_arena_release_data() {
  // @@protoc_insertion_point(field_unsafe_arena_release:mt5_term_api.AccountInfoDoubleReply.data)
  if (_internal_has_data()) {
    clear_has_response();
    ::mt5_term_api::AccountInfoDoubleData* temp = _impl_.response_.data_;
    _impl_.response_.data_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void AccountInfoDoubleReply::unsafe_arena_set_allocated_data(::mt5_term_api::AccountInfoDoubleData* data) {
  clear_response();
  if (data) {
    set_has_data();
    _impl_.response_.data_ = data;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:mt5_term_api.AccountInfoDoubleReply.data)
}
inline ::mt5_term_api::AccountInfoDoubleData* AccountInfoDoubleReply::_internal_mutable_data() {
  if (!_internal_has_data()) {
    clear_response();
    set_has_data();
    _impl_.response_.data_ = CreateMaybeMessage< ::mt5_term_api::AccountInfoDoubleData >(GetArenaForAllocation());
  }
  return _impl_.response_.data_;
}
inline ::mt5_term_api::AccountInfoDoubleData* AccountInfoDoubleReply::mutable_data() {
  ::mt5_term_api::AccountInfoDoubleData* _msg = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:mt5_term_api.AccountInfoDoubleReply.data)
  return _msg;
}

// .mt5_term_api.Error error = 2;
inline bool AccountInfoDoubleReply::_internal_has_error() const {
  return response_case() == kError;
}
inline bool AccountInfoDoubleReply::has_error() const {
  return _internal_has_error();
}
inline void AccountInfoDoubleReply::set_has_error() {
  _impl_._oneof_case_[0] = kError;
}
inline ::mt5_term_api::Error* AccountInfoDoubleReply::release_error() {
  // @@protoc_insertion_point(field_release:mt5_term_api.AccountInfoDoubleReply.error)
  if (_internal_has_error()) {
    clear_has_response();
    ::mt5_term_api::Error* temp = _impl_.response_.error_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.response_.error_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::mt5_term_api::Error& AccountInfoDoubleReply::_internal_error() const {
  return _internal_has_error()
      ? *_impl_.response_.error_
      : reinterpret_cast< ::mt5_term_api::Error&>(::mt5_term_api::_Error_default_instance_);
}
inline const ::mt5_term_api::Error& AccountInfoDoubleReply::error() const {
  // @@protoc_insertion_point(field_get:mt5_term_api.AccountInfoDoubleReply.error)
  return _internal_error();
}
inline ::mt5_term_api::Error* AccountInfoDoubleReply::unsafe_arena_release_error() {
  // @@protoc_insertion_point(field_unsafe_arena_release:mt5_term_api.AccountInfoDoubleReply.error)
  if (_internal_has_error()) {
    clear_has_response();
    ::mt5_term_api::Error* temp = _impl_.response_.error_;
    _impl_.response_.error_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void AccountInfoDoubleReply::unsafe_arena_set_allocated_error(::mt5_term_api::Error* error) {
  clear_response();
  if (error) {
    set_has_error();
    _impl_.response_.error_ = error;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:mt5_term_api.AccountInfoDoubleReply.error)
}
inline ::mt5_term_api::Error* AccountInfoDoubleReply::_internal_mutable_error() {
  if (!_internal_has_error()) {
    clear_response();
    set_has_error();
    _impl_.response_.error_ = CreateMaybeMessage< ::mt5_term_api::Error >(GetArenaForAllocation());
  }
  return _impl_.response_.error_;
}
inline ::mt5_term_api::Error* AccountInfoDoubleReply::mutable_error() {
  ::mt5_term_api::Error* _msg = _internal_mutable_error();
  // @@protoc_insertion_point(field_mutable:mt5_term_api.AccountInfoDoubleReply.error)
  return _msg;
}

inline bool AccountInfoDoubleReply::has_response() const {
  return response_case() != RESPONSE_NOT_SET;
}
inline void AccountInfoDoubleReply::clear_has_response() {
  _impl_._oneof_case_[0] = RESPONSE_NOT_SET;
}
inline AccountInfoDoubleReply::ResponseCase AccountInfoDoubleReply::response_case() const {
  return AccountInfoDoubleReply::ResponseCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// AccountInfoDoubleData

// double requested_value = 1;
inline void AccountInfoDoubleData::clear_requested_value() {
  _impl_.requested_value_ = 0;
}
inline double AccountInfoDoubleData::_internal_requested_value() const {
  return _impl_.requested_value_;
}
inline double AccountInfoDoubleData::requested_value() const {
  // @@protoc_insertion_point(field_get:mt5_term_api.AccountInfoDoubleData.requested_value)
  return _internal_requested_value();
}
inline void AccountInfoDoubleData::_internal_set_requested_value(double value) {
  
  _impl_.requested_value_ = value;
}
inline void AccountInfoDoubleData::set_requested_value(double value) {
  _internal_set_requested_value(value);
  // @@protoc_insertion_point(field_set:mt5_term_api.AccountInfoDoubleData.requested_value)
}

// -------------------------------------------------------------------

// AccountInfoIntegerRequest

// .mt5_term_api.AccountInfoIntegerPropertyType property_id = 1;
inline void AccountInfoIntegerRequest::clear_property_id() {
  _impl_.property_id_ = 0;
}
inline ::mt5_term_api::AccountInfoIntegerPropertyType AccountInfoIntegerRequest::_internal_property_id() const {
  return static_cast< ::mt5_term_api::AccountInfoIntegerPropertyType >(_impl_.property_id_);
}
inline ::mt5_term_api::AccountInfoIntegerPropertyType AccountInfoIntegerRequest::property_id() const {
  // @@protoc_insertion_point(field_get:mt5_term_api.AccountInfoIntegerRequest.property_id)
  return _internal_property_id();
}
inline void AccountInfoIntegerRequest::_internal_set_property_id(::mt5_term_api::AccountInfoIntegerPropertyType value) {
  
  _impl_.property_id_ = value;
}
inline void AccountInfoIntegerRequest::set_property_id(::mt5_term_api::AccountInfoIntegerPropertyType value) {
  _internal_set_property_id(value);
  // @@protoc_insertion_point(field_set:mt5_term_api.AccountInfoIntegerRequest.property_id)
}

// -------------------------------------------------------------------

// AccountInfoIntegerReply

// .mt5_term_api.AccountInfoIntegerData data = 1;
inline bool AccountInfoIntegerReply::_internal_has_data() const {
  return response_case() == kData;
}
inline bool AccountInfoIntegerReply::has_data() const {
  return _internal_has_data();
}
inline void AccountInfoIntegerReply::set_has_data() {
  _impl_._oneof_case_[0] = kData;
}
inline void AccountInfoIntegerReply::clear_data() {
  if (_internal_has_data()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.response_.data_;
    }
    clear_has_response();
  }
}
inline ::mt5_term_api::AccountInfoIntegerData* AccountInfoIntegerReply::release_data() {
  // @@protoc_insertion_point(field_release:mt5_term_api.AccountInfoIntegerReply.data)
  if (_internal_has_data()) {
    clear_has_response();
    ::mt5_term_api::AccountInfoIntegerData* temp = _impl_.response_.data_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.response_.data_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::mt5_term_api::AccountInfoIntegerData& AccountInfoIntegerReply::_internal_data() const {
  return _internal_has_data()
      ? *_impl_.response_.data_
      : reinterpret_cast< ::mt5_term_api::AccountInfoIntegerData&>(::mt5_term_api::_AccountInfoIntegerData_default_instance_);
}
inline const ::mt5_term_api::AccountInfoIntegerData& AccountInfoIntegerReply::data() const {
  // @@protoc_insertion_point(field_get:mt5_term_api.AccountInfoIntegerReply.data)
  return _internal_data();
}
inline ::mt5_term_api::AccountInfoIntegerData* AccountInfoIntegerReply::unsafe_arena_release_data() {
  // @@protoc_insertion_point(field_unsafe_arena_release:mt5_term_api.AccountInfoIntegerReply.data)
  if (_internal_has_data()) {
    clear_has_response();
    ::mt5_term_api::AccountInfoIntegerData* temp = _impl_.response_.data_;
    _impl_.response_.data_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void AccountInfoIntegerReply::unsafe_arena_set_allocated_data(::mt5_term_api::AccountInfoIntegerData* data) {
  clear_response();
  if (data) {
    set_has_data();
    _impl_.response_.data_ = data;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:mt5_term_api.AccountInfoIntegerReply.data)
}
inline ::mt5_term_api::AccountInfoIntegerData* AccountInfoIntegerReply::_internal_mutable_data() {
  if (!_internal_has_data()) {
    clear_response();
    set_has_data();
    _impl_.response_.data_ = CreateMaybeMessage< ::mt5_term_api::AccountInfoIntegerData >(GetArenaForAllocation());
  }
  return _impl_.response_.data_;
}
inline ::mt5_term_api::AccountInfoIntegerData* AccountInfoIntegerReply::mutable_data() {
  ::mt5_term_api::AccountInfoIntegerData* _msg = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:mt5_term_api.AccountInfoIntegerReply.data)
  return _msg;
}

// .mt5_term_api.Error error = 2;
inline bool AccountInfoIntegerReply::_internal_has_error() const {
  return response_case() == kError;
}
inline bool AccountInfoIntegerReply::has_error() const {
  return _internal_has_error();
}
inline void AccountInfoIntegerReply::set_has_error() {
  _impl_._oneof_case_[0] = kError;
}
inline ::mt5_term_api::Error* AccountInfoIntegerReply::release_error() {
  // @@protoc_insertion_point(field_release:mt5_term_api.AccountInfoIntegerReply.error)
  if (_internal_has_error()) {
    clear_has_response();
    ::mt5_term_api::Error* temp = _impl_.response_.error_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.response_.error_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::mt5_term_api::Error& AccountInfoIntegerReply::_internal_error() const {
  return _internal_has_error()
      ? *_impl_.response_.error_
      : reinterpret_cast< ::mt5_term_api::Error&>(::mt5_term_api::_Error_default_instance_);
}
inline const ::mt5_term_api::Error& AccountInfoIntegerReply::error() const {
  // @@protoc_insertion_point(field_get:mt5_term_api.AccountInfoIntegerReply.error)
  return _internal_error();
}
inline ::mt5_term_api::Error* AccountInfoIntegerReply::unsafe_arena_release_error() {
  // @@protoc_insertion_point(field_unsafe_arena_release:mt5_term_api.AccountInfoIntegerReply.error)
  if (_internal_has_error()) {
    clear_has_response();
    ::mt5_term_api::Error* temp = _impl_.response_.error_;
    _impl_.response_.error_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void AccountInfoIntegerReply::unsafe_arena_set_allocated_error(::mt5_term_api::Error* error) {
  clear_response();
  if (error) {
    set_has_error();
    _impl_.response_.error_ = error;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:mt5_term_api.AccountInfoIntegerReply.error)
}
inline ::mt5_term_api::Error* AccountInfoIntegerReply::_internal_mutable_error() {
  if (!_internal_has_error()) {
    clear_response();
    set_has_error();
    _impl_.response_.error_ = CreateMaybeMessage< ::mt5_term_api::Error >(GetArenaForAllocation());
  }
  return _impl_.response_.error_;
}
inline ::mt5_term_api::Error* AccountInfoIntegerReply::mutable_error() {
  ::mt5_term_api::Error* _msg = _internal_mutable_error();
  // @@protoc_insertion_point(field_mutable:mt5_term_api.AccountInfoIntegerReply.error)
  return _msg;
}

inline bool AccountInfoIntegerReply::has_response() const {
  return response_case() != RESPONSE_NOT_SET;
}
inline void AccountInfoIntegerReply::clear_has_response() {
  _impl_._oneof_case_[0] = RESPONSE_NOT_SET;
}
inline AccountInfoIntegerReply::ResponseCase AccountInfoIntegerReply::response_case() const {
  return AccountInfoIntegerReply::ResponseCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// AccountInfoIntegerData

// int64 requested_value = 1;
inline void AccountInfoIntegerData::clear_requested_value() {
  _impl_.requested_value_ = int64_t{0};
}
inline int64_t AccountInfoIntegerData::_internal_requested_value() const {
  return _impl_.requested_value_;
}
inline int64_t AccountInfoIntegerData::requested_value() const {
  // @@protoc_insertion_point(field_get:mt5_term_api.AccountInfoIntegerData.requested_value)
  return _internal_requested_value();
}
inline void AccountInfoIntegerData::_internal_set_requested_value(int64_t value) {
  
  _impl_.requested_value_ = value;
}
inline void AccountInfoIntegerData::set_requested_value(int64_t value) {
  _internal_set_requested_value(value);
  // @@protoc_insertion_point(field_set:mt5_term_api.AccountInfoIntegerData.requested_value)
}

// -------------------------------------------------------------------

// AccountInfoStringRequest

// .mt5_term_api.AccountInfoStringPropertyType property_id = 1;
inline void AccountInfoStringRequest::clear_property_id() {
  _impl_.property_id_ = 0;
}
inline ::mt5_term_api::AccountInfoStringPropertyType AccountInfoStringRequest::_internal_property_id() const {
  return static_cast< ::mt5_term_api::AccountInfoStringPropertyType >(_impl_.property_id_);
}
inline ::mt5_term_api::AccountInfoStringPropertyType AccountInfoStringRequest::property_id() const {
  // @@protoc_insertion_point(field_get:mt5_term_api.AccountInfoStringRequest.property_id)
  return _internal_property_id();
}
inline void AccountInfoStringRequest::_internal_set_property_id(::mt5_term_api::AccountInfoStringPropertyType value) {
  
  _impl_.property_id_ = value;
}
inline void AccountInfoStringRequest::set_property_id(::mt5_term_api::AccountInfoStringPropertyType value) {
  _internal_set_property_id(value);
  // @@protoc_insertion_point(field_set:mt5_term_api.AccountInfoStringRequest.property_id)
}

// -------------------------------------------------------------------

// AccountInfoStringReply

// .mt5_term_api.AccountInfoStringData data = 1;
inline bool AccountInfoStringReply::_internal_has_data() const {
  return response_case() == kData;
}
inline bool AccountInfoStringReply::has_data() const {
  return _internal_has_data();
}
inline void AccountInfoStringReply::set_has_data() {
  _impl_._oneof_case_[0] = kData;
}
inline void AccountInfoStringReply::clear_data() {
  if (_internal_has_data()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.response_.data_;
    }
    clear_has_response();
  }
}
inline ::mt5_term_api::AccountInfoStringData* AccountInfoStringReply::release_data() {
  // @@protoc_insertion_point(field_release:mt5_term_api.AccountInfoStringReply.data)
  if (_internal_has_data()) {
    clear_has_response();
    ::mt5_term_api::AccountInfoStringData* temp = _impl_.response_.data_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.response_.data_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::mt5_term_api::AccountInfoStringData& AccountInfoStringReply::_internal_data() const {
  return _internal_has_data()
      ? *_impl_.response_.data_
      : reinterpret_cast< ::mt5_term_api::AccountInfoStringData&>(::mt5_term_api::_AccountInfoStringData_default_instance_);
}
inline const ::mt5_term_api::AccountInfoStringData& AccountInfoStringReply::data() const {
  // @@protoc_insertion_point(field_get:mt5_term_api.AccountInfoStringReply.data)
  return _internal_data();
}
inline ::mt5_term_api::AccountInfoStringData* AccountInfoStringReply::unsafe_arena_release_data() {
  // @@protoc_insertion_point(field_unsafe_arena_release:mt5_term_api.AccountInfoStringReply.data)
  if (_internal_has_data()) {
    clear_has_response();
    ::mt5_term_api::AccountInfoStringData* temp = _impl_.response_.data_;
    _impl_.response_.data_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void AccountInfoStringReply::unsafe_arena_set_allocated_data(::mt5_term_api::AccountInfoStringData* data) {
  clear_response();
  if (data) {
    set_has_data();
    _impl_.response_.data_ = data;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:mt5_term_api.AccountInfoStringReply.data)
}
inline ::mt5_term_api::AccountInfoStringData* AccountInfoStringReply::_internal_mutable_data() {
  if (!_internal_has_data()) {
    clear_response();
    set_has_data();
    _impl_.response_.data_ = CreateMaybeMessage< ::mt5_term_api::AccountInfoStringData >(GetArenaForAllocation());
  }
  return _impl_.response_.data_;
}
inline ::mt5_term_api::AccountInfoStringData* AccountInfoStringReply::mutable_data() {
  ::mt5_term_api::AccountInfoStringData* _msg = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:mt5_term_api.AccountInfoStringReply.data)
  return _msg;
}

// .mt5_term_api.Error error = 2;
inline bool AccountInfoStringReply::_internal_has_error() const {
  return response_case() == kError;
}
inline bool AccountInfoStringReply::has_error() const {
  return _internal_has_error();
}
inline void AccountInfoStringReply::set_has_error() {
  _impl_._oneof_case_[0] = kError;
}
inline ::mt5_term_api::Error* AccountInfoStringReply::release_error() {
  // @@protoc_insertion_point(field_release:mt5_term_api.AccountInfoStringReply.error)
  if (_internal_has_error()) {
    clear_has_response();
    ::mt5_term_api::Error* temp = _impl_.response_.error_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.response_.error_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::mt5_term_api::Error& AccountInfoStringReply::_internal_error() const {
  return _internal_has_error()
      ? *_impl_.response_.error_
      : reinterpret_cast< ::mt5_term_api::Error&>(::mt5_term_api::_Error_default_instance_);
}
inline const ::mt5_term_api::Error& AccountInfoStringReply::error() const {
  // @@protoc_insertion_point(field_get:mt5_term_api.AccountInfoStringReply.error)
  return _internal_error();
}
inline ::mt5_term_api::Error* AccountInfoStringReply::unsafe_arena_release_error() {
  // @@protoc_insertion_point(field_unsafe_arena_release:mt5_term_api.AccountInfoStringReply.error)
  if (_internal_has_error()) {
    clear_has_response();
    ::mt5_term_api::Error* temp = _impl_.response_.error_;
    _impl_.response_.error_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void AccountInfoStringReply::unsafe_arena_set_allocated_error(::mt5_term_api::Error* error) {
  clear_response();
  if (error) {
    set_has_error();
    _impl_.response_.error_ = error;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:mt5_term_api.AccountInfoStringReply.error)
}
inline ::mt5_term_api::Error* AccountInfoStringReply::_internal_mutable_error() {
  if (!_internal_has_error()) {
    clear_response();
    set_has_error();
    _impl_.response_.error_ = CreateMaybeMessage< ::mt5_term_api::Error >(GetArenaForAllocation());
  }
  return _impl_.response_.error_;
}
inline ::mt5_term_api::Error* AccountInfoStringReply::mutable_error() {
  ::mt5_term_api::Error* _msg = _internal_mutable_error();
  // @@protoc_insertion_point(field_mutable:mt5_term_api.AccountInfoStringReply.error)
  return _msg;
}

inline bool AccountInfoStringReply::has_response() const {
  return response_case() != RESPONSE_NOT_SET;
}
inline void AccountInfoStringReply::clear_has_response() {
  _impl_._oneof_case_[0] = RESPONSE_NOT_SET;
}
inline AccountInfoStringReply::ResponseCase AccountInfoStringReply::response_case() const {
  return AccountInfoStringReply::ResponseCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// AccountInfoStringData

// string requested_value = 1;
inline void AccountInfoStringData::clear_requested_value() {
  _impl_.requested_value_.ClearToEmpty();
}
inline const std::string& AccountInfoStringData::requested_value() const {
  // @@protoc_insertion_point(field_get:mt5_term_api.AccountInfoStringData.requested_value)
  return _internal_requested_value();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AccountInfoStringData::set_requested_value(ArgT0&& arg0, ArgT... args) {
 
 _impl_.requested_value_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:mt5_term_api.AccountInfoStringData.requested_value)
}
inline std::string* AccountInfoStringData::mutable_requested_value() {
  std::string* _s = _internal_mutable_requested_value();
  // @@protoc_insertion_point(field_mutable:mt5_term_api.AccountInfoStringData.requested_value)
  return _s;
}
inline const std::string& AccountInfoStringData::_internal_requested_value() const {
  return _impl_.requested_value_.Get();
}
inline void AccountInfoStringData::_internal_set_requested_value(const std::string& value) {
  
  _impl_.requested_value_.Set(value, GetArenaForAllocation());
}
inline std::string* AccountInfoStringData::_internal_mutable_requested_value() {
  
  return _impl_.requested_value_.Mutable(GetArenaForAllocation());
}
inline std::string* AccountInfoStringData::release_requested_value() {
  // @@protoc_insertion_point(field_release:mt5_term_api.AccountInfoStringData.requested_value)
  return _impl_.requested_value_.Release();
}
inline void AccountInfoStringData::set_allocated_requested_value(std::string* requested_value) {
  if (requested_value != nullptr) {
    
  } else {
    
  }
  _impl_.requested_value_.SetAllocated(requested_value, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.requested_value_.IsDefault()) {
    _impl_.requested_value_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:mt5_term_api.AccountInfoStringData.requested_value)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace mt5_term_api

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::mt5_term_api::AccountInfoDoublePropertyType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::mt5_term_api::AccountInfoDoublePropertyType>() {
  return ::mt5_term_api::AccountInfoDoublePropertyType_descriptor();
}
template <> struct is_proto_enum< ::mt5_term_api::AccountInfoIntegerPropertyType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::mt5_term_api::AccountInfoIntegerPropertyType>() {
  return ::mt5_term_api::AccountInfoIntegerPropertyType_descriptor();
}
template <> struct is_proto_enum< ::mt5_term_api::AccountInfoStringPropertyType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::mt5_term_api::AccountInfoStringPropertyType>() {
  return ::mt5_term_api::AccountInfoStringPropertyType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_mt5_2dterm_2dapi_2daccount_2dinformation_2eproto
