// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: mt5-term-api-gui.proto

#include "mt5-term-api-gui.pb.h"
#include "mt5-term-api-gui.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace mt5_term_api {

static const char* Gui_method_names[] = {
  "/mt5_term_api.Gui/Login",
  "/mt5_term_api.Gui/BrokerSearch",
  "/mt5_term_api.Gui/LoginEx",
  "/mt5_term_api.Gui/CloseDialogs",
  "/mt5_term_api.Gui/DemoOpenAccount",
  "/mt5_term_api.Gui/DemoOpenAccountInteractive",
};

std::unique_ptr< Gui::Stub> Gui::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Gui::Stub> stub(new Gui::Stub(channel, options));
  return stub;
}

Gui::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Login_(Gui_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_BrokerSearch_(Gui_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_LoginEx_(Gui_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CloseDialogs_(Gui_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DemoOpenAccount_(Gui_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DemoOpenAccountInteractive_(Gui_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::Status Gui::Stub::Login(::grpc::ClientContext* context, const ::mt5_term_api::GuiLoginRequest& request, ::mt5_term_api::GuiLoginReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mt5_term_api::GuiLoginRequest, ::mt5_term_api::GuiLoginReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Login_, context, request, response);
}

void Gui::Stub::async::Login(::grpc::ClientContext* context, const ::mt5_term_api::GuiLoginRequest* request, ::mt5_term_api::GuiLoginReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mt5_term_api::GuiLoginRequest, ::mt5_term_api::GuiLoginReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, std::move(f));
}

void Gui::Stub::async::Login(::grpc::ClientContext* context, const ::mt5_term_api::GuiLoginRequest* request, ::mt5_term_api::GuiLoginReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mt5_term_api::GuiLoginReply>* Gui::Stub::PrepareAsyncLoginRaw(::grpc::ClientContext* context, const ::mt5_term_api::GuiLoginRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::mt5_term_api::GuiLoginReply, ::mt5_term_api::GuiLoginRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Login_, context, request);
}

::grpc::ClientAsyncResponseReader< ::mt5_term_api::GuiLoginReply>* Gui::Stub::AsyncLoginRaw(::grpc::ClientContext* context, const ::mt5_term_api::GuiLoginRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncLoginRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Gui::Stub::BrokerSearch(::grpc::ClientContext* context, const ::mt5_term_api::GuiBrokerSearchRequest& request, ::mt5_term_api::GuiBrokerSearchReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mt5_term_api::GuiBrokerSearchRequest, ::mt5_term_api::GuiBrokerSearchReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_BrokerSearch_, context, request, response);
}

void Gui::Stub::async::BrokerSearch(::grpc::ClientContext* context, const ::mt5_term_api::GuiBrokerSearchRequest* request, ::mt5_term_api::GuiBrokerSearchReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mt5_term_api::GuiBrokerSearchRequest, ::mt5_term_api::GuiBrokerSearchReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_BrokerSearch_, context, request, response, std::move(f));
}

void Gui::Stub::async::BrokerSearch(::grpc::ClientContext* context, const ::mt5_term_api::GuiBrokerSearchRequest* request, ::mt5_term_api::GuiBrokerSearchReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_BrokerSearch_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mt5_term_api::GuiBrokerSearchReply>* Gui::Stub::PrepareAsyncBrokerSearchRaw(::grpc::ClientContext* context, const ::mt5_term_api::GuiBrokerSearchRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::mt5_term_api::GuiBrokerSearchReply, ::mt5_term_api::GuiBrokerSearchRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_BrokerSearch_, context, request);
}

::grpc::ClientAsyncResponseReader< ::mt5_term_api::GuiBrokerSearchReply>* Gui::Stub::AsyncBrokerSearchRaw(::grpc::ClientContext* context, const ::mt5_term_api::GuiBrokerSearchRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncBrokerSearchRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Gui::Stub::LoginEx(::grpc::ClientContext* context, const ::mt5_term_api::GuiLoginExRequest& request, ::mt5_term_api::GuiLoginExReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mt5_term_api::GuiLoginExRequest, ::mt5_term_api::GuiLoginExReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_LoginEx_, context, request, response);
}

void Gui::Stub::async::LoginEx(::grpc::ClientContext* context, const ::mt5_term_api::GuiLoginExRequest* request, ::mt5_term_api::GuiLoginExReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mt5_term_api::GuiLoginExRequest, ::mt5_term_api::GuiLoginExReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_LoginEx_, context, request, response, std::move(f));
}

void Gui::Stub::async::LoginEx(::grpc::ClientContext* context, const ::mt5_term_api::GuiLoginExRequest* request, ::mt5_term_api::GuiLoginExReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_LoginEx_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mt5_term_api::GuiLoginExReply>* Gui::Stub::PrepareAsyncLoginExRaw(::grpc::ClientContext* context, const ::mt5_term_api::GuiLoginExRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::mt5_term_api::GuiLoginExReply, ::mt5_term_api::GuiLoginExRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_LoginEx_, context, request);
}

::grpc::ClientAsyncResponseReader< ::mt5_term_api::GuiLoginExReply>* Gui::Stub::AsyncLoginExRaw(::grpc::ClientContext* context, const ::mt5_term_api::GuiLoginExRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncLoginExRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Gui::Stub::CloseDialogs(::grpc::ClientContext* context, const ::mt5_term_api::GuiCloseDialogsRequest& request, ::mt5_term_api::GuiCloseDialogsReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mt5_term_api::GuiCloseDialogsRequest, ::mt5_term_api::GuiCloseDialogsReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CloseDialogs_, context, request, response);
}

void Gui::Stub::async::CloseDialogs(::grpc::ClientContext* context, const ::mt5_term_api::GuiCloseDialogsRequest* request, ::mt5_term_api::GuiCloseDialogsReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mt5_term_api::GuiCloseDialogsRequest, ::mt5_term_api::GuiCloseDialogsReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CloseDialogs_, context, request, response, std::move(f));
}

void Gui::Stub::async::CloseDialogs(::grpc::ClientContext* context, const ::mt5_term_api::GuiCloseDialogsRequest* request, ::mt5_term_api::GuiCloseDialogsReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CloseDialogs_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mt5_term_api::GuiCloseDialogsReply>* Gui::Stub::PrepareAsyncCloseDialogsRaw(::grpc::ClientContext* context, const ::mt5_term_api::GuiCloseDialogsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::mt5_term_api::GuiCloseDialogsReply, ::mt5_term_api::GuiCloseDialogsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CloseDialogs_, context, request);
}

::grpc::ClientAsyncResponseReader< ::mt5_term_api::GuiCloseDialogsReply>* Gui::Stub::AsyncCloseDialogsRaw(::grpc::ClientContext* context, const ::mt5_term_api::GuiCloseDialogsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCloseDialogsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Gui::Stub::DemoOpenAccount(::grpc::ClientContext* context, const ::mt5_term_api::GuiDemoOpenAccountRequest& request, ::mt5_term_api::GuiDemoOpenAccountReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mt5_term_api::GuiDemoOpenAccountRequest, ::mt5_term_api::GuiDemoOpenAccountReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DemoOpenAccount_, context, request, response);
}

void Gui::Stub::async::DemoOpenAccount(::grpc::ClientContext* context, const ::mt5_term_api::GuiDemoOpenAccountRequest* request, ::mt5_term_api::GuiDemoOpenAccountReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mt5_term_api::GuiDemoOpenAccountRequest, ::mt5_term_api::GuiDemoOpenAccountReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DemoOpenAccount_, context, request, response, std::move(f));
}

void Gui::Stub::async::DemoOpenAccount(::grpc::ClientContext* context, const ::mt5_term_api::GuiDemoOpenAccountRequest* request, ::mt5_term_api::GuiDemoOpenAccountReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DemoOpenAccount_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mt5_term_api::GuiDemoOpenAccountReply>* Gui::Stub::PrepareAsyncDemoOpenAccountRaw(::grpc::ClientContext* context, const ::mt5_term_api::GuiDemoOpenAccountRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::mt5_term_api::GuiDemoOpenAccountReply, ::mt5_term_api::GuiDemoOpenAccountRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DemoOpenAccount_, context, request);
}

::grpc::ClientAsyncResponseReader< ::mt5_term_api::GuiDemoOpenAccountReply>* Gui::Stub::AsyncDemoOpenAccountRaw(::grpc::ClientContext* context, const ::mt5_term_api::GuiDemoOpenAccountRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDemoOpenAccountRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReaderWriter< ::mt5_term_api::GuiDemoInteractiveClientMessage, ::mt5_term_api::GuiDemoInteractiveServerMessage>* Gui::Stub::DemoOpenAccountInteractiveRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::mt5_term_api::GuiDemoInteractiveClientMessage, ::mt5_term_api::GuiDemoInteractiveServerMessage>::Create(channel_.get(), rpcmethod_DemoOpenAccountInteractive_, context);
}

void Gui::Stub::async::DemoOpenAccountInteractive(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::mt5_term_api::GuiDemoInteractiveClientMessage,::mt5_term_api::GuiDemoInteractiveServerMessage>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::mt5_term_api::GuiDemoInteractiveClientMessage,::mt5_term_api::GuiDemoInteractiveServerMessage>::Create(stub_->channel_.get(), stub_->rpcmethod_DemoOpenAccountInteractive_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::mt5_term_api::GuiDemoInteractiveClientMessage, ::mt5_term_api::GuiDemoInteractiveServerMessage>* Gui::Stub::AsyncDemoOpenAccountInteractiveRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::mt5_term_api::GuiDemoInteractiveClientMessage, ::mt5_term_api::GuiDemoInteractiveServerMessage>::Create(channel_.get(), cq, rpcmethod_DemoOpenAccountInteractive_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::mt5_term_api::GuiDemoInteractiveClientMessage, ::mt5_term_api::GuiDemoInteractiveServerMessage>* Gui::Stub::PrepareAsyncDemoOpenAccountInteractiveRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::mt5_term_api::GuiDemoInteractiveClientMessage, ::mt5_term_api::GuiDemoInteractiveServerMessage>::Create(channel_.get(), cq, rpcmethod_DemoOpenAccountInteractive_, context, false, nullptr);
}

Gui::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Gui_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Gui::Service, ::mt5_term_api::GuiLoginRequest, ::mt5_term_api::GuiLoginReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Gui::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mt5_term_api::GuiLoginRequest* req,
             ::mt5_term_api::GuiLoginReply* resp) {
               return service->Login(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Gui_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Gui::Service, ::mt5_term_api::GuiBrokerSearchRequest, ::mt5_term_api::GuiBrokerSearchReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Gui::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mt5_term_api::GuiBrokerSearchRequest* req,
             ::mt5_term_api::GuiBrokerSearchReply* resp) {
               return service->BrokerSearch(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Gui_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Gui::Service, ::mt5_term_api::GuiLoginExRequest, ::mt5_term_api::GuiLoginExReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Gui::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mt5_term_api::GuiLoginExRequest* req,
             ::mt5_term_api::GuiLoginExReply* resp) {
               return service->LoginEx(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Gui_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Gui::Service, ::mt5_term_api::GuiCloseDialogsRequest, ::mt5_term_api::GuiCloseDialogsReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Gui::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mt5_term_api::GuiCloseDialogsRequest* req,
             ::mt5_term_api::GuiCloseDialogsReply* resp) {
               return service->CloseDialogs(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Gui_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Gui::Service, ::mt5_term_api::GuiDemoOpenAccountRequest, ::mt5_term_api::GuiDemoOpenAccountReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Gui::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mt5_term_api::GuiDemoOpenAccountRequest* req,
             ::mt5_term_api::GuiDemoOpenAccountReply* resp) {
               return service->DemoOpenAccount(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Gui_method_names[5],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< Gui::Service, ::mt5_term_api::GuiDemoInteractiveClientMessage, ::mt5_term_api::GuiDemoInteractiveServerMessage>(
          [](Gui::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::mt5_term_api::GuiDemoInteractiveServerMessage,
             ::mt5_term_api::GuiDemoInteractiveClientMessage>* stream) {
               return service->DemoOpenAccountInteractive(ctx, stream);
             }, this)));
}

Gui::Service::~Service() {
}

::grpc::Status Gui::Service::Login(::grpc::ServerContext* context, const ::mt5_term_api::GuiLoginRequest* request, ::mt5_term_api::GuiLoginReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Gui::Service::BrokerSearch(::grpc::ServerContext* context, const ::mt5_term_api::GuiBrokerSearchRequest* request, ::mt5_term_api::GuiBrokerSearchReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Gui::Service::LoginEx(::grpc::ServerContext* context, const ::mt5_term_api::GuiLoginExRequest* request, ::mt5_term_api::GuiLoginExReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Gui::Service::CloseDialogs(::grpc::ServerContext* context, const ::mt5_term_api::GuiCloseDialogsRequest* request, ::mt5_term_api::GuiCloseDialogsReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Gui::Service::DemoOpenAccount(::grpc::ServerContext* context, const ::mt5_term_api::GuiDemoOpenAccountRequest* request, ::mt5_term_api::GuiDemoOpenAccountReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Gui::Service::DemoOpenAccountInteractive(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::mt5_term_api::GuiDemoInteractiveServerMessage, ::mt5_term_api::GuiDemoInteractiveClientMessage>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace mt5_term_api

