// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: mt5-term-api-trade-functions.proto

#include "mt5-term-api-trade-functions.pb.h"
#include "mt5-term-api-trade-functions.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace mt5_term_api {

static const char* TradeFunctions_method_names[] = {
  "/mt5_term_api.TradeFunctions/OrderCalcMargin",
  "/mt5_term_api.TradeFunctions/OrderCalcProfit",
  "/mt5_term_api.TradeFunctions/OrderCheck",
  "/mt5_term_api.TradeFunctions/PositionsTotal",
};

std::unique_ptr< TradeFunctions::Stub> TradeFunctions::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< TradeFunctions::Stub> stub(new TradeFunctions::Stub(channel, options));
  return stub;
}

TradeFunctions::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_OrderCalcMargin_(TradeFunctions_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_OrderCalcProfit_(TradeFunctions_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_OrderCheck_(TradeFunctions_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_PositionsTotal_(TradeFunctions_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status TradeFunctions::Stub::OrderCalcMargin(::grpc::ClientContext* context, const ::mt5_term_api::OrderCalcMarginRequest& request, ::mt5_term_api::OrderCalcMarginReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mt5_term_api::OrderCalcMarginRequest, ::mt5_term_api::OrderCalcMarginReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_OrderCalcMargin_, context, request, response);
}

void TradeFunctions::Stub::async::OrderCalcMargin(::grpc::ClientContext* context, const ::mt5_term_api::OrderCalcMarginRequest* request, ::mt5_term_api::OrderCalcMarginReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mt5_term_api::OrderCalcMarginRequest, ::mt5_term_api::OrderCalcMarginReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_OrderCalcMargin_, context, request, response, std::move(f));
}

void TradeFunctions::Stub::async::OrderCalcMargin(::grpc::ClientContext* context, const ::mt5_term_api::OrderCalcMarginRequest* request, ::mt5_term_api::OrderCalcMarginReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_OrderCalcMargin_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mt5_term_api::OrderCalcMarginReply>* TradeFunctions::Stub::PrepareAsyncOrderCalcMarginRaw(::grpc::ClientContext* context, const ::mt5_term_api::OrderCalcMarginRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::mt5_term_api::OrderCalcMarginReply, ::mt5_term_api::OrderCalcMarginRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_OrderCalcMargin_, context, request);
}

::grpc::ClientAsyncResponseReader< ::mt5_term_api::OrderCalcMarginReply>* TradeFunctions::Stub::AsyncOrderCalcMarginRaw(::grpc::ClientContext* context, const ::mt5_term_api::OrderCalcMarginRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncOrderCalcMarginRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TradeFunctions::Stub::OrderCalcProfit(::grpc::ClientContext* context, const ::mt5_term_api::OrderCalcProfitRequest& request, ::mt5_term_api::OrderCalcProfitReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mt5_term_api::OrderCalcProfitRequest, ::mt5_term_api::OrderCalcProfitReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_OrderCalcProfit_, context, request, response);
}

void TradeFunctions::Stub::async::OrderCalcProfit(::grpc::ClientContext* context, const ::mt5_term_api::OrderCalcProfitRequest* request, ::mt5_term_api::OrderCalcProfitReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mt5_term_api::OrderCalcProfitRequest, ::mt5_term_api::OrderCalcProfitReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_OrderCalcProfit_, context, request, response, std::move(f));
}

void TradeFunctions::Stub::async::OrderCalcProfit(::grpc::ClientContext* context, const ::mt5_term_api::OrderCalcProfitRequest* request, ::mt5_term_api::OrderCalcProfitReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_OrderCalcProfit_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mt5_term_api::OrderCalcProfitReply>* TradeFunctions::Stub::PrepareAsyncOrderCalcProfitRaw(::grpc::ClientContext* context, const ::mt5_term_api::OrderCalcProfitRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::mt5_term_api::OrderCalcProfitReply, ::mt5_term_api::OrderCalcProfitRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_OrderCalcProfit_, context, request);
}

::grpc::ClientAsyncResponseReader< ::mt5_term_api::OrderCalcProfitReply>* TradeFunctions::Stub::AsyncOrderCalcProfitRaw(::grpc::ClientContext* context, const ::mt5_term_api::OrderCalcProfitRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncOrderCalcProfitRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TradeFunctions::Stub::OrderCheck(::grpc::ClientContext* context, const ::mt5_term_api::OrderCheckRequest& request, ::mt5_term_api::OrderCheckReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mt5_term_api::OrderCheckRequest, ::mt5_term_api::OrderCheckReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_OrderCheck_, context, request, response);
}

void TradeFunctions::Stub::async::OrderCheck(::grpc::ClientContext* context, const ::mt5_term_api::OrderCheckRequest* request, ::mt5_term_api::OrderCheckReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mt5_term_api::OrderCheckRequest, ::mt5_term_api::OrderCheckReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_OrderCheck_, context, request, response, std::move(f));
}

void TradeFunctions::Stub::async::OrderCheck(::grpc::ClientContext* context, const ::mt5_term_api::OrderCheckRequest* request, ::mt5_term_api::OrderCheckReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_OrderCheck_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mt5_term_api::OrderCheckReply>* TradeFunctions::Stub::PrepareAsyncOrderCheckRaw(::grpc::ClientContext* context, const ::mt5_term_api::OrderCheckRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::mt5_term_api::OrderCheckReply, ::mt5_term_api::OrderCheckRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_OrderCheck_, context, request);
}

::grpc::ClientAsyncResponseReader< ::mt5_term_api::OrderCheckReply>* TradeFunctions::Stub::AsyncOrderCheckRaw(::grpc::ClientContext* context, const ::mt5_term_api::OrderCheckRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncOrderCheckRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TradeFunctions::Stub::PositionsTotal(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::mt5_term_api::PositionsTotalReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::google::protobuf::Empty, ::mt5_term_api::PositionsTotalReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_PositionsTotal_, context, request, response);
}

void TradeFunctions::Stub::async::PositionsTotal(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::mt5_term_api::PositionsTotalReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::google::protobuf::Empty, ::mt5_term_api::PositionsTotalReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PositionsTotal_, context, request, response, std::move(f));
}

void TradeFunctions::Stub::async::PositionsTotal(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::mt5_term_api::PositionsTotalReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PositionsTotal_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mt5_term_api::PositionsTotalReply>* TradeFunctions::Stub::PrepareAsyncPositionsTotalRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::mt5_term_api::PositionsTotalReply, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_PositionsTotal_, context, request);
}

::grpc::ClientAsyncResponseReader< ::mt5_term_api::PositionsTotalReply>* TradeFunctions::Stub::AsyncPositionsTotalRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPositionsTotalRaw(context, request, cq);
  result->StartCall();
  return result;
}

TradeFunctions::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TradeFunctions_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TradeFunctions::Service, ::mt5_term_api::OrderCalcMarginRequest, ::mt5_term_api::OrderCalcMarginReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TradeFunctions::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mt5_term_api::OrderCalcMarginRequest* req,
             ::mt5_term_api::OrderCalcMarginReply* resp) {
               return service->OrderCalcMargin(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TradeFunctions_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TradeFunctions::Service, ::mt5_term_api::OrderCalcProfitRequest, ::mt5_term_api::OrderCalcProfitReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TradeFunctions::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mt5_term_api::OrderCalcProfitRequest* req,
             ::mt5_term_api::OrderCalcProfitReply* resp) {
               return service->OrderCalcProfit(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TradeFunctions_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TradeFunctions::Service, ::mt5_term_api::OrderCheckRequest, ::mt5_term_api::OrderCheckReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TradeFunctions::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mt5_term_api::OrderCheckRequest* req,
             ::mt5_term_api::OrderCheckReply* resp) {
               return service->OrderCheck(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TradeFunctions_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TradeFunctions::Service, ::google::protobuf::Empty, ::mt5_term_api::PositionsTotalReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TradeFunctions::Service* service,
             ::grpc::ServerContext* ctx,
             const ::google::protobuf::Empty* req,
             ::mt5_term_api::PositionsTotalReply* resp) {
               return service->PositionsTotal(ctx, req, resp);
             }, this)));
}

TradeFunctions::Service::~Service() {
}

::grpc::Status TradeFunctions::Service::OrderCalcMargin(::grpc::ServerContext* context, const ::mt5_term_api::OrderCalcMarginRequest* request, ::mt5_term_api::OrderCalcMarginReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TradeFunctions::Service::OrderCalcProfit(::grpc::ServerContext* context, const ::mt5_term_api::OrderCalcProfitRequest* request, ::mt5_term_api::OrderCalcProfitReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TradeFunctions::Service::OrderCheck(::grpc::ServerContext* context, const ::mt5_term_api::OrderCheckRequest* request, ::mt5_term_api::OrderCheckReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TradeFunctions::Service::PositionsTotal(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::mt5_term_api::PositionsTotalReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace mt5_term_api

