// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: mt5-term-api-connection.proto

#include "mt5-term-api-connection.pb.h"
#include "mt5-term-api-connection.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace mt5_term_api {

static const char* Connection_method_names[] = {
  "/mt5_term_api.Connection/ConnectEx",
  "/mt5_term_api.Connection/Connect",
  "/mt5_term_api.Connection/ConnectProxy",
  "/mt5_term_api.Connection/CheckConnect",
  "/mt5_term_api.Connection/ConnectState",
  "/mt5_term_api.Connection/OnConnectState",
  "/mt5_term_api.Connection/ConnectionStatus",
  "/mt5_term_api.Connection/Disconnect",
  "/mt5_term_api.Connection/Reconnect",
  "/mt5_term_api.Connection/ConnectByToken",
  "/mt5_term_api.Connection/GetBrokerServersByBrokerName",
  "/mt5_term_api.Connection/Screenshot",
  "/mt5_term_api.Connection/GetId",
  "/mt5_term_api.Connection/ConnectStream",
  "/mt5_term_api.Connection/ConnectExStream",
};

std::unique_ptr< Connection::Stub> Connection::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Connection::Stub> stub(new Connection::Stub(channel, options));
  return stub;
}

Connection::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ConnectEx_(Connection_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Connect_(Connection_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ConnectProxy_(Connection_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CheckConnect_(Connection_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ConnectState_(Connection_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_OnConnectState_(Connection_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_ConnectionStatus_(Connection_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Disconnect_(Connection_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Reconnect_(Connection_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ConnectByToken_(Connection_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetBrokerServersByBrokerName_(Connection_method_names[10], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Screenshot_(Connection_method_names[11], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetId_(Connection_method_names[12], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ConnectStream_(Connection_method_names[13], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_ConnectExStream_(Connection_method_names[14], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::Status Connection::Stub::ConnectEx(::grpc::ClientContext* context, const ::mt5_term_api::ConnectExRequest& request, ::mt5_term_api::ConnectExReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mt5_term_api::ConnectExRequest, ::mt5_term_api::ConnectExReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ConnectEx_, context, request, response);
}

void Connection::Stub::async::ConnectEx(::grpc::ClientContext* context, const ::mt5_term_api::ConnectExRequest* request, ::mt5_term_api::ConnectExReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mt5_term_api::ConnectExRequest, ::mt5_term_api::ConnectExReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ConnectEx_, context, request, response, std::move(f));
}

void Connection::Stub::async::ConnectEx(::grpc::ClientContext* context, const ::mt5_term_api::ConnectExRequest* request, ::mt5_term_api::ConnectExReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ConnectEx_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mt5_term_api::ConnectExReply>* Connection::Stub::PrepareAsyncConnectExRaw(::grpc::ClientContext* context, const ::mt5_term_api::ConnectExRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::mt5_term_api::ConnectExReply, ::mt5_term_api::ConnectExRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ConnectEx_, context, request);
}

::grpc::ClientAsyncResponseReader< ::mt5_term_api::ConnectExReply>* Connection::Stub::AsyncConnectExRaw(::grpc::ClientContext* context, const ::mt5_term_api::ConnectExRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncConnectExRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Connection::Stub::Connect(::grpc::ClientContext* context, const ::mt5_term_api::ConnectRequest& request, ::mt5_term_api::ConnectReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mt5_term_api::ConnectRequest, ::mt5_term_api::ConnectReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Connect_, context, request, response);
}

void Connection::Stub::async::Connect(::grpc::ClientContext* context, const ::mt5_term_api::ConnectRequest* request, ::mt5_term_api::ConnectReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mt5_term_api::ConnectRequest, ::mt5_term_api::ConnectReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Connect_, context, request, response, std::move(f));
}

void Connection::Stub::async::Connect(::grpc::ClientContext* context, const ::mt5_term_api::ConnectRequest* request, ::mt5_term_api::ConnectReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Connect_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mt5_term_api::ConnectReply>* Connection::Stub::PrepareAsyncConnectRaw(::grpc::ClientContext* context, const ::mt5_term_api::ConnectRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::mt5_term_api::ConnectReply, ::mt5_term_api::ConnectRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Connect_, context, request);
}

::grpc::ClientAsyncResponseReader< ::mt5_term_api::ConnectReply>* Connection::Stub::AsyncConnectRaw(::grpc::ClientContext* context, const ::mt5_term_api::ConnectRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncConnectRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Connection::Stub::ConnectProxy(::grpc::ClientContext* context, const ::mt5_term_api::ConnectProxyRequest& request, ::mt5_term_api::ConnectProxyReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mt5_term_api::ConnectProxyRequest, ::mt5_term_api::ConnectProxyReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ConnectProxy_, context, request, response);
}

void Connection::Stub::async::ConnectProxy(::grpc::ClientContext* context, const ::mt5_term_api::ConnectProxyRequest* request, ::mt5_term_api::ConnectProxyReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mt5_term_api::ConnectProxyRequest, ::mt5_term_api::ConnectProxyReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ConnectProxy_, context, request, response, std::move(f));
}

void Connection::Stub::async::ConnectProxy(::grpc::ClientContext* context, const ::mt5_term_api::ConnectProxyRequest* request, ::mt5_term_api::ConnectProxyReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ConnectProxy_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mt5_term_api::ConnectProxyReply>* Connection::Stub::PrepareAsyncConnectProxyRaw(::grpc::ClientContext* context, const ::mt5_term_api::ConnectProxyRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::mt5_term_api::ConnectProxyReply, ::mt5_term_api::ConnectProxyRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ConnectProxy_, context, request);
}

::grpc::ClientAsyncResponseReader< ::mt5_term_api::ConnectProxyReply>* Connection::Stub::AsyncConnectProxyRaw(::grpc::ClientContext* context, const ::mt5_term_api::ConnectProxyRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncConnectProxyRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Connection::Stub::CheckConnect(::grpc::ClientContext* context, const ::mt5_term_api::CheckConnectRequest& request, ::mt5_term_api::CheckConnectReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mt5_term_api::CheckConnectRequest, ::mt5_term_api::CheckConnectReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CheckConnect_, context, request, response);
}

void Connection::Stub::async::CheckConnect(::grpc::ClientContext* context, const ::mt5_term_api::CheckConnectRequest* request, ::mt5_term_api::CheckConnectReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mt5_term_api::CheckConnectRequest, ::mt5_term_api::CheckConnectReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CheckConnect_, context, request, response, std::move(f));
}

void Connection::Stub::async::CheckConnect(::grpc::ClientContext* context, const ::mt5_term_api::CheckConnectRequest* request, ::mt5_term_api::CheckConnectReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CheckConnect_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mt5_term_api::CheckConnectReply>* Connection::Stub::PrepareAsyncCheckConnectRaw(::grpc::ClientContext* context, const ::mt5_term_api::CheckConnectRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::mt5_term_api::CheckConnectReply, ::mt5_term_api::CheckConnectRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CheckConnect_, context, request);
}

::grpc::ClientAsyncResponseReader< ::mt5_term_api::CheckConnectReply>* Connection::Stub::AsyncCheckConnectRaw(::grpc::ClientContext* context, const ::mt5_term_api::CheckConnectRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCheckConnectRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Connection::Stub::ConnectState(::grpc::ClientContext* context, const ::mt5_term_api::ConnectStateRequest& request, ::mt5_term_api::ConnectStateReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mt5_term_api::ConnectStateRequest, ::mt5_term_api::ConnectStateReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ConnectState_, context, request, response);
}

void Connection::Stub::async::ConnectState(::grpc::ClientContext* context, const ::mt5_term_api::ConnectStateRequest* request, ::mt5_term_api::ConnectStateReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mt5_term_api::ConnectStateRequest, ::mt5_term_api::ConnectStateReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ConnectState_, context, request, response, std::move(f));
}

void Connection::Stub::async::ConnectState(::grpc::ClientContext* context, const ::mt5_term_api::ConnectStateRequest* request, ::mt5_term_api::ConnectStateReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ConnectState_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mt5_term_api::ConnectStateReply>* Connection::Stub::PrepareAsyncConnectStateRaw(::grpc::ClientContext* context, const ::mt5_term_api::ConnectStateRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::mt5_term_api::ConnectStateReply, ::mt5_term_api::ConnectStateRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ConnectState_, context, request);
}

::grpc::ClientAsyncResponseReader< ::mt5_term_api::ConnectStateReply>* Connection::Stub::AsyncConnectStateRaw(::grpc::ClientContext* context, const ::mt5_term_api::ConnectStateRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncConnectStateRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::mt5_term_api::OnConnectStateReply>* Connection::Stub::OnConnectStateRaw(::grpc::ClientContext* context, const ::mt5_term_api::OnConnectStateRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::mt5_term_api::OnConnectStateReply>::Create(channel_.get(), rpcmethod_OnConnectState_, context, request);
}

void Connection::Stub::async::OnConnectState(::grpc::ClientContext* context, const ::mt5_term_api::OnConnectStateRequest* request, ::grpc::ClientReadReactor< ::mt5_term_api::OnConnectStateReply>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::mt5_term_api::OnConnectStateReply>::Create(stub_->channel_.get(), stub_->rpcmethod_OnConnectState_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::mt5_term_api::OnConnectStateReply>* Connection::Stub::AsyncOnConnectStateRaw(::grpc::ClientContext* context, const ::mt5_term_api::OnConnectStateRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::mt5_term_api::OnConnectStateReply>::Create(channel_.get(), cq, rpcmethod_OnConnectState_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::mt5_term_api::OnConnectStateReply>* Connection::Stub::PrepareAsyncOnConnectStateRaw(::grpc::ClientContext* context, const ::mt5_term_api::OnConnectStateRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::mt5_term_api::OnConnectStateReply>::Create(channel_.get(), cq, rpcmethod_OnConnectState_, context, request, false, nullptr);
}

::grpc::Status Connection::Stub::ConnectionStatus(::grpc::ClientContext* context, const ::mt5_term_api::ConnectionStatusRequest& request, ::mt5_term_api::ConnectionStatusReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mt5_term_api::ConnectionStatusRequest, ::mt5_term_api::ConnectionStatusReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ConnectionStatus_, context, request, response);
}

void Connection::Stub::async::ConnectionStatus(::grpc::ClientContext* context, const ::mt5_term_api::ConnectionStatusRequest* request, ::mt5_term_api::ConnectionStatusReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mt5_term_api::ConnectionStatusRequest, ::mt5_term_api::ConnectionStatusReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ConnectionStatus_, context, request, response, std::move(f));
}

void Connection::Stub::async::ConnectionStatus(::grpc::ClientContext* context, const ::mt5_term_api::ConnectionStatusRequest* request, ::mt5_term_api::ConnectionStatusReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ConnectionStatus_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mt5_term_api::ConnectionStatusReply>* Connection::Stub::PrepareAsyncConnectionStatusRaw(::grpc::ClientContext* context, const ::mt5_term_api::ConnectionStatusRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::mt5_term_api::ConnectionStatusReply, ::mt5_term_api::ConnectionStatusRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ConnectionStatus_, context, request);
}

::grpc::ClientAsyncResponseReader< ::mt5_term_api::ConnectionStatusReply>* Connection::Stub::AsyncConnectionStatusRaw(::grpc::ClientContext* context, const ::mt5_term_api::ConnectionStatusRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncConnectionStatusRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Connection::Stub::Disconnect(::grpc::ClientContext* context, const ::mt5_term_api::DisconnectRequest& request, ::mt5_term_api::DisconnectReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mt5_term_api::DisconnectRequest, ::mt5_term_api::DisconnectReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Disconnect_, context, request, response);
}

void Connection::Stub::async::Disconnect(::grpc::ClientContext* context, const ::mt5_term_api::DisconnectRequest* request, ::mt5_term_api::DisconnectReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mt5_term_api::DisconnectRequest, ::mt5_term_api::DisconnectReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Disconnect_, context, request, response, std::move(f));
}

void Connection::Stub::async::Disconnect(::grpc::ClientContext* context, const ::mt5_term_api::DisconnectRequest* request, ::mt5_term_api::DisconnectReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Disconnect_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mt5_term_api::DisconnectReply>* Connection::Stub::PrepareAsyncDisconnectRaw(::grpc::ClientContext* context, const ::mt5_term_api::DisconnectRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::mt5_term_api::DisconnectReply, ::mt5_term_api::DisconnectRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Disconnect_, context, request);
}

::grpc::ClientAsyncResponseReader< ::mt5_term_api::DisconnectReply>* Connection::Stub::AsyncDisconnectRaw(::grpc::ClientContext* context, const ::mt5_term_api::DisconnectRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDisconnectRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Connection::Stub::Reconnect(::grpc::ClientContext* context, const ::mt5_term_api::ReconnectRequest& request, ::mt5_term_api::ReconnectReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mt5_term_api::ReconnectRequest, ::mt5_term_api::ReconnectReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Reconnect_, context, request, response);
}

void Connection::Stub::async::Reconnect(::grpc::ClientContext* context, const ::mt5_term_api::ReconnectRequest* request, ::mt5_term_api::ReconnectReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mt5_term_api::ReconnectRequest, ::mt5_term_api::ReconnectReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Reconnect_, context, request, response, std::move(f));
}

void Connection::Stub::async::Reconnect(::grpc::ClientContext* context, const ::mt5_term_api::ReconnectRequest* request, ::mt5_term_api::ReconnectReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Reconnect_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mt5_term_api::ReconnectReply>* Connection::Stub::PrepareAsyncReconnectRaw(::grpc::ClientContext* context, const ::mt5_term_api::ReconnectRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::mt5_term_api::ReconnectReply, ::mt5_term_api::ReconnectRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Reconnect_, context, request);
}

::grpc::ClientAsyncResponseReader< ::mt5_term_api::ReconnectReply>* Connection::Stub::AsyncReconnectRaw(::grpc::ClientContext* context, const ::mt5_term_api::ReconnectRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncReconnectRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Connection::Stub::ConnectByToken(::grpc::ClientContext* context, const ::mt5_term_api::ConnectByTokenRequest& request, ::mt5_term_api::ConnectExReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mt5_term_api::ConnectByTokenRequest, ::mt5_term_api::ConnectExReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ConnectByToken_, context, request, response);
}

void Connection::Stub::async::ConnectByToken(::grpc::ClientContext* context, const ::mt5_term_api::ConnectByTokenRequest* request, ::mt5_term_api::ConnectExReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mt5_term_api::ConnectByTokenRequest, ::mt5_term_api::ConnectExReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ConnectByToken_, context, request, response, std::move(f));
}

void Connection::Stub::async::ConnectByToken(::grpc::ClientContext* context, const ::mt5_term_api::ConnectByTokenRequest* request, ::mt5_term_api::ConnectExReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ConnectByToken_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mt5_term_api::ConnectExReply>* Connection::Stub::PrepareAsyncConnectByTokenRaw(::grpc::ClientContext* context, const ::mt5_term_api::ConnectByTokenRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::mt5_term_api::ConnectExReply, ::mt5_term_api::ConnectByTokenRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ConnectByToken_, context, request);
}

::grpc::ClientAsyncResponseReader< ::mt5_term_api::ConnectExReply>* Connection::Stub::AsyncConnectByTokenRaw(::grpc::ClientContext* context, const ::mt5_term_api::ConnectByTokenRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncConnectByTokenRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Connection::Stub::GetBrokerServersByBrokerName(::grpc::ClientContext* context, const ::mt5_term_api::GetBrokerServersByBrokerNameRequest& request, ::mt5_term_api::GetBrokerServersByBrokerNameReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mt5_term_api::GetBrokerServersByBrokerNameRequest, ::mt5_term_api::GetBrokerServersByBrokerNameReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetBrokerServersByBrokerName_, context, request, response);
}

void Connection::Stub::async::GetBrokerServersByBrokerName(::grpc::ClientContext* context, const ::mt5_term_api::GetBrokerServersByBrokerNameRequest* request, ::mt5_term_api::GetBrokerServersByBrokerNameReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mt5_term_api::GetBrokerServersByBrokerNameRequest, ::mt5_term_api::GetBrokerServersByBrokerNameReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetBrokerServersByBrokerName_, context, request, response, std::move(f));
}

void Connection::Stub::async::GetBrokerServersByBrokerName(::grpc::ClientContext* context, const ::mt5_term_api::GetBrokerServersByBrokerNameRequest* request, ::mt5_term_api::GetBrokerServersByBrokerNameReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetBrokerServersByBrokerName_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mt5_term_api::GetBrokerServersByBrokerNameReply>* Connection::Stub::PrepareAsyncGetBrokerServersByBrokerNameRaw(::grpc::ClientContext* context, const ::mt5_term_api::GetBrokerServersByBrokerNameRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::mt5_term_api::GetBrokerServersByBrokerNameReply, ::mt5_term_api::GetBrokerServersByBrokerNameRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetBrokerServersByBrokerName_, context, request);
}

::grpc::ClientAsyncResponseReader< ::mt5_term_api::GetBrokerServersByBrokerNameReply>* Connection::Stub::AsyncGetBrokerServersByBrokerNameRaw(::grpc::ClientContext* context, const ::mt5_term_api::GetBrokerServersByBrokerNameRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetBrokerServersByBrokerNameRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Connection::Stub::Screenshot(::grpc::ClientContext* context, const ::mt5_term_api::ScreenshotRequest& request, ::mt5_term_api::ScreenshotReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mt5_term_api::ScreenshotRequest, ::mt5_term_api::ScreenshotReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Screenshot_, context, request, response);
}

void Connection::Stub::async::Screenshot(::grpc::ClientContext* context, const ::mt5_term_api::ScreenshotRequest* request, ::mt5_term_api::ScreenshotReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mt5_term_api::ScreenshotRequest, ::mt5_term_api::ScreenshotReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Screenshot_, context, request, response, std::move(f));
}

void Connection::Stub::async::Screenshot(::grpc::ClientContext* context, const ::mt5_term_api::ScreenshotRequest* request, ::mt5_term_api::ScreenshotReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Screenshot_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mt5_term_api::ScreenshotReply>* Connection::Stub::PrepareAsyncScreenshotRaw(::grpc::ClientContext* context, const ::mt5_term_api::ScreenshotRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::mt5_term_api::ScreenshotReply, ::mt5_term_api::ScreenshotRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Screenshot_, context, request);
}

::grpc::ClientAsyncResponseReader< ::mt5_term_api::ScreenshotReply>* Connection::Stub::AsyncScreenshotRaw(::grpc::ClientContext* context, const ::mt5_term_api::ScreenshotRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncScreenshotRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Connection::Stub::GetId(::grpc::ClientContext* context, const ::mt5_term_api::GetIdRequest& request, ::mt5_term_api::GetIdReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mt5_term_api::GetIdRequest, ::mt5_term_api::GetIdReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetId_, context, request, response);
}

void Connection::Stub::async::GetId(::grpc::ClientContext* context, const ::mt5_term_api::GetIdRequest* request, ::mt5_term_api::GetIdReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mt5_term_api::GetIdRequest, ::mt5_term_api::GetIdReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetId_, context, request, response, std::move(f));
}

void Connection::Stub::async::GetId(::grpc::ClientContext* context, const ::mt5_term_api::GetIdRequest* request, ::mt5_term_api::GetIdReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetId_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mt5_term_api::GetIdReply>* Connection::Stub::PrepareAsyncGetIdRaw(::grpc::ClientContext* context, const ::mt5_term_api::GetIdRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::mt5_term_api::GetIdReply, ::mt5_term_api::GetIdRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetId_, context, request);
}

::grpc::ClientAsyncResponseReader< ::mt5_term_api::GetIdReply>* Connection::Stub::AsyncGetIdRaw(::grpc::ClientContext* context, const ::mt5_term_api::GetIdRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetIdRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::mt5_term_api::ConnectStreamEvent>* Connection::Stub::ConnectStreamRaw(::grpc::ClientContext* context, const ::mt5_term_api::ConnectRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::mt5_term_api::ConnectStreamEvent>::Create(channel_.get(), rpcmethod_ConnectStream_, context, request);
}

void Connection::Stub::async::ConnectStream(::grpc::ClientContext* context, const ::mt5_term_api::ConnectRequest* request, ::grpc::ClientReadReactor< ::mt5_term_api::ConnectStreamEvent>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::mt5_term_api::ConnectStreamEvent>::Create(stub_->channel_.get(), stub_->rpcmethod_ConnectStream_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::mt5_term_api::ConnectStreamEvent>* Connection::Stub::AsyncConnectStreamRaw(::grpc::ClientContext* context, const ::mt5_term_api::ConnectRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::mt5_term_api::ConnectStreamEvent>::Create(channel_.get(), cq, rpcmethod_ConnectStream_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::mt5_term_api::ConnectStreamEvent>* Connection::Stub::PrepareAsyncConnectStreamRaw(::grpc::ClientContext* context, const ::mt5_term_api::ConnectRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::mt5_term_api::ConnectStreamEvent>::Create(channel_.get(), cq, rpcmethod_ConnectStream_, context, request, false, nullptr);
}

::grpc::ClientReader< ::mt5_term_api::ConnectStreamEvent>* Connection::Stub::ConnectExStreamRaw(::grpc::ClientContext* context, const ::mt5_term_api::ConnectExRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::mt5_term_api::ConnectStreamEvent>::Create(channel_.get(), rpcmethod_ConnectExStream_, context, request);
}

void Connection::Stub::async::ConnectExStream(::grpc::ClientContext* context, const ::mt5_term_api::ConnectExRequest* request, ::grpc::ClientReadReactor< ::mt5_term_api::ConnectStreamEvent>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::mt5_term_api::ConnectStreamEvent>::Create(stub_->channel_.get(), stub_->rpcmethod_ConnectExStream_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::mt5_term_api::ConnectStreamEvent>* Connection::Stub::AsyncConnectExStreamRaw(::grpc::ClientContext* context, const ::mt5_term_api::ConnectExRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::mt5_term_api::ConnectStreamEvent>::Create(channel_.get(), cq, rpcmethod_ConnectExStream_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::mt5_term_api::ConnectStreamEvent>* Connection::Stub::PrepareAsyncConnectExStreamRaw(::grpc::ClientContext* context, const ::mt5_term_api::ConnectExRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::mt5_term_api::ConnectStreamEvent>::Create(channel_.get(), cq, rpcmethod_ConnectExStream_, context, request, false, nullptr);
}

Connection::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Connection_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Connection::Service, ::mt5_term_api::ConnectExRequest, ::mt5_term_api::ConnectExReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Connection::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mt5_term_api::ConnectExRequest* req,
             ::mt5_term_api::ConnectExReply* resp) {
               return service->ConnectEx(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Connection_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Connection::Service, ::mt5_term_api::ConnectRequest, ::mt5_term_api::ConnectReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Connection::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mt5_term_api::ConnectRequest* req,
             ::mt5_term_api::ConnectReply* resp) {
               return service->Connect(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Connection_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Connection::Service, ::mt5_term_api::ConnectProxyRequest, ::mt5_term_api::ConnectProxyReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Connection::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mt5_term_api::ConnectProxyRequest* req,
             ::mt5_term_api::ConnectProxyReply* resp) {
               return service->ConnectProxy(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Connection_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Connection::Service, ::mt5_term_api::CheckConnectRequest, ::mt5_term_api::CheckConnectReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Connection::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mt5_term_api::CheckConnectRequest* req,
             ::mt5_term_api::CheckConnectReply* resp) {
               return service->CheckConnect(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Connection_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Connection::Service, ::mt5_term_api::ConnectStateRequest, ::mt5_term_api::ConnectStateReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Connection::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mt5_term_api::ConnectStateRequest* req,
             ::mt5_term_api::ConnectStateReply* resp) {
               return service->ConnectState(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Connection_method_names[5],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< Connection::Service, ::mt5_term_api::OnConnectStateRequest, ::mt5_term_api::OnConnectStateReply>(
          [](Connection::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mt5_term_api::OnConnectStateRequest* req,
             ::grpc::ServerWriter<::mt5_term_api::OnConnectStateReply>* writer) {
               return service->OnConnectState(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Connection_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Connection::Service, ::mt5_term_api::ConnectionStatusRequest, ::mt5_term_api::ConnectionStatusReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Connection::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mt5_term_api::ConnectionStatusRequest* req,
             ::mt5_term_api::ConnectionStatusReply* resp) {
               return service->ConnectionStatus(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Connection_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Connection::Service, ::mt5_term_api::DisconnectRequest, ::mt5_term_api::DisconnectReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Connection::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mt5_term_api::DisconnectRequest* req,
             ::mt5_term_api::DisconnectReply* resp) {
               return service->Disconnect(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Connection_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Connection::Service, ::mt5_term_api::ReconnectRequest, ::mt5_term_api::ReconnectReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Connection::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mt5_term_api::ReconnectRequest* req,
             ::mt5_term_api::ReconnectReply* resp) {
               return service->Reconnect(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Connection_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Connection::Service, ::mt5_term_api::ConnectByTokenRequest, ::mt5_term_api::ConnectExReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Connection::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mt5_term_api::ConnectByTokenRequest* req,
             ::mt5_term_api::ConnectExReply* resp) {
               return service->ConnectByToken(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Connection_method_names[10],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Connection::Service, ::mt5_term_api::GetBrokerServersByBrokerNameRequest, ::mt5_term_api::GetBrokerServersByBrokerNameReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Connection::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mt5_term_api::GetBrokerServersByBrokerNameRequest* req,
             ::mt5_term_api::GetBrokerServersByBrokerNameReply* resp) {
               return service->GetBrokerServersByBrokerName(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Connection_method_names[11],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Connection::Service, ::mt5_term_api::ScreenshotRequest, ::mt5_term_api::ScreenshotReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Connection::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mt5_term_api::ScreenshotRequest* req,
             ::mt5_term_api::ScreenshotReply* resp) {
               return service->Screenshot(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Connection_method_names[12],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Connection::Service, ::mt5_term_api::GetIdRequest, ::mt5_term_api::GetIdReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Connection::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mt5_term_api::GetIdRequest* req,
             ::mt5_term_api::GetIdReply* resp) {
               return service->GetId(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Connection_method_names[13],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< Connection::Service, ::mt5_term_api::ConnectRequest, ::mt5_term_api::ConnectStreamEvent>(
          [](Connection::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mt5_term_api::ConnectRequest* req,
             ::grpc::ServerWriter<::mt5_term_api::ConnectStreamEvent>* writer) {
               return service->ConnectStream(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Connection_method_names[14],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< Connection::Service, ::mt5_term_api::ConnectExRequest, ::mt5_term_api::ConnectStreamEvent>(
          [](Connection::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mt5_term_api::ConnectExRequest* req,
             ::grpc::ServerWriter<::mt5_term_api::ConnectStreamEvent>* writer) {
               return service->ConnectExStream(ctx, req, writer);
             }, this)));
}

Connection::Service::~Service() {
}

::grpc::Status Connection::Service::ConnectEx(::grpc::ServerContext* context, const ::mt5_term_api::ConnectExRequest* request, ::mt5_term_api::ConnectExReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Connection::Service::Connect(::grpc::ServerContext* context, const ::mt5_term_api::ConnectRequest* request, ::mt5_term_api::ConnectReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Connection::Service::ConnectProxy(::grpc::ServerContext* context, const ::mt5_term_api::ConnectProxyRequest* request, ::mt5_term_api::ConnectProxyReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Connection::Service::CheckConnect(::grpc::ServerContext* context, const ::mt5_term_api::CheckConnectRequest* request, ::mt5_term_api::CheckConnectReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Connection::Service::ConnectState(::grpc::ServerContext* context, const ::mt5_term_api::ConnectStateRequest* request, ::mt5_term_api::ConnectStateReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Connection::Service::OnConnectState(::grpc::ServerContext* context, const ::mt5_term_api::OnConnectStateRequest* request, ::grpc::ServerWriter< ::mt5_term_api::OnConnectStateReply>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Connection::Service::ConnectionStatus(::grpc::ServerContext* context, const ::mt5_term_api::ConnectionStatusRequest* request, ::mt5_term_api::ConnectionStatusReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Connection::Service::Disconnect(::grpc::ServerContext* context, const ::mt5_term_api::DisconnectRequest* request, ::mt5_term_api::DisconnectReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Connection::Service::Reconnect(::grpc::ServerContext* context, const ::mt5_term_api::ReconnectRequest* request, ::mt5_term_api::ReconnectReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Connection::Service::ConnectByToken(::grpc::ServerContext* context, const ::mt5_term_api::ConnectByTokenRequest* request, ::mt5_term_api::ConnectExReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Connection::Service::GetBrokerServersByBrokerName(::grpc::ServerContext* context, const ::mt5_term_api::GetBrokerServersByBrokerNameRequest* request, ::mt5_term_api::GetBrokerServersByBrokerNameReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Connection::Service::Screenshot(::grpc::ServerContext* context, const ::mt5_term_api::ScreenshotRequest* request, ::mt5_term_api::ScreenshotReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Connection::Service::GetId(::grpc::ServerContext* context, const ::mt5_term_api::GetIdRequest* request, ::mt5_term_api::GetIdReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Connection::Service::ConnectStream(::grpc::ServerContext* context, const ::mt5_term_api::ConnectRequest* request, ::grpc::ServerWriter< ::mt5_term_api::ConnectStreamEvent>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Connection::Service::ConnectExStream(::grpc::ServerContext* context, const ::mt5_term_api::ConnectExRequest* request, ::grpc::ServerWriter< ::mt5_term_api::ConnectStreamEvent>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* Logs_method_names[] = {
  "/mt5_term_api.Logs/Journal",
  "/mt5_term_api.Logs/OnJournal",
  "/mt5_term_api.Logs/Experts",
  "/mt5_term_api.Logs/OnExperts",
};

std::unique_ptr< Logs::Stub> Logs::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Logs::Stub> stub(new Logs::Stub(channel, options));
  return stub;
}

Logs::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Journal_(Logs_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_OnJournal_(Logs_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_Experts_(Logs_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_OnExperts_(Logs_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::Status Logs::Stub::Journal(::grpc::ClientContext* context, const ::mt5_term_api::JournalRequest& request, ::mt5_term_api::JournalReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mt5_term_api::JournalRequest, ::mt5_term_api::JournalReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Journal_, context, request, response);
}

void Logs::Stub::async::Journal(::grpc::ClientContext* context, const ::mt5_term_api::JournalRequest* request, ::mt5_term_api::JournalReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mt5_term_api::JournalRequest, ::mt5_term_api::JournalReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Journal_, context, request, response, std::move(f));
}

void Logs::Stub::async::Journal(::grpc::ClientContext* context, const ::mt5_term_api::JournalRequest* request, ::mt5_term_api::JournalReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Journal_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mt5_term_api::JournalReply>* Logs::Stub::PrepareAsyncJournalRaw(::grpc::ClientContext* context, const ::mt5_term_api::JournalRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::mt5_term_api::JournalReply, ::mt5_term_api::JournalRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Journal_, context, request);
}

::grpc::ClientAsyncResponseReader< ::mt5_term_api::JournalReply>* Logs::Stub::AsyncJournalRaw(::grpc::ClientContext* context, const ::mt5_term_api::JournalRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncJournalRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::mt5_term_api::OnJournalReply>* Logs::Stub::OnJournalRaw(::grpc::ClientContext* context, const ::mt5_term_api::OnJournalRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::mt5_term_api::OnJournalReply>::Create(channel_.get(), rpcmethod_OnJournal_, context, request);
}

void Logs::Stub::async::OnJournal(::grpc::ClientContext* context, const ::mt5_term_api::OnJournalRequest* request, ::grpc::ClientReadReactor< ::mt5_term_api::OnJournalReply>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::mt5_term_api::OnJournalReply>::Create(stub_->channel_.get(), stub_->rpcmethod_OnJournal_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::mt5_term_api::OnJournalReply>* Logs::Stub::AsyncOnJournalRaw(::grpc::ClientContext* context, const ::mt5_term_api::OnJournalRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::mt5_term_api::OnJournalReply>::Create(channel_.get(), cq, rpcmethod_OnJournal_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::mt5_term_api::OnJournalReply>* Logs::Stub::PrepareAsyncOnJournalRaw(::grpc::ClientContext* context, const ::mt5_term_api::OnJournalRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::mt5_term_api::OnJournalReply>::Create(channel_.get(), cq, rpcmethod_OnJournal_, context, request, false, nullptr);
}

::grpc::Status Logs::Stub::Experts(::grpc::ClientContext* context, const ::mt5_term_api::JournalRequest& request, ::mt5_term_api::JournalReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mt5_term_api::JournalRequest, ::mt5_term_api::JournalReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Experts_, context, request, response);
}

void Logs::Stub::async::Experts(::grpc::ClientContext* context, const ::mt5_term_api::JournalRequest* request, ::mt5_term_api::JournalReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mt5_term_api::JournalRequest, ::mt5_term_api::JournalReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Experts_, context, request, response, std::move(f));
}

void Logs::Stub::async::Experts(::grpc::ClientContext* context, const ::mt5_term_api::JournalRequest* request, ::mt5_term_api::JournalReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Experts_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mt5_term_api::JournalReply>* Logs::Stub::PrepareAsyncExpertsRaw(::grpc::ClientContext* context, const ::mt5_term_api::JournalRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::mt5_term_api::JournalReply, ::mt5_term_api::JournalRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Experts_, context, request);
}

::grpc::ClientAsyncResponseReader< ::mt5_term_api::JournalReply>* Logs::Stub::AsyncExpertsRaw(::grpc::ClientContext* context, const ::mt5_term_api::JournalRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncExpertsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::mt5_term_api::OnJournalReply>* Logs::Stub::OnExpertsRaw(::grpc::ClientContext* context, const ::mt5_term_api::OnJournalRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::mt5_term_api::OnJournalReply>::Create(channel_.get(), rpcmethod_OnExperts_, context, request);
}

void Logs::Stub::async::OnExperts(::grpc::ClientContext* context, const ::mt5_term_api::OnJournalRequest* request, ::grpc::ClientReadReactor< ::mt5_term_api::OnJournalReply>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::mt5_term_api::OnJournalReply>::Create(stub_->channel_.get(), stub_->rpcmethod_OnExperts_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::mt5_term_api::OnJournalReply>* Logs::Stub::AsyncOnExpertsRaw(::grpc::ClientContext* context, const ::mt5_term_api::OnJournalRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::mt5_term_api::OnJournalReply>::Create(channel_.get(), cq, rpcmethod_OnExperts_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::mt5_term_api::OnJournalReply>* Logs::Stub::PrepareAsyncOnExpertsRaw(::grpc::ClientContext* context, const ::mt5_term_api::OnJournalRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::mt5_term_api::OnJournalReply>::Create(channel_.get(), cq, rpcmethod_OnExperts_, context, request, false, nullptr);
}

Logs::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Logs_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Logs::Service, ::mt5_term_api::JournalRequest, ::mt5_term_api::JournalReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Logs::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mt5_term_api::JournalRequest* req,
             ::mt5_term_api::JournalReply* resp) {
               return service->Journal(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Logs_method_names[1],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< Logs::Service, ::mt5_term_api::OnJournalRequest, ::mt5_term_api::OnJournalReply>(
          [](Logs::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mt5_term_api::OnJournalRequest* req,
             ::grpc::ServerWriter<::mt5_term_api::OnJournalReply>* writer) {
               return service->OnJournal(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Logs_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Logs::Service, ::mt5_term_api::JournalRequest, ::mt5_term_api::JournalReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Logs::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mt5_term_api::JournalRequest* req,
             ::mt5_term_api::JournalReply* resp) {
               return service->Experts(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Logs_method_names[3],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< Logs::Service, ::mt5_term_api::OnJournalRequest, ::mt5_term_api::OnJournalReply>(
          [](Logs::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mt5_term_api::OnJournalRequest* req,
             ::grpc::ServerWriter<::mt5_term_api::OnJournalReply>* writer) {
               return service->OnExperts(ctx, req, writer);
             }, this)));
}

Logs::Service::~Service() {
}

::grpc::Status Logs::Service::Journal(::grpc::ServerContext* context, const ::mt5_term_api::JournalRequest* request, ::mt5_term_api::JournalReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Logs::Service::OnJournal(::grpc::ServerContext* context, const ::mt5_term_api::OnJournalRequest* request, ::grpc::ServerWriter< ::mt5_term_api::OnJournalReply>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Logs::Service::Experts(::grpc::ServerContext* context, const ::mt5_term_api::JournalRequest* request, ::mt5_term_api::JournalReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Logs::Service::OnExperts(::grpc::ServerContext* context, const ::mt5_term_api::OnJournalRequest* request, ::grpc::ServerWriter< ::mt5_term_api::OnJournalReply>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace mt5_term_api

